export const BOOK_SERIES = [
  { id:"wwp1", subtitle:"Prime Lv.1", group:"ww" },
  { id:"wwp2", subtitle:"Prime Lv.2", group:"ww" },
  { id:"wwp3", subtitle:"Prime Lv.3", group:"ww" },
  { id:"ww5",  subtitle:"Basic Lv.5", group:"ww" },
  { id:"bew2", subtitle:"Book 2",     group:"bew" },
  { id:"bew3", subtitle:"Book 3",     group:"bew" },
  { id:"bew4", subtitle:"Book 4",     group:"bew" },
  { id:"cew1", subtitle:"Book 1",     group:"cew" },
  { id:"cew2", subtitle:"Book 2",     group:"cew" },
  { id:"cew3", subtitle:"Book 3",     group:"cew" },
  { id:"cew4", subtitle:"Book 4",     group:"cew" },
  { id:"eew1", subtitle:"Book 1",     group:"eew" },
  { id:"eew2", subtitle:"Book 2",     group:"eew" },
  { id:"eew3", subtitle:"Book 3",     group:"eew" },
  { id:"eew4", subtitle:"Book 4",     group:"eew" },
  { id:"eew5", subtitle:"Book 5",     group:"eew" },
  { id:"eew6", subtitle:"Book 6",     group:"eew" },
];
