export const MONSTER_ASSETS = {
  glyphin: {
    artUrl: "/monsters/vocabmon/glyphin.png",
    sourceUrl: "/monsters/vocabmon/_source/glyphin-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.82 },
    displayScale: 1,
  },
  lexigon: {
    artUrl: "/monsters/vocabmon/lexigon.png",
    sourceUrl: "/monsters/vocabmon/_source/lexigon-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.84 },
    displayScale: 1.38,
  },
  vocarion: {
    artUrl: "/monsters/vocabmon/vocarion.png",
    sourceUrl: "/monsters/vocabmon/_source/vocarion-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 1.58,
  },
  emberpuff: {
    artUrl: "/monsters/flame/emberpuff.png",
    sourceUrl: "/monsters/flame/_source/emberpuff-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 1,
  },
  scorchcub: {
    artUrl: "/monsters/flame/scorchcub.png",
    sourceUrl: "/monsters/flame/_source/scorchcub-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.46, y: 0.9 },
    displayScale: 1.12,
  },
  blazeking: {
    artUrl: "/monsters/flame/blazeking.png",
    sourceUrl: "/monsters/flame/_source/blazeking-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.92 },
    displayScale: 1.25,
  },
  bubblet: {
    artUrl: "/monsters/wave/bubblet.png",
    sourceUrl: "/monsters/wave/_source/bubblet-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.84 },
    displayScale: 0.96,
  },
  coralia: {
    artUrl: "/monsters/wave/coralia.png",
    sourceUrl: "/monsters/wave/_source/coralia-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 1.12,
  },
  tidalon: {
    artUrl: "/monsters/wave/tidalon.png",
    sourceUrl: "/monsters/wave/_source/tidalon-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 1.24,
  },
  sproutling: {
    artUrl: "/monsters/leaf/sproutling.png",
    sourceUrl: "/monsters/leaf/_source/sproutling-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.98,
  },
  bloomhog: {
    artUrl: "/monsters/leaf/bloomhog.png",
    sourceUrl: "/monsters/leaf/_source/bloomhog-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.14,
  },
  treant: {
    artUrl: "/monsters/leaf/treant.png",
    sourceUrl: "/monsters/leaf/_source/treant-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.92 },
    displayScale: 1.28,
  },
  shadeling: {
    artUrl: "/monsters/shadow/shadeling.png",
    sourceUrl: "/monsters/shadow/_source/shadeling-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.84 },
    displayScale: 0.96,
  },
  gloomwing: {
    artUrl: "/monsters/shadow/gloomwing.png",
    sourceUrl: "/monsters/shadow/_source/gloomwing-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 1.1,
  },
  voidrex: {
    artUrl: "/monsters/shadow/voidrex.png",
    sourceUrl: "/monsters/shadow/_source/voidrex-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 1.2,
  },
  frostpup: {
    artUrl: "/monsters/ice/frostpup.png",
    sourceUrl: "/monsters/ice/_source/frostpup-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.98,
  },
  glacuff: {
    artUrl: "/monsters/ice/glacuff.png",
    sourceUrl: "/monsters/ice/_source/glacuff-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.12,
  },
  blizzaron: {
    artUrl: "/monsters/ice/blizzaron.png",
    sourceUrl: "/monsters/ice/_source/blizzaron-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.24,
  },
  pebblump: {
    artUrl: "/monsters/rock/pebblump.png",
    sourceUrl: "/monsters/rock/_source/pebblump-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.92,
  },
  bouldug: {
    artUrl: "/monsters/rock/bouldug.png",
    sourceUrl: "/monsters/rock/_source/bouldug-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.08,
  },
  granoth: {
    artUrl: "/monsters/rock/granoth.png",
    sourceUrl: "/monsters/rock/_source/granoth-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.92 },
    displayScale: 1.18,
  },
  breezel: {
    artUrl: "/monsters/wind/breezel.png",
    sourceUrl: "/monsters/wind/_source/breezel-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 0.94,
  },
  cyclair: {
    artUrl: "/monsters/wind/cyclair.png",
    sourceUrl: "/monsters/wind/_source/cyclair-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 1.08,
  },
  tempestross: {
    artUrl: "/monsters/wind/tempestross.png",
    sourceUrl: "/monsters/wind/_source/tempestross-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.12,
  },
  slimlet: {
    artUrl: "/monsters/toxic/slimlet.png",
    sourceUrl: "/monsters/toxic/_source/slimlet-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 0.94,
  },
  venomite: {
    artUrl: "/monsters/toxic/venomite.png",
    sourceUrl: "/monsters/toxic/_source/venomite-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.08,
  },
  toxigore: {
    artUrl: "/monsters/toxic/toxigore.png",
    sourceUrl: "/monsters/toxic/_source/toxigore-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.14,
  },
  cogling: {
    artUrl: "/monsters/metal/cogling.png",
    sourceUrl: "/monsters/metal/_source/cogling-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.96,
  },
  ironax: {
    artUrl: "/monsters/metal/ironax.png",
    sourceUrl: "/monsters/metal/_source/ironax-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.08,
  },
  steelwyrm: {
    artUrl: "/monsters/metal/steelwyrm.png",
    sourceUrl: "/monsters/metal/_source/steelwyrm-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.18,
  },
  pinkpuff: {
    artUrl: "/monsters/fairy/pinkpuff.png",
    sourceUrl: "/monsters/fairy/_source/pinkpuff-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.94,
  },
  floppear: {
    artUrl: "/monsters/fairy/floppear.png",
    sourceUrl: "/monsters/fairy/_source/floppear-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.08,
  },
  lunabun: {
    artUrl: "/monsters/fairy/lunabun.png",
    sourceUrl: "/monsters/fairy/_source/lunabun-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.92 },
    displayScale: 1.14,
  },
  dustkit: {
    artUrl: "/monsters/sand/dustkit.png",
    sourceUrl: "/monsters/sand/_source/dustkit-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.94,
  },
  sandroll: {
    artUrl: "/monsters/sand/sandroll.png",
    sourceUrl: "/monsters/sand/_source/sandroll-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.05,
  },
  terradon: {
    artUrl: "/monsters/sand/terradon.png",
    sourceUrl: "/monsters/sand/_source/terradon-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.16,
  },
  spiklet: {
    artUrl: "/monsters/coral/spiklet.png",
    sourceUrl: "/monsters/coral/_source/spiklet-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 0.94,
  },
  starfish: {
    artUrl: "/monsters/coral/starfish.png",
    sourceUrl: "/monsters/coral/_source/starfish-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 1.06,
  },
  reefqueen: {
    artUrl: "/monsters/coral/reefqueen.png",
    sourceUrl: "/monsters/coral/_source/reefqueen-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.14,
  },
  spooka: {
    artUrl: "/monsters/ghost/spooka.png",
    sourceUrl: "/monsters/ghost/_source/spooka-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.86 },
    displayScale: 0.94,
  },
  phantlet: {
    artUrl: "/monsters/ghost/phantlet.png",
    sourceUrl: "/monsters/ghost/_source/phantlet-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 1.06,
  },
  hauntlord: {
    artUrl: "/monsters/ghost/hauntlord.png",
    sourceUrl: "/monsters/ghost/_source/hauntlord-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.92 },
    displayScale: 1.14,
  },
  dashpup: {
    artUrl: "/monsters/speed/dashpup.png",
    sourceUrl: "/monsters/speed/_source/dashpup-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.88 },
    displayScale: 0.94,
  },
  zoomfox: {
    artUrl: "/monsters/speed/zoomfox.png",
    sourceUrl: "/monsters/speed/_source/zoomfox-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.06,
  },
  blazedash: {
    artUrl: "/monsters/speed/blazedash.png",
    sourceUrl: "/monsters/speed/_source/blazedash-chroma.png",
    bg: "transparent",
    crop: "full-body",
    anchor: { x: 0.5, y: 0.9 },
    displayScale: 1.14,
  },
  ...createMonsterAssetEntries([
    ["bolt", ["zaplet", "thundermew", "voltiger"]],
    ["star", ["stardust", "cosmeling", "galaxion"]],
    ["psychic", ["psykit", "mindra", "cerebron"]],
    ["crystal", ["shimlit", "prismite", "crystalith"]],
    ["dragon", ["drakeling", "scalefang", "wyrmking"]],
    ["nature", ["larvix", "chrysaming", "motheron"]],
    ["lava", ["magmite", "inferite", "volcanix"]],
    ["ancient", ["fossilt", "archaeon", "titanwrex"]],
    ["cosmic", ["voidpup", "nebulark", "cosmodrake"]],
    ["dream", ["drowzee", "slumbear", "dreamon"]],
    ["dino", ["dinkit", "roarex", "terrex"]],
    ["angel", ["halowing", "wingard", "seraphon"]],
    ["candy", ["sweetlet", "sugarpaw", "candrix"]],
    ["music", ["lyrito", "melodew", "symphox"]],
    ["dark", ["shadaowolf", "nightfang", "voidhowl"]],
    ["mech", ["boltchick", "gearbot", "titanmech"]],
    ["cloud", ["pufflet", "nimbus", "stormcloud"]],
    ["lava2", ["magpup", "moltenk9", "volcanovex"]],
    ["crystal2", ["gemkit", "prismark", "diamondra"]],
  ]),
};

function createMonsterAssetEntries(lines) {
  const stageSettings = [
    { anchor: { x: 0.5, y: 0.88 }, displayScale: 0.94 },
    { anchor: { x: 0.5, y: 0.9 }, displayScale: 1.08 },
    { anchor: { x: 0.5, y: 0.92 }, displayScale: 1.18 },
  ];

  return Object.fromEntries(
    lines.flatMap(([lineId, stageIds]) =>
      stageIds.map((stageId, index) => {
        const settings = stageSettings[index] ?? stageSettings[0];
        return [
          stageId,
          {
            artUrl: `/monsters/${lineId}/${stageId}.png`,
            sourceUrl: `/monsters/${lineId}/_source/${stageId}-chroma.png`,
            bg: "transparent",
            crop: "full-body",
            anchor: settings.anchor,
            displayScale: settings.displayScale,
          },
        ];
      })
    )
  );
}

export function getMonsterAsset(stageId) {
  return MONSTER_ASSETS[stageId] ?? null;
}
