// Planning-only manifest for the monster art generation pipeline.
// This file is intentionally not wired into runtime rendering.

export const MONSTER_ART_DIRECTION_VERSION = "2026-05-23";

export const MONSTER_ART_SOURCE_REFERENCES = [
  "src/catchMons.jsx",
  "src/monsterLineConcepts.js",
  "src/monsterAssets.js",
];

export const MONSTER_STAGE_DISPLAY_SCALES = {
  1: 1,
  2: 1.38,
  3: 1.58,
};

export const MONSTER_ART_PATH_TEMPLATE = {
  source: "/monsters/{lineId}/_source/{stageId}-chroma.png",
  final: "/monsters/{lineId}/{stageId}.png",
};

const conceptMap = {
  vocabmon: "tidejaw-line",
  flame: "foxflare-line",
  wave: "tidejaw-line",
  leaf: "grovehart-line",
  bolt: "boltcat-line",
  shadow: "nightwolf-line",
  star: "crystowl-line",
  ice: "cloudwhale-line",
  rock: "cactusaur-line",
  wind: "ramcloud-line",
  toxic: "frogspell-line",
  metal: "mechamite-line",
  psychic: "crystowl-line",
  crystal: "crystowl-line",
  dragon: "volcdrake-line",
  nature: "flutterbug-line",
  lava: "volcdrake-line",
  ancient: "cactusaur-line",
  fairy: "grovehart-line",
  ghost: "nightwolf-line",
  sand: "cactusaur-line",
  speed: "boltcat-line",
  cosmic: "cloudwhale-line",
  dream: "frogspell-line",
  dino: "cactusaur-line",
  angel: "crystowl-line",
  candy: "foxflare-line",
  music: "crystowl-line",
  dark: "nightwolf-line",
  mech: "mechamite-line",
  coral: "tidejaw-line",
  cloud: "cloudwhale-line",
  lava2: "volcdrake-line",
  crystal2: "crystowl-line",
};

const artStage = (lineId, stageIndex, [stageId, name, subject, silhouette, notes = ""]) => {
  const stageNumber = stageIndex + 1;
  return {
    stage: stageNumber,
    stageId,
    name,
    subject,
    silhouette,
    notes,
    sourcePath: `/monsters/${lineId}/_source/${stageId}-chroma.png`,
    finalPath: `/monsters/${lineId}/${stageId}.png`,
    displayScale: MONSTER_STAGE_DISPLAY_SCALES[stageNumber],
  };
};

const artLine = (entry) => ({
  ...entry,
  conceptSource: conceptMap[entry.lineId],
  stages: entry.stages.map((stage, index) => artStage(entry.lineId, index, stage)),
});

export const MONSTER_ART_DIRECTION_LINES = [
  artLine({
    lineId: "vocabmon",
    type: "CORE",
    rarity: "legendary",
    theme: "Vocabulary sea guardian line built around letters, dictionary armor, and heroic aqua energy.",
    palette: ["#33D6FF", "#20B8E8", "#178FD0", "#F6E36A"],
    archetype: "Word-fin shark to abyssal leviathan.",
    silhouette: "Chunky finned reader grows into armored horned leviathan with long wave body.",
    stages: [
      ["glyphin", "GLYPHIN", "Young word-fin beast snapping up loose letters.", "Small rounded shark-lizard body, oversized fin, friendly open mouth, bright letter motes.", "Keep it cute, readable, and starter-like."],
      ["lexigon", "LEXIGON", "Dictionary-plated mid form with a glowing study horn.", "Medium armored quadruped, book-plate back, stronger jaw, horn as the focal point.", "Show plates as dictionary pages, not hard military armor."],
      ["vocarion", "VOCARION", "Abyssal word leviathan whose roar turns fear into vocabulary.", "Long S-curve sea dragon, shark head, glowing horn, broad fins, gold vocabulary aura.", "Signature boss form; preserve noble face and kid-friendly confidence."],
    ],
  }),
  artLine({
    lineId: "flame",
    type: "FLAME",
    rarity: "common",
    theme: "Cozy fire fox-cub line with candle tails, warm fur, and crown-flame growth.",
    palette: ["#FF6B35", "#FF7A4D", "#FF8A38", "#FFB347"],
    archetype: "Fox kit to crown-flame guardian.",
    silhouette: "Tiny flame puff becomes upright cub, then broad crowned fox-lion guardian.",
    stages: [
      ["emberpuff", "EMBERPUFF", "Tiny ember cub with a huggable round flame body.", "Squat teardrop body, little paws, candle tuft, soft cheeks.", "Warm and plush rather than dangerous."],
      ["scorchcub", "SCORCHCUB", "Brave flame-mane cub ready to defend friends.", "Medium fox-cub stance, larger ears, starburst mane, compact tail flame.", "Give it a confident lean and readable facial markings."],
      ["blazeking", "BLAZEKING", "Crown-flame guardian leading with heat and pride.", "Tall fox-lion body, flame crown, sweeping tail, bigger paws.", "Heroic final form; crown should be flame, not metal."],
    ],
  }),
  artLine({
    lineId: "wave",
    type: "WAVE",
    rarity: "common",
    theme: "Bubble fish to ocean crest dragon using reef-blue bodies and foam highlights.",
    palette: ["#44AAFF", "#5BB9FF", "#63C8FF", "#7FD7FF"],
    archetype: "Bubble fish to tidal dragon.",
    silhouette: "Round bubble body grows fins and coral details, then crested aquatic dragon mass.",
    stages: [
      ["bubblet", "BUBBLET", "Bouncy bubble fish drifting with a grin.", "Round orb fish, tiny fins, bubble tail, large happy eyes.", "Transparent bubble shine should read at icon size."],
      ["coralia", "CORALIA", "Coral fin guardian singing to calm the tide.", "Oval fish-dragon body, coral crown, side fins, flowing tail fins.", "Blend coral accents with blue body, no sharp menace."],
      ["tidalon", "TIDALON", "Ocean crest dragon ruling waves with quiet grace.", "Tall aquatic dragon, crest fin, broad flippers, wave-shaped tail.", "Elegant guardian posture with foam glow."],
    ],
  }),
  artLine({
    lineId: "leaf",
    type: "LEAF",
    rarity: "common",
    theme: "Sprout pet to ancient grove keeper with leaf armor and pollen softness.",
    palette: ["#44CC44", "#52D652", "#6DDB63", "#8BE06B"],
    archetype: "Seedling pup to forest treant.",
    silhouette: "Small sprout head grows petal back, then trunk body and canopy arms.",
    stages: [
      ["sproutling", "SPROUTLING", "Sprout pup seedling that grows from praise and play.", "Tiny round puppy body, two-leaf sprout, seed paws.", "Make the sprout shape unmistakable."],
      ["bloomhog", "BLOOMHOG", "Petal-backed buddy protecting friends with pollen fluff.", "Chunky hedgehog body, flower petal shell, stub legs.", "Petals should form a friendly shield."],
      ["treant", "TREANT", "Ancient grove keeper sheltering the forest.", "Large tree-bodied guardian, branch arms, leafy crown, root feet.", "Keep face gentle and wise."],
    ],
  }),
  artLine({
    lineId: "bolt",
    type: "BOLT",
    rarity: "rare",
    theme: "Lightning kitten to sky-strike tiger with zigzag ears and electric whiskers.",
    palette: ["#FFCC00", "#FFD54D", "#FFE066", "#FFF08A"],
    archetype: "Electric cat to thunder tiger.",
    silhouette: "Compact cat shape gains longer legs, then large tiger stance with bolt tail.",
    stages: [
      ["zaplet", "ZAPLET", "Static kitten spark that moves before you blink.", "Small cat loaf, zigzag ears, plug-spark whiskers, bolt tail nub.", "Cute mischief first, electricity second."],
      ["thundermew", "THUNDERMEW", "Stormclaw prowler charging the field with roars.", "Lean teen cat, arched back, longer lightning tail, sparking claws.", "Use dynamic diagonal pose."],
      ["voltiger", "VOLTIGER", "Sky-strike tiger turning thunder into speed.", "Large tiger silhouette, striped lightning marks, high tail bolt, strong paws.", "Final should feel fast and premium."],
    ],
  }),
  artLine({
    lineId: "shadow",
    type: "SHADOW",
    rarity: "superrare",
    theme: "Moonlit shadow spirit line with violet glow, smoke wings, and abyssal drake finish.",
    palette: ["#CC44FF", "#D96CFF", "#E087FF", "#F0A3FF"],
    archetype: "Wisp to shadow wing drake.",
    silhouette: "Small wisp expands into floating winged phantom, then bulky void drake.",
    stages: [
      ["shadeling", "SHADELING", "Mischief wisp child hiding in moonlit corners.", "Tiny floating ghost body, crescent tuft, tapering shadow tail.", "Keep expression playful, not scary."],
      ["gloomwing", "GLOOMWING", "Night silk phantom floating without a sound.", "Medium phantom, soft bat-silk wings, trailing smoke lower body.", "Wings should feel cloth-like and weightless."],
      ["voidrex", "VOIDREX", "Abyssal wing drake that swallows light with a stare.", "Large drake head and shoulders, void wings, smoky tail, glowing eyes.", "Use negative space carefully to retain readable shape."],
    ],
  }),
  artLine({
    lineId: "star",
    type: "STAR",
    rarity: "legendary",
    theme: "Celestial wish spark line with comet trails, gold light, and phoenix final form.",
    palette: ["#FFD700", "#FFE27A", "#FFE894", "#FFF1B0"],
    archetype: "Wish spark to celestial phoenix.",
    silhouette: "Tiny star sprite grows into hopping comet, then broad phoenix flame wings.",
    stages: [
      ["stardust", "STARDUST", "Tiny wish spark born where comets fall.", "Small star core, little feet, comet dust tail.", "Must read as a living star, not just a particle."],
      ["cosmeling", "COSMELING", "Star trail hopper collecting dreams across space.", "Bouncy creature with comet tail, longer limbs, star ear points.", "Pose mid-hop with visible trail."],
      ["galaxion", "GALAXION", "Celestial phoenix lord with rare skyfire presence.", "Large bird-fire silhouette, sweeping wings, crown plume, star tail fans.", "Legendary final; make the wings the icon."],
    ],
  }),
  artLine({
    lineId: "ice",
    type: "ICE",
    rarity: "common",
    theme: "Frost fox and wolf line with glacier armor and calm blue-white magic.",
    palette: ["#88DDFF", "#9DD8F5", "#7BBEE0", "#5E9EBF"],
    archetype: "Ice pup to blizzard dragon.",
    silhouette: "Small fox pup grows armored wolf mass, then horned ice dragon profile.",
    stages: [
      ["frostpup", "FROSTPUP", "Ice fox pup leaving frost prints.", "Small fox body, fluffy tail, frosted paws, snowflake cheek mark.", "Soft, powdery edges."],
      ["glacuff", "GLACUFF", "Ice wolf teen armored in ancient frost.", "Medium wolf stance, ice shoulder plates, icicle mane, thicker legs.", "Armor should be crystalline, not metal."],
      ["blizzaron", "BLIZZARON", "Ice dragon sovereign breathing time-freezing blizzards.", "Large dragon body, icy horns, long tail, glacier wing shapes.", "Regal and cold with a readable face."],
    ],
  }),
  artLine({
    lineId: "rock",
    type: "ROCK",
    rarity: "common",
    theme: "Stone pet line from rolling pebble to gem-memory mountain golem.",
    palette: ["#CCAA77", "#A8967F", "#8C7A6B", "#7A6A5C"],
    archetype: "Pebble to bulldog to stone golem.",
    silhouette: "Round rock lump gains bulldog shell, then massive golem torso with gem core.",
    stages: [
      ["pebblump", "PEBBLUMP", "Living pebble rolling downhill for fun.", "Round rock body, tiny feet, simple crack smile.", "Make it charmingly uneven."],
      ["bouldug", "BOULDUG", "Rock bulldog whose cracks grow stronger.", "Low bulldog stance, boulder shell, stub tail, heavy paws.", "Sturdy and loyal, not aggressive."],
      ["granoth", "GRANOTH", "Ancient stone golem with memory gems.", "Huge blocky body, broad arms, small head, glowing gem seams.", "Final needs strong silhouette and cyan gem focus."],
    ],
  }),
  artLine({
    lineId: "wind",
    type: "WIND",
    rarity: "rare",
    theme: "Airborne bird line with vortex eyes, teal wind ribbons, and storm condor scale.",
    palette: ["#88FFCC", "#7DD8B8", "#3ABBA8", "#4A88CC"],
    archetype: "Swallow to owl to storm condor.",
    silhouette: "Small swooping bird grows round owl wings, then huge condor span.",
    stages: [
      ["breezel", "BREEZEL", "Swallow wind-rider faster than a whisper.", "Tiny streamlined bird, fork tail, wind scarf trail.", "Keep it light and fast."],
      ["cyclair", "CYCLAIR", "Vortex owl that sees the eye of every storm.", "Round owl body, spiral chest, broad short wings, focused eyes.", "Vortex motif should be central."],
      ["tempestross", "TEMPESTROSS", "Storm condor sovereign with horizon-wide wings.", "Massive condor wingspan, storm crest, long tail feathers.", "Needs a wide horizontal read."],
    ],
  }),
  artLine({
    lineId: "toxic",
    type: "TOXIC",
    rarity: "rare",
    theme: "Bubbly slime and frogspell line with acid bubbles and comic danger.",
    palette: ["#88FF44", "#88EE66", "#44882A", "#336622"],
    archetype: "Slime baby to poison frog-lizard to acid dragon.",
    silhouette: "Blobby droplet becomes squat frog-lizard, then heavier dragon with acid sacs.",
    stages: [
      ["slimlet", "SLIMLET", "Bubbly slime baby whose hugs leave sticky marks.", "Small droplet body, bubbles inside, tiny hands, wide smile.", "Gross-cute, not hazardous horror."],
      ["venomite", "VENOMITE", "Poison frog-lizard with a melting tongue.", "Squat frog-lizard, big throat bubble, long tongue curl, spotted back.", "Tongue can be playful and readable."],
      ["toxigore", "TOXIGORE", "Acid dragon leaving craters with every step.", "Large low dragon, acid sacs, heavy tail, bubbling back spines.", "Make acid glow bright lime."],
    ],
  }),
  artLine({
    lineId: "metal",
    type: "METAL",
    rarity: "rare",
    theme: "Clockwork metal line from tiny gear creature to chrome wyrm.",
    palette: ["#AABBCC", "#C8B89A", "#7A8890", "#788A98"],
    archetype: "Gear helper to armored bear to steel dragon.",
    silhouette: "Small cog body gains bear armor, then long plated wyrm frame.",
    stages: [
      ["cogling", "COGLING", "Gear creature ticking in perfect time.", "Round gear torso, small limbs, keyhole face, antenna bolt.", "Toy-like and buildable."],
      ["ironax", "IRONAX", "Iron war bear forged in magma pits.", "Bulky bear silhouette, armored shoulders, axe-like forearms.", "Avoid realistic weapons; keep tool-shaped forms."],
      ["steelwyrm", "STEELWYRM", "Chrome dragon whose scales deflect lightning.", "Long segmented dragon, metal plates, fin-like blades, glowing core.", "Reflective chrome with clear outline."],
    ],
  }),
  artLine({
    lineId: "psychic",
    type: "PSYCHIC",
    rarity: "superrare",
    theme: "Mind-reading cat and fox line with prism eyes, tails, and sphinx mystery.",
    palette: ["#EE88FF", "#C8A8E8", "#A880C8", "#7A5AA8"],
    archetype: "Psychic kitten to mind fox to sphinx.",
    silhouette: "Small cat grows multiple tails, then seated sphinx with psychic halo.",
    stages: [
      ["psykit", "PSYKIT", "Psychic kitten reading thoughts before they form.", "Small cat with oversized head, third-eye gem, floating pebble toys.", "Curious expression is key."],
      ["mindra", "MINDRA", "Mind fox weaving illusions with three tails.", "Sleek fox, three ribbon tails, forehead gem, floating rings.", "Tails should create a clear fan."],
      ["cerebron", "CEREBRON", "Psychic sphinx rearranging reality.", "Seated sphinx, broad paws, ornate head crest, hovering mind halo.", "Elegant, ancient, and readable."],
    ],
  }),
  artLine({
    lineId: "crystal",
    type: "CRYSTAL",
    rarity: "superrare",
    theme: "Prismatic fairy and fox line ending in a refractive crystal colossus.",
    palette: ["#88EEFF", "#B8ECFF", "#6AABCC", "#4A8AAA"],
    archetype: "Crystal spark to prism fox to crystal golem.",
    silhouette: "Tiny shard fairy becomes fox with prism wings, then broad crystalline titan.",
    stages: [
      ["shimlit", "SHIMLIT", "Crystal fairy spark refracting light into rainbows.", "Tiny sprite body, shard wings, diamond head tuft.", "Light and delicate."],
      ["prismite", "PRISMITE", "Prism-winged fox leaving rainbow trails.", "Fox body, faceted wing panels, long tail prism, pointed ears.", "Balance animal form and crystal wings."],
      ["crystalith", "CRYSTALITH", "Crystal colossus refracting the whole sky.", "Large golem body, faceted shoulders, gem crown, heavy shard fists.", "Use simple facets for small-size clarity."],
    ],
  }),
  artLine({
    lineId: "dragon",
    type: "DRAGON",
    rarity: "superrare",
    theme: "Classic red dragon evolution with smoke, scale fangs, and royal final form.",
    palette: ["#FF6644", "#CC4422", "#AA2A18", "#880E04"],
    archetype: "Baby dragon to dragon lord.",
    silhouette: "Small chubby dragon grows claws and wings, then crowned heavy dragon king.",
    stages: [
      ["drakeling", "DRAKELING", "Baby dragon breathing more smoke than fire.", "Small round dragon, stub wings, smoke puff, oversized snout.", "Cute hatchling proportions."],
      ["scalefang", "SCALEFANG", "Dragon teen with stone-cutting claws.", "Lean biped dragon, larger wings, sharp claws, scale cheek plates.", "Confident teen energy."],
      ["wyrmking", "WYRMKING", "Dragon lord before whom lesser dragons bow.", "Massive dragon, horn crown, broad wings, long tail coil.", "Regal rather than villainous."],
    ],
  }),
  artLine({
    lineId: "nature",
    type: "NATURE",
    rarity: "superrare",
    theme: "Leaf larva to cosmic moth sovereign using shield leaves and stained-glass wings.",
    palette: ["#FFCC44", "#88CC44", "#CC66AA", "#6633AA"],
    archetype: "Larva to butterfly to cosmic moth.",
    silhouette: "Bean crawler becomes winged chrysalis, then huge moth wings with star map.",
    stages: [
      ["larvix", "LARVIX", "Leaf-shield larva wearing a buckler.", "Chubby caterpillar, single big leaf shield, tiny feet, curled antennae.", "Adventurer bug buddy."],
      ["chrysaming", "CHRYSAMING", "Crystal butterfly carrying ancient pollen.", "Cocoon torso, emerging angular wings, pollen motes.", "Stage should bridge larva and moth."],
      ["motheron", "MOTHERON", "Cosmic moth sovereign with a galaxy map in its wings.", "Large moth body, wide patterned wings, crescent antennae.", "Make wing pattern the hero detail."],
    ],
  }),
  artLine({
    lineId: "lava",
    type: "LAVA",
    rarity: "legendary",
    theme: "Volcanic creature line from magma slug to lava phoenix lord.",
    palette: ["#FF4400", "#CC2200", "#AA1A00", "#FFB300"],
    archetype: "Magma slug to salamander to phoenix.",
    silhouette: "Low slug becomes lizard, then winged phoenix with molten tail.",
    stages: [
      ["magmite", "MAGMITE", "Magma slug leaving molten tracks on stone.", "Low rounded slug, lava trail, small basalt shell spots.", "Make the trail part of the pose."],
      ["inferite", "INFERITE", "Lava salamander hot enough to melt iron.", "Long salamander, glowing belly, ember feet, tail flame.", "Sleek but still collectible."],
      ["volcanix", "VOLCANIX", "Lava phoenix lord rising from eruptions.", "Large phoenix wings, molten feather tips, crest plume, lava tail.", "Legendary firebird silhouette."],
    ],
  }),
  artLine({
    lineId: "ancient",
    type: "ANCIENT",
    rarity: "legendary",
    theme: "Fossil spirit line with amber, ghost energy, and prehistoric rex power.",
    palette: ["#EED8B8", "#C8B89A", "#9966FF", "#FFAA44"],
    archetype: "Fossil hatchling to raptor spirit to titan rex.",
    silhouette: "Small fossil chick grows raptor bones, then huge rex colossus with energy seams.",
    stages: [
      ["fossilt", "FOSSILT", "Fossil hatchling awakened from amber sleep.", "Tiny dino chick, amber shell piece, fossil stripe marks.", "Ancient but adorable."],
      ["archaeon", "ARCHAEON", "Raptor spirit animated by ghost energy.", "Lean raptor skeleton shape, teal spirit outline, feather hints.", "Readable bones without being creepy."],
      ["titanwrex", "TITANWREX", "Ancient rex colossus older than memory.", "Huge rex head and tail, gold bone sheen, purple energy cracks.", "Big legendary dinosaur read."],
    ],
  }),
  artLine({
    lineId: "fairy",
    type: "FAIRY",
    rarity: "common",
    theme: "Soft bunny fairy line with flowers, moon horns, and healing warmth.",
    palette: ["#FF88CC", "#FF99DD", "#FFAADD", "#FFBBEE"],
    archetype: "Fluffy bunny to moon rabbit queen.",
    silhouette: "Round puff bunny grows floppy ears and flower crown, then tall horned moon rabbit.",
    stages: [
      ["pinkpuff", "PINKPUFF", "Fluffy pink bunny giving warm worry-healing hugs.", "Round cotton body, tiny ears, little paws, blush cheeks.", "Maximum plush appeal."],
      ["floppear", "FLOPPEAR", "Flower-crowned rabbit dancing in moonlit meadows.", "Long floppy ears, flower crown, nimble feet, ribbon tail.", "Pose should feel like a small dance step."],
      ["lunabun", "LUNABUN", "Moon-horn rabbit queen ruling night with grace.", "Tall rabbit, crescent horn, flowing ear ribbons, moon tail.", "Graceful final, not too ornate."],
    ],
  }),
  artLine({
    lineId: "ghost",
    type: "GHOST",
    rarity: "rare",
    theme: "Shy ghost line with teal glow, floating sheets, and crowned haunted nobility.",
    palette: ["#66DDEE", "#CCEEEE", "#AADDEE", "#88CCDD"],
    archetype: "Tiny ghost to crowned haunt lord.",
    silhouette: "Small sheet ghost gains glowing eyes and hands, then tall crowned phantom.",
    stages: [
      ["spooka", "SPOOKA", "Tiny shy ghost disappearing when reached for.", "Small sheet shape, peekaboo eyes, curled wisp tail.", "Sweet and bashful."],
      ["phantlet", "PHANTLET", "Glowing-eyed ghost floating through walls humming.", "Medium ghost body, floating hands, brighter eye glow, trailing hem.", "Use teal glow as main read."],
      ["hauntlord", "HAUNTLORD", "Crowned ghost sovereign ruling haunted places.", "Tall phantom, crown, cape-like sheet, broad shadow base.", "Noble haunted-house mascot."],
    ],
  }),
  artLine({
    lineId: "sand",
    type: "SAND",
    rarity: "common",
    theme: "Desert pet line from sand mouse to armored roller and heat-storing lizard king.",
    palette: ["#DDAA55", "#EEC88A", "#C8983C", "#A87830"],
    archetype: "Sand mouse to armadillo to desert lizard.",
    silhouette: "Tiny mouse curls into round armadillo form, then larger spined lizard.",
    stages: [
      ["dustkit", "DUSTKIT", "Sand mouse pup curling its tail in warmth.", "Small mouse body, curled tail, big ears, sand speckles.", "Soft desert baby."],
      ["sandroll", "SANDROLL", "Armadillo roller curling into a ball to escape.", "Round armored body, visible bands, small snout, tucked paws.", "Needs clear rolling form."],
      ["terradon", "TERRADON", "Desert king lizard storing heat in spines.", "Large lizard, back spines, heavy tail, plated head.", "Warm, sturdy, sun-baked final."],
    ],
  }),
  artLine({
    lineId: "speed",
    type: "SPEED",
    rarity: "rare",
    theme: "Orange racer fox line with wind streaks, afterimages, and diagonal sprint poses.",
    palette: ["#FF8833", "#FF9944", "#EE6611", "#CC4400"],
    archetype: "Speed fox pup to afterimage racer.",
    silhouette: "Small running pup stretches into sleek fox, then long-legged racer with flame-like trail.",
    stages: [
      ["dashpup", "DASHPUP", "Speedy orange fox pup leaving wind streaks.", "Small fox in running pose, swept ears, short streak tail.", "Diagonal motion line is important."],
      ["zoomfox", "ZOOMFOX", "Speed-line fox teen whose fur blurs at full sprint.", "Lean fox, long legs, blur stripes, swept tail.", "Show a single clean afterimage."],
      ["blazedash", "BLAZEDASH", "Afterimage fox racer breaking sound barriers.", "Long racer body, multiple tail streaks, low sprint stance.", "Fastest line; silhouette should lean forward."],
    ],
  }),
  artLine({
    lineId: "cosmic",
    type: "COSMIC",
    rarity: "superrare",
    theme: "Alien void pup line with galaxy markings, many eyes, and cosmic drake finale.",
    palette: ["#AA66FF", "#9966CC", "#6644BB", "#3311AA"],
    archetype: "Alien blob to galaxy drake.",
    silhouette: "Blob pup gains many eyes and star map, then dragon form with cosmic body.",
    stages: [
      ["voidpup", "VOIDPUP", "Alien blob pup curiously poking everything.", "Small blob quadruped, antenna nubs, big curious eyes.", "Odd but friendly."],
      ["nebulark", "NEBULARK", "Galaxy-pattern alien seeing with tiny eyes.", "Medium alien beast, multiple small eyes, star-speckled back.", "Eyes should feel cute, not unsettling."],
      ["cosmodrake", "COSMODRAKE", "Cosmic star dragon whose body maps the universe.", "Large dragon, constellation body marks, nebula tail, star horns.", "Keep constellation lines visible."],
    ],
  }),
  artLine({
    lineId: "dream",
    type: "DREAM",
    rarity: "rare",
    theme: "Sleepy cloud-dream line with soft purple glow, Z shapes, and celestial guardian calm.",
    palette: ["#C8A0FF", "#D8C8F8", "#C8B8F0", "#8866CC"],
    archetype: "Dream cloud to bear to celestial guardian.",
    silhouette: "Puffy cloud shape gains bear limbs, then tall floating guardian with moon aura.",
    stages: [
      ["drowzee", "DROWZEE", "Sleepy cloud puff dreaming of sweet things.", "Tiny cloud ball, closed sleepy eyes, dangling feet, small Z trail.", "Soft and rounded."],
      ["slumbear", "SLUMBEAR", "Dream cloud bear with floating Z shapes.", "Bear cub made of cloud, ear puffs, sleepy paws, Z motes.", "Make it huggable."],
      ["dreamon", "DREAMON", "Celestial dream guardian protecting sleeping minds.", "Tall floating guardian, cloud mane, moon halo, flowing tail.", "Calm protector posture."],
    ],
  }),
  artLine({
    lineId: "dino",
    type: "DINO",
    rarity: "common",
    theme: "Green dinosaur line from hungry hatchling to spine-finned apex predator.",
    palette: ["#44BB33", "#77CC55", "#3A9930", "#2A7722"],
    archetype: "Baby dino to apex rex.",
    silhouette: "Stubby baby dino grows wings and roar crest, then heavy predator with spine fins.",
    stages: [
      ["dinkit", "DINKIT", "Baby dino hatchling with stubby arms and huge appetite.", "Small round dino, oversized head, tiny arms, egg chip on head.", "Cute appetite-focused starter."],
      ["roarex", "ROAREX", "Teen dino with wings and valley-shaking roar.", "Medium raptor body, small wings, open roar pose, tail balance.", "Bridge cute and powerful."],
      ["terrex", "TERREX", "Dino apex predator with radiating spine fins.", "Large rex stance, dorsal fins, heavy tail, strong jaw.", "Powerful but not too scary."],
    ],
  }),
  artLine({
    lineId: "angel",
    type: "ANGEL",
    rarity: "superrare",
    theme: "Halo bird line with guardian warmth, white feathers, and six-wing seraph finale.",
    palette: ["#FFE066", "#F0F0FF", "#E8E8FF", "#D8D8FF"],
    archetype: "Halo bird to seraph.",
    silhouette: "Small bird with halo gains guardian wings, then tall six-wing celestial form.",
    stages: [
      ["halowing", "HALOWING", "Baby angel bird with a sunlight halo.", "Small chick, tiny halo, little wings, soft glow.", "Gentle and bright."],
      ["wingard", "WINGARD", "Guardian angel bird carrying warmth and hope.", "Medium bird, broader wings, shield-like chest feathers, halo ring.", "Protector mascot energy."],
      ["seraphon", "SERAPHON", "Six-winged seraph lighting the whole sky.", "Tall avian spirit, six wings, large halo, flowing tail feathers.", "Premium celestial final with clear wing count."],
    ],
  }),
  artLine({
    lineId: "candy",
    type: "CANDY",
    rarity: "rare",
    theme: "Candy creature line with pink sugar, lollipop props, rainbow flavor, and dragon finale.",
    palette: ["#FF66AA", "#FF99CC", "#FFAADD", "#CC2277"],
    archetype: "Candy blob to candy cat to candy dragon.",
    silhouette: "Round sweet blob grows cat paws, then curled candy dragon with scale sweets.",
    stages: [
      ["sweetlet", "SWEETLET", "Sweet candy blob leaving a sugary trail.", "Small gumdrop body, candy shine, tiny feet, syrup trail.", "Glossy but not sticky-looking."],
      ["sugarpaw", "SUGARPAW", "Candy cat purring in rainbow flavors.", "Cat body, lollipop wand tail, sprinkle cheek marks, round paws.", "Use candy prop without clutter."],
      ["candrix", "CANDRIX", "Rainbow candy dragon with flavor scales.", "Curled dragon, candy horns, gumdrop scales, ribbon tail.", "Bright final with controlled color accents."],
    ],
  }),
  artLine({
    lineId: "music",
    type: "MUSIC",
    rarity: "rare",
    theme: "Music note creature line evolving into rhythm bird and resonant fox-bird performer.",
    palette: ["#7799FF", "#5588FF", "#3355BB", "#2244AA"],
    archetype: "Music note to bird to fox-bird.",
    silhouette: "Single note shape gains wings, then hybrid performer with sound-wave mane.",
    stages: [
      ["lyrito", "LYRITO", "Note-shaped creature singing one pure tone.", "Simple eighth-note body, little face in note head, tiny feet.", "Must read as a living note."],
      ["melodew", "MELODEW", "Musical note bird beating wings in rhythm.", "Bird body built from note shapes, wing bars, treble tail curl.", "Rhythmic wing pose."],
      ["symphox", "SYMPHOX", "Sound wave fox-bird whose mane resonates with music.", "Fox-bird hybrid, wave mane, winged forelimbs, long note tail.", "Show flowing sound waves as silhouette."],
    ],
  }),
  artLine({
    lineId: "dark",
    type: "DARK",
    rarity: "rare",
    theme: "Dark wolf line with silver eyes, constellation fur, and void howl finale.",
    palette: ["#AAAAFF", "#2A2A3A", "#22223A", "#18183A"],
    archetype: "Shadow wolf pup to void alpha.",
    silhouette: "Low wolf pup grows starry body and twin smoke tail, then alpha howl pose.",
    stages: [
      ["shadaowolf", "SHADAOWOLF", "Shadow wolf pup with silver eyes in the dark.", "Small wolf pup, big ears, shadow paws, silver eye glow.", "Preserve current id spelling."],
      ["nightfang", "NIGHTFANG", "Star-pattern wolf teen dotted with constellations.", "Lean wolf, longer muzzle, star spots, trailing tail smoke.", "Constellation marks should remain sparse."],
      ["voidhowl", "VOIDHOWL", "Void wolf sovereign whose howl silences the cosmos.", "Large alpha wolf, raised head, twin smoke tails, eclipse mane.", "Dramatic but loyal."],
    ],
  }),
  artLine({
    lineId: "mech",
    type: "MECH",
    rarity: "rare",
    theme: "Robot bird and modular mech line with cyan LEDs, gears, and upgradeable parts.",
    palette: ["#00FFCC", "#8899AA", "#667788", "#445566"],
    archetype: "Robot hatchling to modular mech titan.",
    silhouette: "Small robotic chick becomes boxy gear bot, then broad titan with jet boots.",
    stages: [
      ["boltchick", "BOLTCHICK", "Robot bird hatchling blinking LED eyes in Morse code.", "Tiny chick bot, beak plate, LED eyes, wind-up feet.", "Toy robot charm."],
      ["gearbot", "GEARBOT", "Gear-chest robot with a spinning power core.", "Boxy helper bot, gear chest, clamp hands, antenna.", "Readable modular parts."],
      ["titanmech", "TITANMECH", "Mega mech warrior with jet boots.", "Broad mech, tool gauntlets, jet boots, cyan chest core.", "Powerful but non-military."],
    ],
  }),
  artLine({
    lineId: "coral",
    type: "CORAL",
    rarity: "common",
    theme: "Warm reef line from sea urchin to starfish and coral dragon queen.",
    palette: ["#FF8855", "#FFAA66", "#FF7733", "#CC3366"],
    archetype: "Reef creature to coral dragon.",
    silhouette: "Spiky round urchin becomes five-point star, then flowing coral dragon queen.",
    stages: [
      ["spiklet", "SPIKLET", "Spiny sea urchin with orange underwater glow.", "Round urchin body, short soft spikes, small face in center.", "Spikes should be cute and blunt."],
      ["starfish", "STARFISH", "Star creature sensing currents with each tip.", "Five-point star body, central face, small tube feet.", "Simple iconic star silhouette."],
      ["reefqueen", "REEFQUEEN", "Coral dragon queen whose anemone mane feeds the reef.", "Elegant sea dragon, coral crown, anemone mane, flowing fins.", "Warm coral and magenta focal points."],
    ],
  }),
  artLine({
    lineId: "cloud",
    type: "CLOUD",
    rarity: "common",
    theme: "Weather cloud line from puff pet to storm cloud titan with lightning crown.",
    palette: ["#AACCFF", "#EEF4FF", "#C8D8F8", "#8899BB"],
    archetype: "Cloud puff to thundercloud titan.",
    silhouette: "Small cloud puff gains storm ears and bolts, then huge cloud mass with crown.",
    stages: [
      ["pufflet", "PUFFLET", "Tiny cloud puff drifting on a gentle breeze.", "Small rounded cloud, dangling feet, soft swirl tuft.", "Softest common line."],
      ["nimbus", "NIMBUS", "Storm cloud with lightning ears in drizzle.", "Medium cloud body, bolt ears, raindrop fringe, sleepy smile.", "Balance storm and cute."],
      ["stormcloud", "STORMCLOUD", "Thunder cloud titan with a lightning crown.", "Large cloud mass, crown bolts, heavy underside, broad arms.", "Final should feel like a weather boss."],
    ],
  }),
  artLine({
    lineId: "lava2",
    type: "LAVA2",
    rarity: "superrare",
    theme: "Magma hound line with lava paw prints, armor plates, and eruption mane.",
    palette: ["#FF3300", "#AA2200", "#661100", "#440800"],
    archetype: "Magma puppy to volcano dragon hound.",
    silhouette: "Small puppy becomes armored wolf, then dragon-hound overlord with erupting mane.",
    stages: [
      ["magpup", "MAGPUP", "Magma puppy leaving lava paw prints.", "Small dog body, glowing paws, ember ears, lava droplet tail.", "Friendly hot-foot puppy."],
      ["moltenk9", "MOLTENK9", "Magma wolf with armor and lava joints.", "Medium wolf, basalt plates, glowing seams, hot paws.", "Armor from cooled lava."],
      ["volcanovex", "VOLCANOVEX", "Volcano overlord dragon with an eruption mane.", "Large dragon-hound, crater mane, heavy paws, molten tail.", "Superrare final; make mane the signature."],
    ],
  }),
  artLine({
    lineId: "crystal2",
    type: "CRYSTAL2",
    rarity: "legendary",
    theme: "Gem seed and prism golem line culminating in diamond dragon empress.",
    palette: ["#88FFFF", "#AAEEFF", "#55AABB", "#2A6888"],
    archetype: "Gem seed to prism golem to diamond dragon.",
    silhouette: "Small seed crystal grows blocky prism body, then elegant diamond dragon.",
    stages: [
      ["gemkit", "GEMKIT", "Crystal seed creature refracting tiny rainbows.", "Small gem seed body, sprout shard, tiny paws, bright core.", "Baby gemstone mascot."],
      ["prismark", "PRISMARK", "Crystal prism golem bending light into power.", "Medium golem, prism torso, shard arms, refracted beam accents.", "Facets should be simple and bold."],
      ["diamondra", "DIAMONDRA", "Crystal dragon empress pouring rainbow light from within.", "Large elegant dragon, diamond crown, faceted wings, long gem tail.", "Legendary crystalline elegance."],
    ],
  }),
];

export const MONSTER_ART_DIRECTION_BY_LINE = Object.fromEntries(
  MONSTER_ART_DIRECTION_LINES.map((line) => [line.lineId, line])
);

export const MONSTER_ART_DIRECTION_BY_STAGE = Object.fromEntries(
  MONSTER_ART_DIRECTION_LINES.flatMap((line) =>
    line.stages.map((stage) => [stage.stageId, { lineId: line.lineId, ...stage }])
  )
);

export const MONSTER_ART_DIRECTION_SUMMARY = {
  lineCount: MONSTER_ART_DIRECTION_LINES.length,
  stageCount: MONSTER_ART_DIRECTION_LINES.reduce((total, line) => total + line.stages.length, 0),
  expectedLineCount: 34,
  expectedStageCount: 102,
};
