// Wonderful World Prime word bank.
export const WWP_WORDS_DB = {
  "wwp1_1": [
    {w:"same",m:"\uac19\uc740",def:"not different; exactly like something",unit:1,opts:["same", "tell", "technology", "different"]},
    {w:"tell",m:"\uad6c\ubcc4\ud558\ub2e4",def:"to see the difference between two people or things",unit:1,opts:["tell", "different", "same", "technology"]},
    {w:"different",m:"\ub2e4\ub978",def:"not the same; unlike",unit:1,opts:["crazy", "same", "different", "quiet"]},
    {w:"loud",m:"\uc2dc\ub044\ub7ec\uc6b4",def:"making a lot of noise",unit:1,opts:["different", "technology", "tell", "loud"]},
    {w:"silly",m:"\uc5c9\ub6b1\ud55c",def:"playful and funny",unit:1,opts:["quiet", "silly", "crazy", "technology"]},
    {w:"quiet",m:"\uc870\uc6a9\ud55c",def:"making no noise",unit:1,opts:["quiet", "tell", "loud", "same"]},
    {w:"crazy",m:"\uc5f4\uad11\ud558\ub294",def:"very interested in something or someone",unit:1,opts:["technology", "quiet", "crazy", "different"]},
    {w:"technology",m:"\uacfc\ud559 \uae30\uc220",def:"advanced scientific knowledge",unit:1,opts:["technology", "different", "quiet", "crazy"]},
  ],
  "wwp1_2": [
    {w:"amazing",m:"\ub180\ub77c\uc6b4",def:"causing great surprise",unit:2,opts:["parent", "the antarctic", "amazing", "come out"]},
    {w:"the antarctic",m:"\ub0a8\uadf9",def:"the land near the South Pole",unit:2,opts:["keep warm", "parent", "chick", "the antarctic"]},
    {w:"parent",m:"\uc544\ubc84\uc9c0 \ub610\ub294 \uc5b4\uba38\ub2c8",def:"a mother or a father",unit:2,opts:["amazing", "come out", "keep warm", "parent"]},
    {w:"keep warm",m:"\ub530\ub73b\uc774 \uac04\uc9c1\ud558\ub2e4",def:"to not lose heat",unit:2,opts:["keep warm", "stay", "amazing", "the antarctic"]},
    {w:"stay",m:"\uba38\ubb34\ub974\ub2e4",def:"to continue to be in the same place",unit:2,opts:["stay", "keep warm", "come out", "leave"]},
    {w:"chick",m:"\uc0c8\ub07c \uc0c8",def:"a baby bird",unit:2,opts:["parent", "leave", "chick", "come out"]},
    {w:"come out",m:"\ub098\uc624\ub2e4",def:"to appear in the open",unit:2,opts:["parent", "chick", "keep warm", "come out"]},
    {w:"leave",m:"\ub5a0\ub098\ub2e4",def:"to go away from",unit:2,opts:["leave", "chick", "keep warm", "stay"]},
  ],
  "wwp1_3": [
    {w:"cool",m:"\uba4b\uc9c4",def:"very interesting or attractive",unit:3,opts:["funny", "cool", "stupid", "beautiful"]},
    {w:"together",m:"\ud568\uaed8",def:"with each other",unit:3,opts:["stupid", "beautiful", "funny", "together"]},
    {w:"clever",m:"\ub611\ub611\ud55c",def:"intelligent; smart",unit:3,opts:["funny", "beautiful", "stupid", "clever"]},
    {w:"funny",m:"\uc6c3\uae30\ub294",def:"causing laughter",unit:3,opts:["funny", "stupid", "clever", "birthday"]},
    {w:"birthday",m:"\uc0dd\uc77c",def:"the day of the year when someone was born",unit:3,opts:["stupid", "cool", "birthday", "clever"]},
    {w:"blond",m:"(\ubaa8\ubc1c\uc774) \uae08\ubc1c\uc778",def:"(of hair) yellow or golden colored",unit:3,opts:["blond", "birthday", "together", "stupid"]},
    {w:"beautiful",m:"\uc544\ub984\ub2e4\uc6b4",def:"having beauty",unit:3,opts:["blond", "cool", "beautiful", "clever"]},
    {w:"stupid",m:"\uc5b4\ub9ac\uc11d\uc740",def:"showing a lack of good sense",unit:3,opts:["stupid", "together", "birthday", "funny"]},
  ],
  "wwp1_4": [
    {w:"thing",m:"\ubb3c\uac74",def:"an object",unit:4,opts:["thing", "typewriter", "video game", "scared"]},
    {w:"puzzle",m:"\ud37c\uc990",def:"a game made of many pieces that can be fit together",unit:4,opts:["video game", "piece", "puzzle", "touch"]},
    {w:"piece",m:"\uc870\uac01",def:"a part separated from a larger part",unit:4,opts:["piece", "thing", "touch", "strange"]},
    {w:"video game",m:"\ube44\ub514\uc624 \uac8c\uc784",def:"an electronic game played on a screen",unit:4,opts:["strange", "touch", "video game", "typewriter"]},
    {w:"typewriter",m:"\ud0c0\uc790\uae30",def:"a machine for typing letters",unit:4,opts:["scared", "puzzle", "touch", "typewriter"]},
    {w:"strange",m:"\ub0af\uc120",def:"unusual; surprising",unit:4,opts:["thing", "typewriter", "strange", "scared"]},
    {w:"touch",m:"\ub9cc\uc9c0\ub2e4",def:"to put your hand on something",unit:4,opts:["touch", "thing", "video game", "strange"]},
    {w:"scared",m:"\ubb34\uc11c\uc6cc\ud558\ub294",def:"nervous or frightened",unit:4,opts:["thing", "scared", "video game", "typewriter"]},
  ],
  "wwp1_5": [
    {w:"present",m:"\uc120\ubb3c",def:"a gift",unit:5,opts:["moving", "present", "globe", "surfboard"]},
    {w:"spider",m:"\uac70\ubbf8",def:"a small creature that has eight legs",unit:5,opts:["surfboard", "present", "globe", "spider"]},
    {w:"moving",m:"\uc6c0\uc9c1\uc774\ub294",def:"changing position or place",unit:5,opts:["country", "moving", "surfboard", "coding"]},
    {w:"globe",m:"\uc9c0\uad6c\ubcf8",def:"a round ball with a map of the world on it",unit:5,opts:["coding", "surfboard", "present", "globe"]},
    {w:"country",m:"\uad6d\uac00",def:"an area of land that has its own government",unit:5,opts:["exciting", "coding", "country", "spider"]},
    {w:"coding",m:"\ucf54\ub529",def:"the process of using a programming language to tell a computer what to do",unit:5,opts:["country", "present", "globe", "coding"]},
    {w:"exciting",m:"\ud765\ubbf8\uc9c4\uc9c4\ud55c",def:"causing a feeling of interest and happiness",unit:5,opts:["country", "globe", "coding", "exciting"]},
    {w:"surfboard",m:"\uc11c\ud551 \ubcf4\ub4dc",def:"a long, light, narrow board for surfing",unit:5,opts:["present", "surfboard", "spider", "country"]},
  ],
  "wwp1_6": [
    {w:"comic book",m:"\ub9cc\ud654\ucc45",def:"a magazine that tells stories using pictures",unit:6,opts:["lesson", "violin", "have fun", "comic book"]},
    {w:"drawing",m:"\uadf8\ub9bc",def:"a picture drawn with a pencil, pen, etc.",unit:6,opts:["boat", "have fun", "drawing", "comic book"]},
    {w:"favorite",m:"\ub9e4\uc6b0 \uc88b\uc544\ud558\ub294",def:"most liked",unit:6,opts:["favorite", "boat", "have fun", "drawing"]},
    {w:"violin",m:"\ubc14\uc774\uc62c\ub9b0",def:"a musical instrument with strings",unit:6,opts:["boat", "violin", "drawing", "lesson"]},
    {w:"lesson",m:"\uc218\uc5c5",def:"a part of a course of instruction",unit:6,opts:["puppet", "lesson", "favorite", "drawing"]},
    {w:"boat",m:"\ubc30",def:"a vehicle that travels on water",unit:6,opts:["drawing", "violin", "favorite", "boat"]},
    {w:"puppet",m:"\uc190\uac00\ub77d \uc778\ud615",def:"a doll that is moved by putting a hand inside it",unit:6,opts:["lesson", "puppet", "violin", "favorite"]},
    {w:"have fun",m:"\uc990\uae30\ub2e4",def:"to have an enjoyable or amusing time",unit:6,opts:["violin", "lesson", "drawing", "have fun"]},
  ],
  "wwp1_7": [
    {w:"prize",m:"\uc0c1",def:"something given to the winner of a contest",unit:7,opts:["the arctic", "prize", "fitness center", "ceremony"]},
    {w:"ceremony",m:"\uc758\uc2dd",def:"an important social or religious event",unit:7,opts:["exercise", "school subject", "problem", "ceremony"]},
    {w:"the arctic",m:"\ubd81\uadf9",def:"the land near the North Pole",unit:7,opts:["prize", "solution", "the arctic", "ceremony"]},
    {w:"school subject",m:"\uad50\uacfc",def:"an area of knowledge studied in school",unit:7,opts:["fitness center", "ceremony", "solution", "school subject"]},
    {w:"solution",m:"\ud574\uacb0\ucc45",def:"a way of solving a problem; answer",unit:7,opts:["solution", "problem", "ceremony", "exercise"]},
    {w:"problem",m:"\ubb38\uc81c",def:"something difficult to deal with",unit:7,opts:["fitness center", "problem", "the arctic", "prize"]},
    {w:"fitness center",m:"\ud5ec\uc2a4\uc7a5",def:"a place in a building that people can exercise",unit:7,opts:["prize", "ceremony", "solution", "fitness center"]},
    {w:"exercise",m:"\uc6b4\ub3d9\ud558\ub2e4",def:"to do sports in order to become healthy",unit:7,opts:["fitness center", "solution", "exercise", "the arctic"]},
  ],
  "wwp1_8": [
    {w:"cap",m:"(\uc55e\ubd80\ubd84\uc5d0 \ucc59\uc774 \ub2ec\ub9b0) \ubaa8\uc790",def:"a small, soft hat that often has a hard curved part",unit:8,opts:["language", "uniform", "cap", "spaghetti"]},
    {w:"hat",m:"\ubaa8\uc790",def:"a head covering, often with a brim",unit:8,opts:["musical instrument", "helmet", "hat", "language"]},
    {w:"helmet",m:"\ud5ec\uba67",def:"a strong, hard hat that protects the head",unit:8,opts:["spaghetti", "language", "helmet", "musical instrument"]},
    {w:"wear",m:"\uc785\uace0 \uc788\ub2e4",def:"to have something on your body",unit:8,opts:["cap", "musical instrument", "wear", "language"]},
    {w:"uniform",m:"\uad50\ubcf5",def:"a special set of clothes worn by all the members of a group",unit:8,opts:["helmet", "hat", "uniform", "cap"]},
    {w:"spaghetti",m:"\uc2a4\ud30c\uac8c\ud2f0",def:"pasta in the shape of long, thin strings",unit:8,opts:["cap", "uniform", "hat", "spaghetti"]},
    {w:"musical instrument",m:"\uc545\uae30",def:"something that you use for playing music",unit:8,opts:["language", "musical instrument", "uniform", "cap"]},
    {w:"language",m:"\uc5b8\uc5b4",def:"the system of words that people use to express thoughts",unit:8,opts:["cap", "musical instrument", "uniform", "language"]},
  ],
  "wwp1_9": [
    {w:"boarding school",m:"\uae30\uc219\ud559\uad50",def:"a school where students live and study",unit:9,opts:["take care of", "arts and crafts", "break", "boarding school"]},
    {w:"learn",m:"\ubc30\uc6b0\ub2e4",def:"to gain knowledge by studying",unit:9,opts:["vegetable", "learn", "shower", "take care of"]},
    {w:"vegetable",m:"\ucc44\uc18c",def:"a plant that is eaten as food",unit:9,opts:["take care of", "vegetable", "jewelry", "learn"]},
    {w:"take care of",m:"~\uc744 \ub3cc\ubcf4\ub2e4",def:"to look after something or someone",unit:9,opts:["take care of", "break", "shower", "learn"]},
    {w:"jewelry",m:"\uc7a5\uc2e0\uad6c",def:"decorative things such as rings and necklaces",unit:9,opts:["take care of", "boarding school", "jewelry", "arts and crafts"]},
    {w:"arts and crafts",m:"\uacf5\uc608",def:"the activity of making useful and beautiful things",unit:9,opts:["arts and crafts", "take care of", "break", "vegetable"]},
    {w:"shower",m:"\uc0e4\uc6cc\ub97c \ud558\ub2e4",def:"to wash your body in a shower",unit:9,opts:["shower", "break", "boarding school", "jewelry"]},
    {w:"break",m:"\uc26c\ub294 \uc2dc\uac04",def:"the time for students to take a rest",unit:9,opts:["arts and crafts", "jewelry", "take care of", "break"]},
  ],
  "wwp1_10": [
    {w:"hall",m:"\ubcf5\ub3c4",def:"a narrow passageway in a building",unit:10,opts:["wait", "hall", "festival", "kite"]},
    {w:"kite",m:"\uc5f0",def:"a toy that is flown in the air",unit:10,opts:["winner", "kite", "wait", "competition"]},
    {w:"colorful",m:"(\uc0c9\uc774) \ub2e4\ucc44\ub85c\uc6b4",def:"having a lot of different colors",unit:10,opts:["colorful", "kite", "winner", "festival"]},
    {w:"festival",m:"\ucd95\uc81c",def:"a special time when people celebrate something",unit:10,opts:["colorful", "winner", "wait", "festival"]},
    {w:"wait",m:"\uae30\ub2e4\ub9ac\ub2e4",def:"to stay in a place until something happens",unit:10,opts:["kite", "colorful", "competition", "wait"]},
    {w:"competition",m:"\ub300\ud68c",def:"a contest in which people compete with each other",unit:10,opts:["wait", "winner", "competition", "colorful"]},
    {w:"winner",m:"\uc6b0\uc2b9\uc790",def:"someone that wins a contest",unit:10,opts:["colorful", "wait", "congratulations", "winner"]},
    {w:"congratulations",m:"\ucd95\ud558(\uc778\uc0ac)",def:"a message congratulating someone",unit:10,opts:["colorful", "congratulations", "kite", "festival"]},
  ],
  "wwp1_11": [
    {w:"popular",m:"\uc778\uae30 \uc788\ub294",def:"liked by many people",unit:11,opts:["mirror", "amusement\npark", "roller coaster", "popular"]},
    {w:"amusement\npark",m:"\ub180\uc774\uacf5\uc6d0",def:"a place with many games and rides",unit:11,opts:["popular", "amusement\npark", "tourist", "huge"]},
    {w:"tourist",m:"\uad00\uad11\uac1d",def:"someone who travels to a place for pleasure",unit:11,opts:["tourist", "ride", "popular", "entrance"]},
    {w:"entrance",m:"\uc785\uad6c",def:"a door or gate",unit:11,opts:["ride", "tourist", "huge", "entrance"]},
    {w:"huge",m:"\uac70\ub300\ud55c",def:"very great in size",unit:11,opts:["amusement\npark", "tourist", "huge", "ride"]},
    {w:"ride",m:"\ub180\uc774\uae30\uad6c",def:"a large machine at an amusement park people ride for fun",unit:11,opts:["popular", "ride", "huge", "mirror"]},
    {w:"roller coaster",m:"\ub864\ub7ec\ucf54\uc2a4\ud130",def:"a fast ride that is like a small train at an amusement park",unit:11,opts:["roller coaster", "popular", "entrance", "ride"]},
    {w:"mirror",m:"\uac70\uc6b8",def:"a piece of glass that you can see yourself in",unit:11,opts:["roller coaster", "ride", "tourist", "mirror"]},
  ],
  "wwp1_12": [
    {w:"meal",m:"\uc2dd\uc0ac",def:"the food eaten at one time",unit:12,opts:["go bowling", "contest", "visit", "meal"]},
    {w:"bookstore",m:"\uc11c\uc810",def:"a store that sells books",unit:12,opts:["bookstore", "meal", "contest", "fantastic"]},
    {w:"help",m:"\ub3d5\ub2e4",def:"to assist someone",unit:12,opts:["help", "meal", "visit", "contest"]},
    {w:"go bowling",m:"\ubcfc\ub9c1\uc744 \uce58\ub7ec \uac00\ub2e4",def:"to go to play a bowling game",unit:12,opts:["bookstore", "meal", "go bowling", "water park"]},
    {w:"contest",m:"\ub300\ud68c",def:"an event in which people try to win",unit:12,opts:["water park", "visit", "contest", "help"]},
    {w:"fantastic",m:"\ud658\uc0c1\uc801\uc778",def:"extremely good",unit:12,opts:["water park", "meal", "help", "fantastic"]},
    {w:"water park",m:"\uc6cc\ud130\ud30c\ud06c",def:"a place where people have fun or swim in water",unit:12,opts:["help", "contest", "water park", "visit"]},
    {w:"visit",m:"\ubc29\ubb38\ud558\ub2e4",def:"to go and spend time in a place",unit:12,opts:["visit", "fantastic", "water park", "go bowling"]},
  ],
  "wwp2_1": [
    {w:"celebration",m:"\uae30\ub150 \ud589\uc0ac",def:"a party or a special event",unit:1,opts:["share", "bright", "celebration", "cover"]},
    {w:"stall",m:"\uac00\ud310\ub300",def:"a small shop with an open front",unit:1,opts:["celebration", "stall", "share", "cover"]},
    {w:"powder",m:"\uac00\ub8e8",def:"a soft, dry substance that looks like dust or sand",unit:1,opts:["powder", "throw", "stall", "share"]},
    {w:"bonfire",m:"\ubaa8\ub2e5\ubd88",def:"a large outdoor fire",unit:1,opts:["throw", "bonfire", "share", "celebration"]},
    {w:"throw",m:"\ub358\uc9c0\ub2e4",def:"to use your hand to send something through the air",unit:1,opts:["cover", "throw", "bright", "celebration"]},
    {w:"cover",m:"\ub36e\ub2e4",def:"to be all over the surface of something",unit:1,opts:["cover", "bright", "powder", "throw"]},
    {w:"bright",m:"\ubc1d\uc740",def:"having very light and strong colors",unit:1,opts:["stall", "cover", "bright", "powder"]},
    {w:"share",m:"\ub098\ub204\ub2e4",def:"to have something with other people",unit:1,opts:["bright", "share", "throw", "celebration"]},
  ],
  "wwp2_2": [
    {w:"carnival",m:"\ucd95\uc81c",def:"a public festival",unit:2,opts:["lucky", "parade", "carnival", "costume"]},
    {w:"parade",m:"\ud37c\ub808\uc774\ub4dc",def:"a group of people going in the same direction to celebrate an event",unit:2,opts:["parade", "lucky", "mascot", "sculpture"]},
    {w:"costume",m:"\uc758\uc0c1",def:"a set of clothes worn to look like someone else",unit:2,opts:["fireworks", "costume", "lucky", "preparation"]},
    {w:"fireworks",m:"\ubd88\uaf43\ub180\uc774",def:"a display of colored lights and noise in the sky",unit:2,opts:["carnival", "lucky", "costume", "fireworks"]},
    {w:"preparation",m:"\uc900\ube44",def:"things to make something ready",unit:2,opts:["preparation", "sculpture", "costume", "mascot"]},
    {w:"sculpture",m:"\uc870\uac01\ud488",def:"an artwork made by carving or shaping ice, clay, stone, etc.",unit:2,opts:["lucky", "costume", "parade", "sculpture"]},
    {w:"mascot",m:"\ub9c8\uc2a4\ucf54\ud2b8",def:"an animal or an object used as a symbol",unit:2,opts:["mascot", "costume", "preparation", "parade"]},
    {w:"lucky",m:"\uc6b4\uc774 \uc88b\uc740",def:"having good luck",unit:2,opts:["mascot", "lucky", "carnival", "fireworks"]},
  ],
  "wwp2_3": [
    {w:"tradition",m:"\uc804\ud1b5",def:"an old belief and custom",unit:3,opts:["tradition", "wish", "drop", "scoop"]},
    {w:"midnight",m:"\uc790\uc815",def:"twelve o\u2019clock at night",unit:3,opts:["suitcase", "tradition", "drop", "midnight"]},
    {w:"wish",m:"\uc18c\ub9dd",def:"a desire for something to happen",unit:3,opts:["suitcase", "scoop", "block", "wish"]},
    {w:"block",m:"(\ub3c4\uc2dc\uc758) \ube14\ub85d",def:"an area surrounded by four streets",unit:3,opts:["tradition", "scoop", "block", "drop"]},
    {w:"empty",m:"\ube44\uc5b4 \uc788\ub294",def:"containing nothing",unit:3,opts:["block", "wish", "empty", "midnight"]},
    {w:"suitcase",m:"\uc5ec\ud589 \uac00\ubc29",def:"a large case used for carrying clothes and other things",unit:3,opts:["tradition", "wish", "suitcase", "drop"]},
    {w:"drop",m:"\ub5a8\uc5b4\ub728\ub9ac\ub2e4",def:"to make something fall",unit:3,opts:["wish", "empty", "midnight", "drop"]},
    {w:"scoop",m:"\ud55c \uc21f\uac08",def:"an amount of food picked up by a scoop",unit:3,opts:["suitcase", "drop", "scoop", "tradition"]},
  ],
  "wwp2_4": [
    {w:"serve",m:"\uc81c\uacf5\ud558\ub2e4",def:"to give food or drink to someone",unit:4,opts:["order", "check", "serve", "waiter"]},
    {w:"order",m:"\uc8fc\ubb38\ud558\ub2e4",def:"to request food or drink",unit:4,opts:["check", "menu", "serve", "order"]},
    {w:"menu",m:"\uba54\ub274",def:"a list of food served at a restaurant",unit:4,opts:["check", "menu", "serve", "waiter"]},
    {w:"waiter",m:"\uc885\uc5c5\uc6d0",def:"a man who serves food or drink to someone",unit:4,opts:["menu", "waiter", "serve", "favorite"]},
    {w:"check",m:"\uacc4\uc0b0\uc11c",def:"a bill for the food at a restaurant",unit:4,opts:["plate", "check", "order", "serve"]},
    {w:"plate",m:"\uc811\uc2dc",def:"a flat dish that is used for eating",unit:4,opts:["favorite", "menu", "serve", "plate"]},
    {w:"favorite",m:"\uac00\uc7a5 \uc88b\uc544\ud558\ub294",def:"most liked",unit:4,opts:["favorite", "check", "fast food", "order"]},
    {w:"fast food",m:"\ud328\uc2a4\ud2b8\ud478\ub4dc",def:"food that is quickly made and served",unit:4,opts:["waiter", "serve", "menu", "fast food"]},
  ],
  "wwp2_5": [
    {w:"knife",m:"\uce7c",def:"a tool with a sharp blade for cutting food",unit:5,opts:["skill", "pick up", "knife", "noodle"]},
    {w:"chopsticks",m:"\uc813\uac00\ub77d",def:"two thin sticks that you use to eat food",unit:5,opts:["chopsticks", "horn", "shell", "pick up"]},
    {w:"shell",m:"\uaecd\ub370\uae30",def:"the hard outer covering of an animal",unit:5,opts:["skill", "shell", "noodle", "horn"]},
    {w:"horn",m:"\ubfd4",def:"a hard pointed part that grows on the head of some animals",unit:5,opts:["bowl", "knife", "horn", "noodle"]},
    {w:"pick up",m:"\ub4e4\uc5b4\uc62c\ub9ac\ub2e4",def:"to lift something up",unit:5,opts:["horn", "skill", "chopsticks", "pick up"]},
    {w:"noodle",m:"\uba74",def:"a thin, long strip made from flour",unit:5,opts:["knife", "noodle", "shell", "pick up"]},
    {w:"bowl",m:"(\uc6b0\ubb35\ud55c) \uadf8\ub987",def:"a deep, round dish",unit:5,opts:["horn", "skill", "shell", "bowl"]},
    {w:"skill",m:"\uae30\uc220",def:"an ability to do something well",unit:5,opts:["chopsticks", "pick up", "skill", "knife"]},
  ],
  "wwp2_6": [
    {w:"national",m:"\uad6d\uac00\uc758; \uc804 \uad6d\ubbfc\uc758",def:"related to a country",unit:6,opts:["tasty", "national", "filling", "dish"]},
    {w:"dish",m:"\uc694\ub9ac",def:"a type of food cooked in a particular way",unit:6,opts:["dumpling", "fresh", "dish", "filling"]},
    {w:"dumpling",m:"\ub9cc\ub450",def:"a piece of food that is wrapped in dough and cooked",unit:6,opts:["dumpling", "national", "stick", "tasty"]},
    {w:"filling",m:"(\uc694\ub9ac\uc758) \uc18c",def:"a food mixture that is used to fill something",unit:6,opts:["spicy", "filling", "fresh", "tasty"]},
    {w:"stick",m:"\ub9c9\ub300\uae30",def:"a thin piece of wood",unit:6,opts:["spicy", "stick", "fresh", "tasty"]},
    {w:"spicy",m:"\ub9e4\uc6b4",def:"having a strong taste from spices",unit:6,opts:["dish", "national", "spicy", "filling"]},
    {w:"tasty",m:"\ub9db\uc788\ub294",def:"having a good flavor",unit:6,opts:["dumpling", "stick", "tasty", "fresh"]},
    {w:"fresh",m:"\uc2e0\uc120\ud55c",def:"newly made; not old",unit:6,opts:["national", "fresh", "tasty", "dumpling"]},
  ],
  "wwp2_7": [
    {w:"during",m:"~\ub3d9\uc548",def:"throughout the entire time of an event, period, etc.",unit:7,opts:["finish line", "cross", "during", "racer"]},
    {w:"enter",m:"\ucc38\uac00\ud558\ub2e4",def:"to take part in a race, competition, etc.",unit:7,opts:["racer", "enter", "impossible", "simultaneously"]},
    {w:"mass",m:"\ub300\uaddc\ubaa8\uc758",def:"involving a large number of people",unit:7,opts:["mass", "finish line", "racer", "during"]},
    {w:"racer",m:"\uacbd\uc8fc \ucc38\uac00\uc790",def:"a person that races",unit:7,opts:["enter", "cross", "during", "racer"]},
    {w:"simultaneously",m:"\ub3d9\uc2dc\uc5d0",def:"happening at the same time",unit:7,opts:["mass", "simultaneously", "during", "impossible"]},
    {w:"impossible",m:"\ubd88\uac00\ub2a5\ud55c",def:"unable to be done or to happen",unit:7,opts:["racer", "simultaneously", "cross", "impossible"]},
    {w:"cross",m:"\uac74\ub108\ub2e4",def:"to go from one side to the other",unit:7,opts:["during", "simultaneously", "cross", "racer"]},
    {w:"finish line",m:"\uacb0\uc2b9\uc120",def:"a line that marks the end of a race",unit:7,opts:["impossible", "during", "enter", "finish line"]},
  ],
  "wwp2_8": [
    {w:"mind",m:"\uc815\uc2e0",def:"the part of a person that thinks and understands",unit:8,opts:["mind", "fight", "confident", "movement"]},
    {w:"movement",m:"\uc6c0\uc9c1\uc784",def:"an act of moving the body",unit:8,opts:["get ready", "train", "confident", "movement"]},
    {w:"fight",m:"\uaca8\ub8e8\ub2e4",def:"to participate in a match",unit:8,opts:["confident", "get ready", "give up", "fight"]},
    {w:"train",m:"\ud6c8\ub828\ud558\ub2e4",def:"to practice a sport regularly before a match",unit:8,opts:["train", "confident", "give up", "movement"]},
    {w:"get ready",m:"\uc900\ube44\ub97c \ud558\ub2e4",def:"to prepare for something",unit:8,opts:["confident", "mind", "get ready", "champion"]},
    {w:"champion",m:"\ucc54\ud53c\uc5b8",def:"someone that has won a contest",unit:8,opts:["get ready", "movement", "champion", "mind"]},
    {w:"give up",m:"\ud3ec\uae30\ud558\ub2e4",def:"to stop trying to do something",unit:8,opts:["mind", "train", "confident", "give up"]},
    {w:"confident",m:"\uc790\uc2e0\uac10 \uc788\ub294",def:"being certain of your abilities",unit:8,opts:["movement", "confident", "give up", "train"]},
  ],
  "wwp2_9": [
    {w:"junior",m:"\uc8fc\ub2c8\uc5b4\uc758",def:"younger in age",unit:9,opts:["competition", "skate", "difficult", "junior"]},
    {w:"moment",m:"\uc9c0\uae08",def:"the present time",unit:9,opts:["difficult", "moment", "skate", "practice"]},
    {w:"practice",m:"\uc5f0\uc2b5\ud558\ub2e4",def:"to do something repeatedly to improve your skill",unit:9,opts:["difficult", "practice", "competition", "skate"]},
    {w:"competition",m:"\ub300\ud68c",def:"an organized event that people try to win a prize",unit:9,opts:["difficult", "skate", "competition", "practice"]},
    {w:"coach",m:"\ucf54\uce58",def:"a person who teaches athletes",unit:9,opts:["competition", "junior", "good luck", "coach"]},
    {w:"difficult",m:"\uc5b4\ub824\uc6b4",def:"not easy",unit:9,opts:["difficult", "moment", "competition", "junior"]},
    {w:"skate",m:"\uc2a4\ucf00\uc774\ud2b8\ub97c \ud0c0\ub2e4",def:"to move on skates",unit:9,opts:["skate", "good luck", "junior", "competition"]},
    {w:"good luck",m:"\ud589\uc6b4\uc744 \ube4c\ub2e4",def:"used to say that you hope someone will succeed",unit:9,opts:["good luck", "competition", "difficult", "practice"]},
  ],
  "wwp2_10": [
    {w:"cottage",m:"\uc791\uc740 \uc9d1",def:"a small house in the country",unit:10,opts:["balcony", "basement", "cottage", "lie"]},
    {w:"earthquake",m:"\uc9c0\uc9c4",def:"a shaking of the Earth\u2019s surface",unit:10,opts:["earthquake", "ladder", "floor", "balcony"]},
    {w:"flood",m:"\ud64d\uc218",def:"a large amount of water covering dry land",unit:10,opts:["flood", "cottage", "ladder", "earthquake"]},
    {w:"floor",m:"\uce35",def:"a level in a building",unit:10,opts:["flood", "earthquake", "basement", "floor"]},
    {w:"ladder",m:"\uc0ac\ub2e4\ub9ac",def:"a device used for climbing",unit:10,opts:["balcony", "ladder", "basement", "earthquake"]},
    {w:"basement",m:"\uc9c0\ud558\uce35",def:"the part of a building that is below the ground",unit:10,opts:["ladder", "cottage", "flood", "basement"]},
    {w:"balcony",m:"\ubc1c\ucf54\ub2c8",def:"a platform that is connected to the side of a building",unit:10,opts:["cottage", "flood", "ladder", "balcony"]},
    {w:"lie",m:"\ub215\ub2e4",def:"to be in a flat position on a surface",unit:10,opts:["basement", "cottage", "lie", "floor"]},
  ],
  "wwp2_11": [
    {w:"routine",m:"\uc77c\uacfc",def:"a regular way of doing things in a particular order",unit:11,opts:["space shuttle", "routine", "take a bath", "machine"]},
    {w:"relax",m:"\ud734\uc2dd\uc744 \ucde8\ud558\ub2e4",def:"to rest",unit:11,opts:["space shuttle", "machine", "relax", "package"]},
    {w:"take a bath",m:"\ubaa9\uc695\ud558\ub2e4",def:"to wash the body usually by sitting in a bathtub",unit:11,opts:["fasten", "take a bath", "package", "routine"]},
    {w:"float",m:"\ub5a0\ub2e4\ub2c8\ub2e4",def:"to move slowly in the air",unit:11,opts:["space shuttle", "relax", "float", "take a bath"]},
    {w:"package",m:"(\ud3ec\uc7a5\uc6a9) \uc0c1\uc790",def:"a wrapper or container that holds something",unit:11,opts:["take a bath", "space shuttle", "machine", "package"]},
    {w:"space shuttle",m:"\uc6b0\uc8fc \uc655\ubcf5\uc120",def:"a vehicle that goes into space and back to Earth",unit:11,opts:["fasten", "space shuttle", "float", "relax"]},
    {w:"machine",m:"\uae30\uacc4",def:"a device that uses electronic power to work",unit:11,opts:["float", "routine", "machine", "space shuttle"]},
    {w:"fasten",m:"\uace0\uc815\uc2dc\ud0a4\ub2e4",def:"to attach something firmly to another surface",unit:11,opts:["package", "routine", "fasten", "float"]},
  ],
  "wwp2_12": [
    {w:"lively",m:"\ud65c\uae30 \ub118\uce58\ub294",def:"full of movement or activity",unit:12,opts:["downtown", "lively", "attraction", "fantastic"]},
    {w:"fantastic",m:"\ud658\uc0c1\uc801\uc778",def:"extremely good",unit:12,opts:["ride", "lively", "church", "fantastic"]},
    {w:"downtown",m:"\uc2dc\ub0b4",def:"the main or central part of a city or town",unit:12,opts:["downtown", "indoor", "lively", "church"]},
    {w:"church",m:"\uad50\ud68c",def:"a building that Christians use for religious services",unit:12,opts:["church", "ride", "lively", "indoor"]},
    {w:"finished",m:"\uc644\uc131\ub41c",def:"entirely done or completed",unit:12,opts:["finished", "indoor", "ride", "church"]},
    {w:"attraction",m:"\uba85\uc18c",def:"a place that people visit for pleasure and interest",unit:12,opts:["fantastic", "ride", "indoor", "attraction"]},
    {w:"ride",m:"\uc5ec\uc815",def:"a usually short journey in or on a vehicle",unit:12,opts:["lively", "ride", "finished", "indoor"]},
    {w:"indoor",m:"\uc2e4\ub0b4\uc758",def:"inside a building",unit:12,opts:["attraction", "church", "lively", "indoor"]},
  ],
  "wwp3_1": [
    {w:"village",m:"\ub9c8\uc744",def:"a small town in the country",unit:1,opts:["town hall", "village", "ordinary", "crime"]},
    {w:"ordinary",m:"\ud3c9\ubc94\ud55c",def:"not different; usual",unit:1,opts:["bank", "bridge", "ordinary", "canal"]},
    {w:"town hall",m:"\uc2dc\uccad",def:"a public building used for a town\u2019s local government",unit:1,opts:["town hall", "crime", "ordinary", "bank"]},
    {w:"bank",m:"\uc740\ud589",def:"a place where people can keep or borrow money",unit:1,opts:["bank", "ordinary", "town hall", "village"]},
    {w:"lock",m:"\uc790\ubb3c\uc1e0",def:"a device that keeps a door fastened",unit:1,opts:["crime", "ordinary", "canal", "lock"]},
    {w:"crime",m:"\ubc94\uc8c4",def:"activity that is against the law",unit:1,opts:["lock", "bank", "bridge", "crime"]},
    {w:"canal",m:"\uc6b4\ud558",def:"a long stretch of water made by people",unit:1,opts:["village", "bank", "canal", "ordinary"]},
    {w:"bridge",m:"\ub2e4\ub9ac",def:"a structure that allows people to cross a river",unit:1,opts:["canal", "bridge", "ordinary", "town hall"]},
  ],
  "wwp3_2": [
    {w:"inventor",m:"\ubc1c\uba85\uac00",def:"someone who designs and makes new things",unit:2,opts:["tie", "hot-air balloon", "inventor", "smoke"]},
    {w:"hot-air balloon",m:"\uc5f4\uae30\uad6c",def:"a large balloon filled with hot air, used for carrying people up into the sky",unit:2,opts:["smoke", "hot-air balloon", "basket", "flight"]},
    {w:"smoke",m:"\uc5f0\uae30",def:"the gray gas that is produced by burning something",unit:2,opts:["land", "smoke", "inventor", "hot-air balloon"]},
    {w:"silk",m:"\ube44\ub2e8",def:"a soft and shiny cloth",unit:2,opts:["silk", "basket", "smoke", "inventor"]},
    {w:"tie",m:"\ubb36\ub2e4",def:"to fasten with a string",unit:2,opts:["silk", "tie", "flight", "inventor"]},
    {w:"basket",m:"\ubc14\uad6c\ub2c8",def:"a container for carrying things",unit:2,opts:["land", "inventor", "tie", "basket"]},
    {w:"flight",m:"\ube44\ud589",def:"the act of flying",unit:2,opts:["flight", "land", "tie", "smoke"]},
    {w:"land",m:"\ucc29\ub959\ud558\ub2e4",def:"to move down to the ground",unit:2,opts:["flight", "land", "hot-air balloon", "inventor"]},
  ],
  "wwp3_3": [
    {w:"vacation",m:"\ud734\uac00",def:"a period of time spent traveling or resting",unit:3,opts:["cycling", "cheap", "vacation", "expensive"]},
    {w:"travel",m:"\uc5ec\ud589\ud558\ub2e4",def:"to go on a trip",unit:3,opts:["delicious", "travel", "cheap", "temple"]},
    {w:"cycling",m:"\uc790\uc804\uac70 \ud0c0\uae30",def:"the activity of riding a bicycle",unit:3,opts:["cycling", "travel", "temple", "vacation"]},
    {w:"temple",m:"\uc0ac\uc6d0",def:"a building for worship",unit:3,opts:["delicious", "expensive", "travel", "temple"]},
    {w:"delicious",m:"\uc544\uc8fc \ub9db\uc788\ub294",def:"very good to eat or drink",unit:3,opts:["cheap", "play", "delicious", "expensive"]},
    {w:"expensive",m:"\ube44\uc2fc",def:"costing a lot of money",unit:3,opts:["cheap", "play", "delicious", "expensive"]},
    {w:"cheap",m:"\uc2fc",def:"costing little money",unit:3,opts:["play", "cheap", "delicious", "temple"]},
    {w:"play",m:"\uc5f0\uadf9, \ud76c\uace1",def:"a story to be performed by actors on a stage",unit:3,opts:["cheap", "play", "delicious", "vacation"]},
  ],
  "wwp3_4": [
    {w:"film studio",m:"\uc601\ud654 \uc81c\uc791\uc18c",def:"a place where movies are made",unit:4,opts:["film studio", "director", "advertisement", "refugee"]},
    {w:"advertisement",m:"\uad11\uace0",def:"a short film to help sell a product",unit:4,opts:["stage", "set", "autograph", "advertisement"]},
    {w:"stage",m:"\ubb34\ub300",def:"a raised area in a theater where the actors perform",unit:4,opts:["makeup", "advertisement", "stage", "refugee"]},
    {w:"makeup",m:"\ubd84\uc7a5 \ub3c4\uad6c",def:"materials used to change the appearances of an actor",unit:4,opts:["film studio", "advertisement", "makeup", "autograph"]},
    {w:"director",m:"\uac10\ub3c5",def:"someone who tells the actors in a movie what to do",unit:4,opts:["advertisement", "makeup", "director", "autograph"]},
    {w:"refugee",m:"\ub09c\ubbfc",def:"someone who has been forced to leave their country because of a war",unit:4,opts:["stage", "set", "director", "refugee"]},
    {w:"set",m:"\ucd2c\uc601\uc7a5",def:"a place where a movie is filmed",unit:4,opts:["set", "director", "refugee", "autograph"]},
    {w:"autograph",m:"\uc0ac\uc778",def:"a famous person\u2019s signature",unit:4,opts:["autograph", "makeup", "refugee", "set"]},
  ],
  "wwp3_5": [
    {w:"animated",m:"\ub9cc\ud654 \uc601\ud654\ub85c \ub41c",def:"produced by the creation of a series of drawings, pictures, etc.",unit:5,opts:["award", "adventurous", "company", "animated"]},
    {w:"company",m:"\ud68c\uc0ac",def:"a business organization that makes money",unit:5,opts:["company", "artist", "animated", "adventurous"]},
    {w:"adventurous",m:"\ubaa8\ud5d8\uc2ec\uc774 \uac15\ud55c",def:"willing to take risks and find excitement",unit:5,opts:["award", "company", "character", "adventurous"]},
    {w:"character",m:"\ub4f1\uc7a5\uc778\ubb3c",def:"a person or an animal in a story, movie, etc.",unit:5,opts:["character", "adventurous", "animated", "cartoon"]},
    {w:"creative",m:"\ucc3d\uc758\uc801\uc778",def:"involving the use of imagination to make new ideas",unit:5,opts:["company", "cartoon", "creative", "adventurous"]},
    {w:"cartoon",m:"\ub9cc\ud654 \uc601\ud654",def:"an animated film or TV show",unit:5,opts:["character", "company", "cartoon", "animated"]},
    {w:"award",m:"\uc0c1",def:"a prize for being excellent",unit:5,opts:["award", "artist", "cartoon", "creative"]},
    {w:"artist",m:"\ud654\uac00, \uc608\uc220\uac00",def:"someone who creates art",unit:5,opts:["cartoon", "animated", "artist", "creative"]},
  ],
  "wwp3_6": [
    {w:"singer",m:"\uac00\uc218",def:"someone who sings for a living",unit:6,opts:["improve", "musical", "singer", "drama school"]},
    {w:"actor",m:"\ubc30\uc6b0",def:"someone who acts in a play, movie, etc.",unit:6,opts:["actor", "musical", "improve", "singer"]},
    {w:"drama school",m:"\uc5f0\uadf9 \ud559\uad50",def:"a school where students learn how to act",unit:6,opts:["drama school", "role", "nervous", "actor"]},
    {w:"audition",m:"\uc624\ub514\uc158",def:"a short performance to show one\u2019s talents",unit:6,opts:["audition", "musical", "actor", "role"]},
    {w:"nervous",m:"\uae34\uc7a5\ub418\ub294",def:"worried about something",unit:6,opts:["actor", "nervous", "audition", "improve"]},
    {w:"musical",m:"\ubba4\uc9c0\uceec",def:"a movie or play that tells a story with songs",unit:6,opts:["musical", "actor", "singer", "audition"]},
    {w:"improve",m:"\ud5a5\uc0c1\ud558\ub2e4",def:"to become better",unit:6,opts:["drama school", "role", "improve", "nervous"]},
    {w:"role",m:"\uc5ed\ud560",def:"the character played by an actor",unit:6,opts:["musical", "role", "drama school", "actor"]},
  ],
  "wwp3_7": [
    {w:"spend",m:"(\uc2dc\uac04\uc744) \ubcf4\ub0b4\ub2e4",def:"to use time for a particular purpose",unit:7,opts:["insect", "macaw", "spend", "species"]},
    {w:"insect",m:"\uace4\ucda9",def:"a small animal with six legs and three body parts",unit:7,opts:["coatimundi", "macaw", "insect", "binoculars"]},
    {w:"single",m:"\ub2e8 \ud558\ub098\uc758",def:"only one; not having another",unit:7,opts:["single", "south", "insect", "macaw"]},
    {w:"south",m:"\ub0a8\ucabd",def:"the direction that is the opposite of north",unit:7,opts:["coatimundi", "south", "species", "spend"]},
    {w:"species",m:"\uc885",def:"a group of animals or plants that are similar",unit:7,opts:["macaw", "species", "insect", "binoculars"]},
    {w:"macaw",m:"\ub9c8\ucf54\uc575\ubb34\uc0c8",def:"a large, long-tailed parrot",unit:7,opts:["insect", "macaw", "binoculars", "spend"]},
    {w:"binoculars",m:"\uc30d\uc548\uacbd",def:"a device with two lenses for viewing distant objects",unit:7,opts:["binoculars", "south", "species", "macaw"]},
    {w:"coatimundi",m:"\ucf54\uc544\ud2f0; \uae34\ucf54\ub108\uad6c\ub9ac",def:"a relative of the raccoon with a long nose",unit:7,opts:["coatimundi", "macaw", "spend", "single"]},
  ],
  "wwp3_8": [
    {w:"friendship",m:"\uc6b0\uc815",def:"a relationship between friends",unit:8,opts:["at first sight", "friendship", "cheetah", "unusual"]},
    {w:"cheetah",m:"\uce58\ud0c0",def:"a large wild cat that can run very fast",unit:8,opts:["friendship", "unusual", "cub", "cheetah"]},
    {w:"care for",m:"~\uc744 \ub3cc\ubcf4\ub2e4",def:"to look after someone or something",unit:8,opts:["unusual", "puppy", "friendship", "care for"]},
    {w:"puppy",m:"\uac15\uc544\uc9c0",def:"a young dog",unit:8,opts:["friendship", "puppy", "unusual", "relax"]},
    {w:"cub",m:"(\uacf0\u00b7\uc0ac\uc790\u00b7\uc5ec\uc6b0 \ub4f1\uc758) \uc0c8\ub07c",def:"the baby of a wild animal, such as a lion or a bear",unit:8,opts:["relax", "cheetah", "cub", "care for"]},
    {w:"at first sight",m:"\uccab\ub208\uc5d0",def:"when first seen",unit:8,opts:["cub", "unusual", "care for", "at first sight"]},
    {w:"unusual",m:"\ud2b9\ubcc4\ud55c, \ud2b9\uc774\ud55c",def:"not normal",unit:8,opts:["unusual", "care for", "cheetah", "cub"]},
    {w:"relax",m:"\uc548\uc2ec\ud558\ub2e4",def:"to become less tense",unit:8,opts:["cub", "at first sight", "relax", "puppy"]},
  ],
  "wwp3_9": [
    {w:"count",m:"(\uc218\ub97c) \uc138\ub2e4",def:"to say numbers in order",unit:9,opts:["count", "brilliant", "bark", "understand"]},
    {w:"shelter",m:"\ubcf4\ud638\uc18c",def:"a place that provides food and protection for animals",unit:9,opts:["command", "brilliant", "shelter", "understand"]},
    {w:"understand",m:"\uc774\ud574\ud558\ub2e4",def:"to know the meaning of what someone says",unit:9,opts:["understand", "shelter", "brilliant", "chase"]},
    {w:"trick",m:"\uc7ac\uc8fc, \ubb18\uae30",def:"a clever and skillful action to entertain people",unit:9,opts:["bark", "understand", "chase", "trick"]},
    {w:"bark",m:"\uc9d6\ub2e4",def:"to make a short loud sound",unit:9,opts:["shelter", "bark", "command", "trick"]},
    {w:"command",m:"\uba85\ub839",def:"an order given to a person or an animal",unit:9,opts:["bark", "trick", "understand", "command"]},
    {w:"brilliant",m:"\ub6f0\uc5b4\ub09c",def:"smart; intelligent",unit:9,opts:["chase", "shelter", "brilliant", "command"]},
    {w:"chase",m:"\ub4a4\ucad3\ub2e4",def:"to follow and try to catch someone or something",unit:9,opts:["chase", "command", "understand", "count"]},
  ],
  "wwp3_10": [
    {w:"look for",m:"\ucc3e\ub2e4",def:"to try to find",unit:10,opts:["forest", "look for", "near", "hidden"]},
    {w:"treasure",m:"\ubcf4\ubb3c",def:"something valuable that is hidden in a safe place",unit:10,opts:["hidden", "treasure", "look for", "app"]},
    {w:"app",m:"\uc751\uc6a9 \ud504\ub85c\uadf8\ub7a8",def:"a program designed to do a special job; application",unit:10,opts:["near", "app", "hidden", "object"]},
    {w:"gps",m:"\uc704\uc131 \uc704\uce58 \ud655\uc778 \uc2dc\uc2a4\ud15c",def:"a navigation system that shows an exact location",unit:10,opts:["gps", "near", "forest", "object"]},
    {w:"object",m:"\ubb3c\uccb4",def:"a thing that you can see and touch",unit:10,opts:["near", "gps", "forest", "object"]},
    {w:"near",m:"\uac00\uae4c\uc6b4",def:"close to someone or something",unit:10,opts:["look for", "near", "object", "forest"]},
    {w:"hidden",m:"\uc228\uaca8\uc9c4",def:"difficult to see or find",unit:10,opts:["near", "look for", "hidden", "treasure"]},
    {w:"forest",m:"\uc232",def:"a large area of land covered with trees",unit:10,opts:["forest", "object", "app", "gps"]},
  ],
  "wwp3_11": [
    {w:"heat",m:"\uc5f4",def:"warmth or the quality of being hot",unit:11,opts:["cut down", "heat", "measure", "survive"]},
    {w:"energy",m:"\uc5d0\ub108\uc9c0",def:"usable power that comes from heat, electricity, etc.",unit:11,opts:["heat", "energy", "destroy", "measure"]},
    {w:"measure",m:"\uce21\uc815\ud558\ub2e4",def:"to find the size, length, or degree of something",unit:11,opts:["survive", "measure", "energy", "heat"]},
    {w:"temperature",m:"\uc628\ub3c4",def:"a measurement of how hot or cold something is",unit:11,opts:["cut down", "heat", "rain forest", "temperature"]},
    {w:"survive",m:"\uc0b4\uc544\ub0a8\ub2e4",def:"to continue to live",unit:11,opts:["rain forest", "survive", "heat", "measure"]},
    {w:"cut down",m:"\ubca0\uc5b4 \uc4f0\ub7ec\ub728\ub9ac\ub2e4",def:"to cut something to make it fall down",unit:11,opts:["heat", "rain forest", "survive", "cut down"]},
    {w:"destroy",m:"\ud30c\uad34\ud558\ub2e4",def:"to damage something badly",unit:11,opts:["temperature", "energy", "rain forest", "destroy"]},
    {w:"rain forest",m:"\uc5f4\ub300 \uc6b0\ub9bc",def:"a tropical forest with tall trees and lots of rain",unit:11,opts:["temperature", "measure", "rain forest", "cut down"]},
  ],
  "wwp3_12": [
    {w:"hobby",m:"\ucde8\ubbf8",def:"an activity that someone does for pleasure",unit:12,opts:["ground", "follow", "lift", "hobby"]},
    {w:"tornado",m:"\ud1a0\ub124\uc774\ub3c4",def:"a violent storm in which winds spin around",unit:12,opts:["ground", "lift", "hobby", "tornado"]},
    {w:"rotate",m:"\ud68c\uc804\ud558\ub2e4",def:"to turn around a central point",unit:12,opts:["follow", "reach", "hobby", "rotate"]},
    {w:"reach",m:"\ub2ff\ub2e4",def:"to grow or increase to a certain point",unit:12,opts:["hobby", "reach", "ground", "careful"]},
    {w:"ground",m:"\ub545",def:"an area of land",unit:12,opts:["hobby", "ground", "follow", "tornado"]},
    {w:"lift",m:"\ub4e4\uc5b4 \uc62c\ub9ac\ub2e4",def:"to move something or someone to a higher position",unit:12,opts:["lift", "tornado", "ground", "careful"]},
    {w:"follow",m:"\ub530\ub77c\uac00\ub2e4",def:"to go after something or someone",unit:12,opts:["tornado", "hobby", "follow", "careful"]},
    {w:"careful",m:"\uc870\uc2ec\ud558\ub294",def:"trying to avoid anything bad",unit:12,opts:["careful", "follow", "ground", "reach"]},
  ],
};

