// 1000 Basic English Words word bank.
export const BEW_WORDS_DB = {
  "bew2_1": [
    {w:"angry",m:"\ud654\ub09c",def:"feeling upset",unit:1,opts:["angry", "photograph (photo)", "group", "wonder"]},
    {w:"boring",m:"\uc9c0\ub8e8\ud55c",def:"not interesting",unit:1,opts:["math", "feel", "group", "boring"]},
    {w:"class",m:"\uc218\uc5c5",def:"a lesson at school",unit:1,opts:["angry", "class", "invite", "photograph (photo)"]},
    {w:"dream",m:"\uafc8\uafb8\ub2e4",def:"to think about a wish for something good",unit:1,opts:["famous", "boring", "hobby", "dream"]},
    {w:"famous",m:"\uc720\uba85\ud55c",def:"known by many people",unit:1,opts:["photograph (photo)", "boring", "class", "famous"]},
    {w:"feel",m:"\ub290\ub07c\ub2e4",def:"to have a sense of something",unit:1,opts:["dream", "feel", "hobby", "math"]},
    {w:"future",m:"\ubbf8\ub798",def:"the time that has not happened yet",unit:1,opts:["president", "famous", "group", "future"]},
    {w:"group",m:"\uadf8\ub8f9",def:"several people that are together",unit:1,opts:["class", "hundred", "boring", "group"]},
    {w:"hobby",m:"\ucde8\ubbf8",def:"something you like to do in your free time",unit:1,opts:["boring", "invite", "voice", "hobby"]},
    {w:"job",m:"\uc9c1\uc5c5",def:"the work that a person is paid to do",unit:1,opts:["future", "job", "travel", "president"]},
    {w:"hundred",m:"\uc22b\uc790 100",def:"the number 100",unit:1,opts:["hundred", "group", "wonder", "dream"]},
    {w:"invite",m:"\ucd08\ub300\ud558\ub2e4",def:"to ask to go somewhere",unit:1,opts:["famous", "speech", "wonder", "invite"]},
    {w:"math",m:"\uc218\ud559",def:"the study of numbers",unit:1,opts:["group", "voice", "math", "photograph (photo)"]},
    {w:"photograph (photo)",m:"\uc0ac\uc9c4",def:"a picture taken with a camera",unit:1,opts:["invite", "photograph (photo)", "job", "math"]},
    {w:"president",m:"\ub300\ud1b5\ub839",def:"the leader of the government or of a company",unit:1,opts:["dream", "really", "hobby", "president"]},
    {w:"really",m:"\uc815\ub9d0",def:"very",unit:1,opts:["travel", "feel", "speech", "really"]},
    {w:"speech",m:"\uc5f0\uc124",def:"a talk that someone gives in front of a group of people",unit:1,opts:["hundred", "dream", "future", "speech"]},
    {w:"travel",m:"\uc5ec\ud589\ud558\ub2e4",def:"to go on a trip, usually far away",unit:1,opts:["travel", "angry", "invite", "hundred"]},
    {w:"voice",m:"\ubaa9\uc18c\ub9ac",def:"the sound a person makes when speaking or singing",unit:1,opts:["math", "voice", "famous", "feel"]},
    {w:"wonder",m:"\uad81\uae08\ud574\ud558\ub2e4",def:"to have interest in knowing or learning something",unit:1,opts:["wonder", "president", "dream", "future"]},
  ],
  "bew2_2": [
    {w:"baseball",m:"\uc57c\uad6c",def:"a game in which players hit a ball with a bat",unit:2,opts:["tie", "earth", "baseball", "hold"]},
    {w:"basketball",m:"\ub18d\uad6c",def:"a game in which players throw a ball through a net",unit:2,opts:["hit", "hill", "basketball", "hospital"]},
    {w:"dangerous",m:"\uc704\ud5d8\ud55c",def:"involving danger or harm",unit:2,opts:["drop", "slow", "dangerous", "take"]},
    {w:"excited",m:"\uc2e0\uc774 \ub09c",def:"feeling happy about something",unit:2,opts:["hurt", "earth", "motorbike", "excited"]},
    {w:"hill",m:"\uc5b8\ub355",def:"land that is higher than the area around it",unit:2,opts:["hill", "dangerous", "take", "round"]},
    {w:"hit",m:"\uce58\ub2e4",def:"to make contact with something quickly",unit:2,opts:["excited", "hit", "hill", "dangerous"]},
    {w:"hospital",m:"\ubcd1\uc6d0",def:"the place people go when they are sick",unit:2,opts:["flag", "slow", "drop", "hospital"]},
    {w:"hurt",m:"\ub2e4\uce58\ub2e4",def:"to harm, wound, or damage",unit:2,opts:["take", "tie", "hurt", "dangerous"]},
    {w:"motorbike",m:"\uc624\ud1a0\ubc14\uc774",def:"a bike that runs on a motor; a motorcycle",unit:2,opts:["motorbike", "hospital", "hill", "take"]},
    {w:"slow",m:"\ub290\ub9b0",def:"not fast",unit:2,opts:["foolish", "excited", "hold", "slow"]},
    {w:"drop",m:"\ub5a8\uc5b4\ub728\ub9ac\ub2e4",def:"to fall or let fall",unit:2,opts:["flag", "drop", "hit", "basketball"]},
    {w:"earth",m:"\ub545",def:"the ground; dirt",unit:2,opts:["flag", "earth", "excited", "drop"]},
    {w:"flag",m:"\uae43\ubc1c",def:"a shape, often with four sides, used as a symbol",unit:2,opts:["flag", "basketball", "earth", "baseball"]},
    {w:"foolish",m:"\uc5b4\ub9ac\uc11d\uc740",def:"lacking wisdom; stupid",unit:2,opts:["hill", "tie", "baseball", "foolish"]},
    {w:"hold",m:"\uc7a1\ub2e4",def:"to use hands to carry something",unit:2,opts:["hold", "drop", "round", "foolish"]},
    {w:"matter",m:"\ubb38\uc81c\uac00 \ub418\ub2e4",def:"to be important",unit:2,opts:["hill", "weather", "matter", "baseball"]},
    {w:"round",m:"\ub465\uadfc",def:"in the shape of a circle or ball",unit:2,opts:["baseball", "excited", "round", "flag"]},
    {w:"take",m:"\ub370\ub9ac\uace0 \uac00\ub2e4",def:"to move a person or thing from one place to another",unit:2,opts:["tie", "take", "round", "hill"]},
    {w:"tie",m:"\ubb34\uc2b9\ubd80",def:"when two teams finish with the same number of points",unit:2,opts:["baseball", "tie", "matter", "slow"]},
    {w:"weather",m:"\ub0a0\uc528",def:"what the air is like at a certain time and place",unit:2,opts:["drop", "weather", "hit", "earth"]},
  ],
  "bew2_3": [
    {w:"art",m:"\ubbf8\uc220\ud488",def:"paintings, drawings, or sculptures",unit:3,opts:["art", "wall", "choose", "rock"]},
    {w:"build",m:"\uc9d3\ub2e4",def:"to make",unit:3,opts:["paint", "build", "wall", "back"]},
    {w:"choose",m:"\uace0\ub974\ub2e4",def:"to decide or make a choice",unit:3,opts:["rock", "choose", "wood", "plant"]},
    {w:"draw",m:"\uadf8\ub9ac\ub2e4",def:"to make a picture using a pen or pencil",unit:3,opts:["draw", "kid", "paint", "plant"]},
    {w:"kid",m:"\uc544\uc774",def:"a child",unit:3,opts:["kid", "build", "picnic", "choose"]},
    {w:"paint",m:"\uadf8\ub9bc \uadf8\ub9ac\ub2e4",def:"to make art with paint",unit:3,opts:["wall", "rock", "kid", "paint"]},
    {w:"picture",m:"\uc0ac\uc9c4, \uadf8\ub9bc",def:"a photograph or other image of a person or thing",unit:3,opts:["art", "back", "picture", "draw"]},
    {w:"plant",m:"\uc2dd\ubb3c",def:"a living thing that grows in the earth",unit:3,opts:["plant", "land", "fix", "pants"]},
    {w:"repeat",m:"\ubc18\ubcf5\ud558\ub2e4",def:"to say again",unit:3,opts:["repeat", "wood", "fix", "school"]},
    {w:"wall",m:"\ubcbd",def:"one of the sides of a room",unit:3,opts:["wall", "back", "picnic", "repeat"]},
    {w:"absent",m:"\uacb0\uc11d\ud55c",def:"not in a place",unit:3,opts:["fix", "paint", "absent", "wood"]},
    {w:"back",m:"\ub4a4\ucabd",def:"the area farthest from the front",unit:3,opts:["picture", "picnic", "rock", "back"]},
    {w:"fix",m:"\uace0\uce58\ub2e4",def:"to repair",unit:3,opts:["fix", "draw", "rock", "kid"]},
    {w:"land",m:"\ub545",def:"earth; ground",unit:3,opts:["draw", "pants", "kid", "land"]},
    {w:"pants",m:"\ubc14\uc9c0",def:"clothes worn on the legs",unit:3,opts:["repeat", "pants", "fix", "land"]},
    {w:"picnic",m:"\uc18c\ud48d",def:"a meal eaten outside on the ground",unit:3,opts:["picture", "picnic", "rock", "absent"]},
    {w:"river",m:"\uac15",def:"a large flow of water moving across land",unit:3,opts:["school", "picture", "river", "plant"]},
    {w:"rock",m:"\ubc14\uc704",def:"a big stone",unit:3,opts:["rock", "fix", "draw", "pants"]},
    {w:"school",m:"\ud559\uad50",def:"a place to go to learn",unit:3,opts:["build", "picture", "choose", "school"]},
    {w:"wood",m:"\ub098\ubb34",def:"material from trees",unit:3,opts:["repeat", "absent", "wood", "kid"]},
  ],
  "bew2_4": [
    {w:"book",m:"\ucc45",def:"sheets of paper held together",unit:4,opts:["noise", "book", "mean", "guess"]},
    {w:"example",m:"\uc608",def:"a sample",unit:4,opts:["noise", "glue", "sound", "example"]},
    {w:"glue",m:"\ud480",def:"something sticky used to make things stay together",unit:4,opts:["mean", "glue", "book", "noise"]},
    {w:"library",m:"\ub3c4\uc11c\uad00",def:"a place where books are kept",unit:4,opts:["example", "difference", "library", "excellent"]},
    {w:"mean",m:"\uc2ec\uc220\uad82\uc740",def:"unkind",unit:4,opts:["mean", "noise", "library", "glue"]},
    {w:"piece",m:"\uc870\uac01",def:"a small part of something larger",unit:4,opts:["piece", "book", "museum", "mean"]},
    {w:"plan",m:"\uacc4\ud68d",def:"a way of doing or making something",unit:4,opts:["tomorrow", "plan", "read", "difficult"]},
    {w:"quiet",m:"\uc870\uc6a9\ud55c",def:"silent; making little sound",unit:4,opts:["piece", "read", "correct", "quiet"]},
    {w:"read",m:"\uc77d\ub2e4",def:"to understand written words",unit:4,opts:["difference", "example", "book", "read"]},
    {w:"sound",m:"\uc18c\ub9ac",def:"something you can hear",unit:4,opts:["sound", "difficult", "tomorrow", "excellent"]},
    {w:"correct",m:"\uc815\ud655\ud55c",def:"right",unit:4,opts:["library", "sound", "correct", "difference"]},
    {w:"difference",m:"\ucc28\uc774",def:"how two things are unlike each other",unit:4,opts:["museum", "difference", "example", "tomorrow"]},
    {w:"difficult",m:"\uc5b4\ub824\uc6b4",def:"not easy",unit:4,opts:["mean", "example", "museum", "difficult"]},
    {w:"excellent",m:"\ud6cc\ub96d\ud55c",def:"very good",unit:4,opts:["excellent", "plan", "difficult", "noise"]},
    {w:"guess",m:"\ucd94\uce21\ud558\ub2e4",def:"to answer when you do not know if it is true",unit:4,opts:["piece", "guess", "museum", "read"]},
    {w:"museum",m:"\ubc15\ubb3c\uad00",def:"a place where items of art, science, or history are kept",unit:4,opts:["library", "noise", "museum", "difficult"]},
    {w:"noise",m:"\uc18c\uc74c",def:"something you can hear, usually loud or unpleasant",unit:4,opts:["mean", "noise", "quiet", "guess"]},
    {w:"relax",m:"\ud734\uc2dd\uc744 \ucde8\ud558\ub2e4",def:"to rest",unit:4,opts:["excellent", "relax", "guess", "example"]},
    {w:"science",m:"\uacfc\ud559",def:"the study of things in the world",unit:4,opts:["tomorrow", "science", "difficult", "book"]},
    {w:"tomorrow",m:"\ub0b4\uc77c",def:"on the day after today",unit:4,opts:["excellent", "mean", "tomorrow", "plan"]},
  ],
  "bew2_5": [
    {w:"close",m:"\uac00\uae4c\uc6b4",def:"near",unit:5,opts:["windy", "deep", "close", "glove"]},
    {w:"grass",m:"\uc794\ub514",def:"a plant that covers the ground",unit:5,opts:["grass", "close", "windy", "soap"]},
    {w:"hat",m:"\ubaa8\uc790",def:"something worn on the head",unit:5,opts:["hat", "toilet", "mountain", "wet"]},
    {w:"lake",m:"\ud638\uc218",def:"a large area of water with land around it",unit:5,opts:["close", "windy", "lake", "smell"]},
    {w:"moon",m:"\ub2ec",def:"the round, white object in the sky at night",unit:5,opts:["house", "smell", "moon", "farm"]},
    {w:"mountain",m:"\uc0b0",def:"a part of land that is higher than a hill",unit:5,opts:["mountain", "deep", "boot", "hat"]},
    {w:"smell",m:"\ub0c4\uc0c8 \ub9e1\ub2e4",def:"to be able to sense an odor with your nose",unit:5,opts:["grass", "wet", "smell", "wide"]},
    {w:"soap",m:"\ube44\ub204",def:"something used with water to clean",unit:5,opts:["soap", "well", "glove", "windy"]},
    {w:"toilet",m:"\ubcc0\uae30",def:"a seat in a bathroom",unit:5,opts:["wide", "lake", "toilet", "mountain"]},
    {w:"wet",m:"\uc816\uc740",def:"covered with water",unit:5,opts:["top", "hat", "wet", "soap"]},
    {w:"boot",m:"\ubd80\uce20",def:"a type of shoe",unit:5,opts:["lake", "boot", "top", "moon"]},
    {w:"deep",m:"\uae4a\uc740",def:"going far below",unit:5,opts:["smell", "deep", "lake", "well"]},
    {w:"farm",m:"\ub18d\uc7a5",def:"land used for growing plants or raising animals for food",unit:5,opts:["lake", "sunny", "farm", "house"]},
    {w:"glove",m:"\uc7a5\uac11",def:"clothing worn on the hands",unit:5,opts:["well", "toilet", "deep", "glove"]},
    {w:"house",m:"\uc9d1",def:"a building where people live",unit:5,opts:["house", "hat", "smell", "windy"]},
    {w:"sunny",m:"\ud654\ucc3d\ud55c",def:"having lots of sun",unit:5,opts:["mountain", "sunny", "boot", "toilet"]},
    {w:"top",m:"\uaf2d\ub300\uae30",def:"the highest point",unit:5,opts:["top", "mountain", "deep", "lake"]},
    {w:"well",m:"\uc6b0\ubb3c",def:"a deep hole with water for drinking",unit:5,opts:["well", "windy", "boot", "hat"]},
    {w:"wide",m:"\ub113\uc740",def:"having a large distance from one side to the other",unit:5,opts:["wide", "toilet", "grass", "house"]},
    {w:"windy",m:"\ubc14\ub78c\uc774 \ubd80\ub294",def:"having a lot of wind",unit:5,opts:["wide", "glove", "windy", "close"]},
  ],
  "bew2_6": [
    {w:"care",m:"\ubcf4\uc0b4\ud53c\ub2e4",def:"to look after",unit:6,opts:["girl", "window", "hungry", "care"]},
    {w:"die",m:"\uc8fd\ub2e4",def:"to stop living",unit:6,opts:["die", "zoo", "window", "feed"]},
    {w:"empty",m:"\ube44\uc5b4 \uc788\ub294",def:"having nothing inside",unit:6,opts:["empty", "hungry", "spoon", "dirty"]},
    {w:"feed",m:"\uba39\uc774\ub97c \uc8fc\ub2e4",def:"to give someone or something food",unit:6,opts:["care", "zoo", "feed", "frog"]},
    {w:"health",m:"\uac74\uac15",def:"the good condition of the body",unit:6,opts:["health", "die", "glass", "fill"]},
    {w:"heart",m:"\uc2ec\uc7a5",def:"the body part that moves blood through the body",unit:6,opts:["fresh", "heart", "die", "care"]},
    {w:"large",m:"\ud070",def:"big in size or amount",unit:6,opts:["remember", "large", "feed", "fresh"]},
    {w:"remember",m:"\uae30\uc5b5\ud558\ub2e4",def:"to have or keep something in mind",unit:6,opts:["remember", "health", "dirty", "glass"]},
    {w:"rule",m:"\uaddc\uce59",def:"something that says what you can or cannot do",unit:6,opts:["window", "die", "rule", "empty"]},
    {w:"zoo",m:"\ub3d9\ubb3c\uc6d0",def:"a place with wild animals for people to look at",unit:6,opts:["glass", "rule", "zoo", "feed"]},
    {w:"dirty",m:"\ub354\ub7ec\uc6b4",def:"not clean",unit:6,opts:["dirty", "large", "zoo", "care"]},
    {w:"fill",m:"\ucc44\uc6b0\ub2e4",def:"to make full of something",unit:6,opts:["spoon", "fresh", "fill", "heart"]},
    {w:"fresh",m:"\uc2e0\uc120\ud55c",def:"recently made or gotten",unit:6,opts:["spoon", "dirty", "fresh", "frog"]},
    {w:"frog",m:"\uac1c\uad6c\ub9ac",def:"a small green animal that lives near water",unit:6,opts:["large", "frog", "thirsty", "health"]},
    {w:"girl",m:"\uc18c\ub140",def:"a kid who is not a boy",unit:6,opts:["fill", "girl", "hungry", "remember"]},
    {w:"glass",m:"\uc720\ub9ac\ucef5",def:"a container used for drinks",unit:6,opts:["rule", "zoo", "glass", "thirsty"]},
    {w:"hungry",m:"\ubc30\uace0\ud508",def:"needing food",unit:6,opts:["care", "large", "hungry", "feed"]},
    {w:"spoon",m:"\uc21f\uac00\ub77d",def:"a tool used for eating",unit:6,opts:["spoon", "large", "fresh", "empty"]},
    {w:"thirsty",m:"\ubaa9\ub9c8\ub978",def:"needing to drink",unit:6,opts:["dirty", "thirsty", "girl", "care"]},
    {w:"window",m:"\ucc3d\ubb38",def:"an opening in a building which lets in light",unit:6,opts:["health", "feed", "window", "fill"]},
  ],
  "bew2_7": [
    {w:"ago",m:"\uc804\uc5d0",def:"before now",unit:7,opts:["trip", "ago", "past", "holiday"]},
    {w:"agree",m:"\ub3d9\uc758\ud558\ub2e4",def:"to think the same thing",unit:7,opts:["lamp", "last", "ball", "agree"]},
    {w:"beach",m:"\ud574\ubcc0",def:"an area next to water that is covered with sand",unit:7,opts:["west", "ship", "beach", "agree"]},
    {w:"cap",m:"\ubaa8\uc790",def:"a hat",unit:7,opts:["lamp", "ship", "cap", "past"]},
    {w:"fat",m:"\ub6b1\ub6b1\ud55c",def:"overweight; not thin",unit:7,opts:["fat", "vacation", "sea", "towel"]},
    {w:"sea",m:"\ubc14\ub2e4",def:"a very large body of water",unit:7,opts:["boat", "sea", "agree", "last"]},
    {w:"throw",m:"\ub358\uc9c0\ub2e4",def:"to push something out of your hands",unit:7,opts:["boat", "fat", "throw", "holiday"]},
    {w:"towel",m:"\uc218\uac74",def:"something used for drying things",unit:7,opts:["towel", "last", "trip", "boat"]},
    {w:"trip",m:"\uc5ec\ud589",def:"a visit to a place",unit:7,opts:["spend", "fat", "vacation", "trip"]},
    {w:"vacation",m:"\ud734\uac00",def:"time away from school or work, usually to travel or relax",unit:7,opts:["agree", "cap", "west", "vacation"]},
    {w:"ball",m:"\uacf5",def:"a round object that you play with",unit:7,opts:["spend", "towel", "ball", "sea"]},
    {w:"basket",m:"\ubc14\uad6c\ub2c8",def:"a container, usually made of wood",unit:7,opts:["holiday", "basket", "west", "ago"]},
    {w:"boat",m:"\ubc30",def:"something that people travel with on water",unit:7,opts:["boat", "fat", "sea", "ball"]},
    {w:"holiday",m:"\ud734\uc77c",def:"a special day",unit:7,opts:["ship", "cap", "holiday", "vacation"]},
    {w:"lamp",m:"\ub7a8\ud504",def:"something that makes light",unit:7,opts:["vacation", "past", "lamp", "ship"]},
    {w:"last",m:"\uacc4\uc18d \ub418\ub2e4",def:"to continue for a certain amount of time",unit:7,opts:["ago", "vacation", "last", "beach"]},
    {w:"past",m:"\uacfc\uac70",def:"the time before now",unit:7,opts:["cap", "basket", "ball", "past"]},
    {w:"ship",m:"\ubc30",def:"a large boat",unit:7,opts:["last", "ship", "boat", "vacation"]},
    {w:"spend",m:"\uc4f0\ub2e4",def:"to use money on something or use time to do something",unit:7,opts:["west", "cap", "vacation", "spend"]},
    {w:"west",m:"\uc11c\ucabd\uc73c\ub85c",def:"in the direction where the sun sets",unit:7,opts:["ago", "fat", "basket", "west"]},
  ],
  "bew2_8": [
    {w:"beef",m:"\uc1e0\uace0\uae30",def:"meat from a cow",unit:8,opts:["live", "month", "beef", "low"]},
    {w:"best",m:"\ucd5c\uace0\uc758",def:"better than the others",unit:8,opts:["best", "name", "size", "phone"]},
    {w:"bread",m:"\ube75",def:"a type of baked food",unit:8,opts:["bread", "store", "free", "dear"]},
    {w:"free",m:"\ubb34\ub8cc\uc758",def:"not needing money to buy",unit:8,opts:["pair", "pick", "free", "beef"]},
    {w:"hurry",m:"\uc11c\ub450\ub974\ub2e4",def:"to move quickly",unit:8,opts:["beef", "hurry", "rich", "store"]},
    {w:"join",m:"\ud568\uaed8 \ud558\ub2e4",def:"to come together",unit:8,opts:["rice", "hurry", "free", "join"]},
    {w:"middle",m:"\uc911\uac04",def:"a point in the center",unit:8,opts:["bag", "dear", "free", "middle"]},
    {w:"pair",m:"\ud55c \uc30d",def:"two things that match",unit:8,opts:["live", "beef", "store", "pair"]},
    {w:"pick",m:"\uace0\ub974\ub2e4",def:"to choose",unit:8,opts:["hurry", "name", "pick", "beef"]},
    {w:"store",m:"\uc0c1\uc810",def:"a shop",unit:8,opts:["size", "phone", "rich", "store"]},
    {w:"bag",m:"\uac00\ubc29",def:"something that people can put things in",unit:8,opts:["bag", "bread", "rich", "phone"]},
    {w:"dear",m:"\uc0ac\ub791\ud558\ub294",def:"a word used to begin a letter or diary",unit:8,opts:["size", "hurry", "month", "dear"]},
    {w:"live",m:"\uc0b4\ub2e4",def:"to have a home in a certain place; to be alive",unit:8,opts:["store", "pick", "live", "beef"]},
    {w:"low",m:"\ub0ae\uc740",def:"near to the ground",unit:8,opts:["bread", "dear", "join", "low"]},
    {w:"month",m:"\ud55c \ub2ec",def:"one of the twelve periods of time in a year",unit:8,opts:["rice", "size", "low", "month"]},
    {w:"name",m:"\uc774\ub984",def:"the word(s) by which a person or thing is known",unit:8,opts:["hurry", "bag", "live", "name"]},
    {w:"phone",m:"\uc804\ud654",def:"something used to talk to people who are far away",unit:8,opts:["phone", "live", "middle", "bread"]},
    {w:"rice",m:"\uc300",def:"a type of small white or brown grain",unit:8,opts:["pair", "best", "join", "rice"]},
    {w:"rich",m:"\ubd80\uc720\ud55c",def:"having a lot of money",unit:8,opts:["name", "pick", "bag", "rich"]},
    {w:"size",m:"\ud06c\uae30",def:"how big or small a person or thing is",unit:8,opts:["best", "phone", "join", "size"]},
  ],
  "bew2_9": [
    {w:"birth",m:"\ucd9c\uc0dd",def:"the moment a baby is born",unit:9,opts:["second", "clothes", "brush", "birth"]},
    {w:"clothes",m:"\uc637",def:"things people wear",unit:9,opts:["bath", "bright", "clothes", "lose"]},
    {w:"cost",m:"\ube44\uc6a9\uc774 \ub4e4\ub2e4",def:"to have an amount of money as a price",unit:9,opts:["weigh", "brush", "lose", "cost"]},
    {w:"hide",m:"\uc228\ub2e4",def:"to put something in a place where others cannot see it",unit:9,opts:["bright", "soft", "cost", "hide"]},
    {w:"pet",m:"\uc560\uc644\ub3d9\ubb3c",def:"an animal cared for by a person",unit:9,opts:["hide", "puppy", "pet", "second"]},
    {w:"puppy",m:"\uac15\uc544\uc9c0",def:"a very young dog",unit:9,opts:["age", "clothes", "puppy", "thank"]},
    {w:"soft",m:"\ud479\uc2e0\ud55c",def:"smooth and nice to touch",unit:9,opts:["soft", "thank", "touch", "clothes"]},
    {w:"touch",m:"\ub9cc\uc9c0\ub2e4",def:"to feel by putting fingers on something",unit:9,opts:["lose", "weigh", "touch", "brush"]},
    {w:"weigh",m:"\ubb34\uac8c\ub97c \uc7ac\ub2e4",def:"to find out how heavy a person or thing is",unit:9,opts:["weigh", "puppy", "ugly", "clothes"]},
    {w:"wish",m:"\uc18c\uc6d0",def:"a hope for something",unit:9,opts:["wish", "clothes", "weigh", "hide"]},
    {w:"age",m:"\ub098\uc774",def:"the amount of time being alive",unit:9,opts:["test", "soft", "ugly", "age"]},
    {w:"bath",m:"\ubaa9\uc695",def:"the act of cleaning the body",unit:9,opts:["thank", "brush", "bath", "test"]},
    {w:"bright",m:"\ub611\ub611\ud55c",def:"clever or smart",unit:9,opts:["hide", "weigh", "bright", "cost"]},
    {w:"brush",m:"\ube57\uc9c8\uc744 \ud558\ub2e4",def:"to clean or make smooth with a brush",unit:9,opts:["bath", "test", "ugly", "brush"]},
    {w:"lose",m:"\uc783\uc5b4\ubc84\ub9ac\ub2e4",def:"not to be able to find something; not to be the best in a game",unit:9,opts:["tell", "lose", "ugly", "hide"]},
    {w:"second",m:"\ucd08",def:"a very short period of time; 1/60 of a minute",unit:9,opts:["second", "wish", "tell", "test"]},
    {w:"tell",m:"\ub9d0\ud558\ub2e4",def:"to say or write something to someone",unit:9,opts:["second", "tell", "lose", "bright"]},
    {w:"test",m:"\uc2dc\ud5d8",def:"an exam",unit:9,opts:["test", "second", "birth", "brush"]},
    {w:"thank",m:"\uac10\uc0ac\ud558\ub2e4",def:"to tell someone you are grateful for something",unit:9,opts:["bath", "weigh", "thank", "test"]},
    {w:"ugly",m:"\ubabb\uc0dd\uae34",def:"not pretty",unit:9,opts:["second", "puppy", "ugly", "birth"]},
  ],
  "bew2_10": [
    {w:"calendar",m:"\ub2ec\ub825",def:"a table that shows the days, weeks, and months of a year",unit:10,opts:["luck", "paper", "calendar", "clear"]},
    {w:"dance",m:"\ucda4\ucd94\ub2e4",def:"to move the body along with music",unit:10,opts:["post", "luck", "dance", "clear"]},
    {w:"date",m:"\ub0a0\uc9dc",def:"a specific day of the month or year",unit:10,opts:["turn", "date", "idea", "floor"]},
    {w:"idea",m:"\uc0dd\uac01",def:"a thought or plan",unit:10,opts:["luck", "dance", "idea", "polite"]},
    {w:"luck",m:"\uc6b4",def:"good fortune",unit:10,opts:["luck", "toy", "idea", "favorite"]},
    {w:"paper",m:"\uc885\uc774",def:"something flat used to write on",unit:10,opts:["train", "polite", "clear", "paper"]},
    {w:"post",m:"\uac8c\uc2dc\ud558\ub2e4",def:"to put up a sign or other writing",unit:10,opts:["dance", "favorite", "post", "date"]},
    {w:"receive",m:"\ubc1b\ub2e4",def:"to get",unit:10,opts:["floor", "toy", "receive", "luck"]},
    {w:"toy",m:"\uc7a5\ub09c\uac10",def:"something a child plays with",unit:10,opts:["luck", "toy", "paper", "fan"]},
    {w:"week",m:"\uc8fc",def:"a period of time lasting seven days",unit:10,opts:["present", "week", "clear", "turn"]},
    {w:"clear",m:"\uce58\uc6b0\ub2e4",def:"to make clean by removing items",unit:10,opts:["calendar", "clear", "week", "dance"]},
    {w:"continue",m:"\uacc4\uc18d\ud558\ub2e4",def:"to keep doing something",unit:10,opts:["fan", "luck", "continue", "date"]},
    {w:"fan",m:"\ud32c",def:"someone interested in a famous thing or person",unit:10,opts:["floor", "fan", "luck", "post"]},
    {w:"favorite",m:"\uac00\uc7a5 \uc88b\uc544\ud558\ub294",def:"most liked",unit:10,opts:["floor", "favorite", "present", "post"]},
    {w:"floor",m:"\ubc14\ub2e5",def:"the part of the room people walk on",unit:10,opts:["train", "clear", "floor", "toy"]},
    {w:"polite",m:"\uc608\uc758 \ubc14\ub978",def:"nice to other people",unit:10,opts:["polite", "favorite", "post", "week"]},
    {w:"practice",m:"\uc5f0\uc2b5\ud558\ub2e4",def:"to repeat something in order to become better",unit:10,opts:["week", "continue", "luck", "practice"]},
    {w:"present",m:"\uc8fc\ub2e4",def:"to give something to a person in a formal way",unit:10,opts:["clear", "present", "luck", "polite"]},
    {w:"train",m:"\ud6c8\ub828\ud558\ub2e4",def:"to exercise in order to become better",unit:10,opts:["train", "dance", "date", "paper"]},
    {w:"turn",m:"\ucc28\ub840",def:"the chance for someone to do something",unit:10,opts:["calendar", "dance", "luck", "turn"]},
  ],
  "bew2_11": [
    {w:"balloon",m:"\ud48d\uc120",def:"a thin rubber bag that becomes larger when filled with air",unit:11,opts:["king", "wake", "busy", "balloon"]},
    {w:"bridge",m:"\ub2e4\ub9ac",def:"something built for crossing over water or land",unit:11,opts:["surprise", "fight", "restaurant", "bridge"]},
    {w:"busy",m:"\ubc14\uc05c",def:"having no free time",unit:11,opts:["handsome", "company", "busy", "wake"]},
    {w:"company",m:"\uc190\ub2d8",def:"guests",unit:11,opts:["company", "old", "husband", "fight"]},
    {w:"congratulate",m:"\ucd95\ud558\ud558\ub2e4",def:"to tell someone that you are happy for their good luck",unit:11,opts:["old", "fight", "congratulate", "handsome"]},
    {w:"delicious",m:"\ub9db\uc788\ub294",def:"very good to eat",unit:11,opts:["king", "delicious", "woman", "bridge"]},
    {w:"fight",m:"\uc2f8\uc6b0\ub2e4",def:"to battle or hurt with force",unit:11,opts:["handsome", "fight", "restaurant", "queen"]},
    {w:"old",m:"\uc624\ub798\ub41c",def:"having lived or been used for a long time",unit:11,opts:["gentleman", "congratulate", "old", "busy"]},
    {w:"restaurant",m:"\uc2dd\ub2f9",def:"a place where you can buy and eat food",unit:11,opts:["restaurant", "old", "surprise", "delicious"]},
    {w:"surprise",m:"\ub73b\ubc16\uc758 \uc77c",def:"something that you do not know about before it happens",unit:11,opts:["company", "gentleman", "surprise", "restaurant"]},
    {w:"gentleman",m:"\uc2e0\uc0ac",def:"a man who is polite",unit:11,opts:["wake", "balloon", "company", "gentleman"]},
    {w:"handsome",m:"\uc798\uc0dd\uae34",def:"good-looking, usually for men",unit:11,opts:["restaurant", "wake", "handsome", "surprise"]},
    {w:"husband",m:"\ub0a8\ud3b8",def:"a man someone is married to",unit:11,opts:["interested", "balloon", "old", "husband"]},
    {w:"interested",m:"\uad00\uc2ec \uc788\ub294",def:"wanting to look at something closely",unit:11,opts:["interested", "bridge", "woman", "wake"]},
    {w:"king",m:"\uc655",def:"a man who rules a country",unit:11,opts:["skirt", "king", "fight", "company"]},
    {w:"queen",m:"\uc5ec\uc655",def:"a woman who rules a country or who is a king\u2019s wife",unit:11,opts:["restaurant", "fight", "gentleman", "queen"]},
    {w:"skirt",m:"\uce58\ub9c8",def:"a piece of women\u2019s clothing which hangs from the waist",unit:11,opts:["delicious", "queen", "balloon", "skirt"]},
    {w:"wake",m:"\uc7a0\uc774 \uae68\ub2e4, \uc77c\uc5b4\ub098\ub2e4",def:"to stop sleeping",unit:11,opts:["wake", "old", "husband", "handsome"]},
    {w:"wife",m:"\uc544\ub0b4",def:"a woman someone is married to",unit:11,opts:["wife", "fight", "congratulate", "old"]},
    {w:"woman",m:"\uc5ec\uc790",def:"a girl when she grows up",unit:11,opts:["woman", "fight", "surprise", "busy"]},
  ],
  "bew2_12": [
    {w:"arrive",m:"\ub3c4\ucc29\ud558\ub2e4",def:"to get to a place",unit:12,opts:["subway", "arrive", "south", "office"]},
    {w:"car",m:"\uc790\ub3d9\ucc28",def:"something that people can drive or ride in",unit:12,opts:["umbrella", "arrive", "car", "plate"]},
    {w:"forget",m:"\uc78a\ub2e4",def:"not to remember something",unit:12,opts:["theater", "forget", "car", "arrive"]},
    {w:"gate",m:"\ubb38",def:"a door in a wall or fence",unit:12,opts:["gate", "umbrella", "tonight", "office"]},
    {w:"grand",m:"\uc6c5\uc7a5\ud55c",def:"large and impressive",unit:12,opts:["line", "office", "grand", "forget"]},
    {w:"line",m:"\uc904",def:"a long row of things or people",unit:12,opts:["line", "subway", "office", "square"]},
    {w:"subway",m:"\uc9c0\ud558\ucca0",def:"a system of trains that go under a city",unit:12,opts:["car", "south", "line", "subway"]},
    {w:"theater",m:"\uadf9\uc7a5",def:"a place to watch movies or plays",unit:12,opts:["subway", "win", "office", "theater"]},
    {w:"thousand",m:"\uc22b\uc790 1,000",def:"the number 1,000",unit:12,opts:["thousand", "plate", "cloudy", "grand"]},
    {w:"win",m:"\uc774\uae30\ub2e4",def:"to do better than other people in a game",unit:12,opts:["subway", "tonight", "win", "umbrella"]},
    {w:"cloudy",m:"\ud750\ub9b0",def:"not clear or easily seen through",unit:12,opts:["street", "win", "cloudy", "tonight"]},
    {w:"north",m:"\ubd81\ucabd\uc73c\ub85c",def:"in the direction pointing toward the top of a map",unit:12,opts:["north", "forget", "theater", "plate"]},
    {w:"office",m:"\uc0ac\ubb34\uc2e4",def:"a room where people work with desks and chairs",unit:12,opts:["office", "car", "street", "gate"]},
    {w:"plate",m:"\uc811\uc2dc",def:"a flat dish",unit:12,opts:["plate", "arrive", "forget", "subway"]},
    {w:"police",m:"\uacbd\ucc30",def:"a person or group of people who help keep others safe",unit:12,opts:["office", "street", "theater", "police"]},
    {w:"south",m:"\ub0a8\ucabd\uc73c\ub85c",def:"in the direction pointing toward the bottom of a map",unit:12,opts:["north", "theater", "south", "police"]},
    {w:"square",m:"\uad11\uc7a5",def:"an open area in a town or city where people get together",unit:12,opts:["square", "win", "office", "gate"]},
    {w:"street",m:"\uac70\ub9ac",def:"a road, usually with buildings on one or both sides",unit:12,opts:["theater", "street", "arrive", "cloudy"]},
    {w:"tonight",m:"\uc624\ub298 \ubc24",def:"the night of today",unit:12,opts:["office", "tonight", "police", "theater"]},
    {w:"umbrella",m:"\uc6b0\uc0b0",def:"a thing used to stop rain or the sun from getting on you",unit:12,opts:["north", "police", "forget", "umbrella"]},
  ],
  "bew3_1": [
    {w:"burn",m:"\ud0c0\ub2e4",def:"to be on fire",unit:1,opts:["knock", "shake", "smart", "burn"]},
    {w:"exchange",m:"\uad50\ud658\ud558\ub2e4",def:"to give something and get something at the same time",unit:1,opts:["bowl", "result", "exchange", "popular"]},
    {w:"introduce",m:"\uc18c\uac1c\ud558\ub2e4",def:"to make a person known to another person",unit:1,opts:["reason", "block", "shake", "introduce"]},
    {w:"offer",m:"\uc81c\uacf5\ud558\ub2e4",def:"to try to give or do something to help someone",unit:1,opts:["pardon", "prepare", "offer", "exchange"]},
    {w:"pardon",m:"\uc6a9\uc11c\ud558\ub2e4",def:"to forgive, often used with me",unit:1,opts:["borrow", "pardon", "bell", "shy"]},
    {w:"popular",m:"\uc778\uae30 \uc788\ub294",def:"liked by many people",unit:1,opts:["popular", "confuse", "knock", "burn"]},
    {w:"prepare",m:"\uc900\ube44\ud558\ub2e4",def:"to make",unit:1,opts:["offer", "burn", "smart", "prepare"]},
    {w:"reason",m:"\uc774\uc720",def:"something that says why something was or was not done",unit:1,opts:["subject", "bell", "reason", "seem"]},
    {w:"shake",m:"\ud754\ub4e4\ub2e4",def:"to hold and move up and down",unit:1,opts:["shake", "block", "confuse", "bowl"]},
    {w:"shy",m:"\uc218\uc90d\uc740",def:"quiet and not wanting to talk to others",unit:1,opts:["result", "offer", "smart", "shy"]},
    {w:"bell",m:"\uc885",def:"something that makes a ringing sound when hit",unit:1,opts:["bell", "introduce", "result", "shy"]},
    {w:"block",m:"\ube14\ub85d, \uad6c\uc5ed",def:"a part of a city with streets on all four sides",unit:1,opts:["exchange", "borrow", "confuse", "block"]},
    {w:"borrow",m:"\ube4c\ub9ac\ub2e4",def:"to take and use something belonging to another person",unit:1,opts:["popular", "subject", "confuse", "borrow"]},
    {w:"bowl",m:"\uadf8\ub987",def:"a dish with tall sides",unit:1,opts:["smart", "offer", "shy", "bowl"]},
    {w:"confuse",m:"\ud63c\ub780 \uc2dc\ud0a4\ub2e4",def:"to make it difficult for someone to understand",unit:1,opts:["shake", "shy", "smart", "confuse"]},
    {w:"knock",m:"\ub450\ub4dc\ub9ac\ub2e4",def:"to hit something with part of your hand",unit:1,opts:["knock", "block", "borrow", "introduce"]},
    {w:"result",m:"\uacb0\uacfc",def:"an exam grade; something that is caused by another",unit:1,opts:["block", "shy", "introduce", "result"]},
    {w:"seem",m:"~\uc778 \uac83 \uac19\ub2e4",def:"to look to be",unit:1,opts:["introduce", "seem", "bowl", "result"]},
    {w:"smart",m:"\ub611\ub611\ud55c",def:"good at learning or thinking about things",unit:1,opts:["knock", "block", "prepare", "smart"]},
    {w:"subject",m:"\uacfc\ubaa9",def:"something you study in school",unit:1,opts:["offer", "block", "shy", "subject"]},
  ],
  "bew3_2": [
    {w:"active",m:"\ud65c\ubc1c\ud55c",def:"doing many things",unit:2,opts:["enter", "active", "choice", "path"]},
    {w:"believe",m:"\ubbff\ub2e4",def:"to think that something is true",unit:2,opts:["lie", "believe", "environment", "area"]},
    {w:"environment",m:"\ud658\uacbd",def:"all of the things found in an area, indoors or outdoors",unit:2,opts:["safe", "forest", "environment", "service"]},
    {w:"forest",m:"\uc232",def:"a big area of trees",unit:2,opts:["active", "choice", "forest", "human"]},
    {w:"human",m:"\uc0ac\ub78c",def:"a person",unit:2,opts:["enter", "path", "forest", "human"]},
    {w:"hunt",m:"\uc0ac\ub0e5\ud558\ub2e4",def:"to look for animals to kill",unit:2,opts:["active", "wild", "hunt", "choice"]},
    {w:"path",m:"\uae38",def:"a way to go from one place to another",unit:2,opts:["active", "protect", "path", "choice"]},
    {w:"safe",m:"\uc548\uc804\ud55c",def:"not dangerous",unit:2,opts:["safe", "enter", "hunt", "human"]},
    {w:"service",m:"\uc11c\ube44\uc2a4",def:"the job of helping visitors at a place like a restaurant",unit:2,opts:["choice", "path", "service", "enter"]},
    {w:"wild",m:"\uc57c\uc0dd\uc758",def:"living or growing without humans\u2019 help",unit:2,opts:["wild", "path", "believe", "safe"]},
    {w:"area",m:"\uc9c0\uc5ed",def:"a part of a larger place",unit:2,opts:["active", "path", "shout", "area"]},
    {w:"choice",m:"\uc120\ud0dd",def:"something you can choose",unit:2,opts:["human", "choice", "lie", "service"]},
    {w:"enter",m:"\ub4e4\uc5b4\uac00\ub2e4",def:"to go in",unit:2,opts:["human", "usually", "enter", "hunt"]},
    {w:"important",m:"\uc911\uc694\ud55c",def:"having great meaning",unit:2,opts:["important", "nature", "hunt", "path"]},
    {w:"lie",m:"\ub215\ub2e4",def:"to be on your back on the ground or in a bed",unit:2,opts:["nature", "safe", "lie", "usually"]},
    {w:"mad",m:"\ud654\ub09c",def:"angry",unit:2,opts:["hunt", "choice", "mad", "active"]},
    {w:"nature",m:"\uc790\uc5f0",def:"everything in the world that is not made by humans",unit:2,opts:["human", "forest", "nature", "shout"]},
    {w:"protect",m:"\ubcf4\ud638\ud558\ub2e4",def:"to keep safe from harm",unit:2,opts:["usually", "area", "protect", "lie"]},
    {w:"shout",m:"\uc18c\ub9ac\uce58\ub2e4",def:"to say something very loudly",unit:2,opts:["active", "environment", "forest", "shout"]},
    {w:"usually",m:"\ubcf4\ud1b5",def:"most of the time",unit:2,opts:["path", "usually", "important", "shout"]},
  ],
  "bew3_3": [
    {w:"amazing",m:"\ub180\ub77c\uc6b4",def:"causing great surprise or wonder",unit:3,opts:["public", "event", "cheer", "amazing"]},
    {w:"attend",m:"\ucc38\uc11d\ud558\ub2e4",def:"to go to a class or activity",unit:3,opts:["express", "secret", "scene", "attend"]},
    {w:"event",m:"\ud589\uc0ac",def:"a special, planned activity",unit:3,opts:["event", "special", "stage", "express"]},
    {w:"express",m:"\ud45c\ud604\ud558\ub2e4",def:"to say, write, or show thoughts or feelings",unit:3,opts:["save", "stage", "cheer", "express"]},
    {w:"grade",m:"\ud559\ub144",def:"a level of study in school",unit:3,opts:["grade", "unique", "save", "set"]},
    {w:"part",m:"\ubd80\ubd84",def:"a piece; some but not all",unit:3,opts:["express", "part", "special", "event"]},
    {w:"save",m:"\uc808\uc57d\ud558\ub2e4",def:"to keep something to use later",unit:3,opts:["grade", "save", "part", "special"]},
    {w:"set",m:"\uc815\ud558\ub2e4",def:"to choose something",unit:3,opts:["amazing", "scene", "cheer", "set"]},
    {w:"space",m:"\uacf5\uac04",def:"an empty area where a person or thing can go",unit:3,opts:["magazine", "stage", "event", "space"]},
    {w:"special",m:"\ud2b9\ubcc4\ud55c",def:"different from the usual",unit:3,opts:["public", "express", "set", "special"]},
    {w:"cheer",m:"\uc751\uc6d0\ud558\ub2e4",def:"to shout to show happiness or to make others feel good",unit:3,opts:["magazine", "express", "secret", "cheer"]},
    {w:"contest",m:"\ub300\ud68c",def:"an event in which there is a winner",unit:3,opts:["set", "part", "contest", "event"]},
    {w:"gift",m:"\uc120\ubb3c",def:"something given to someone",unit:3,opts:["gift", "set", "save", "perform"]},
    {w:"magazine",m:"\uc7a1\uc9c0",def:"a thin book that comes out once a week or month",unit:3,opts:["cheer", "scene", "express", "magazine"]},
    {w:"perform",m:"\uacf5\uc5f0\ud558\ub2e4",def:"to do something like singing or acting in front of people",unit:3,opts:["perform", "express", "set", "scene"]},
    {w:"public",m:"\uacf5\uacf5\uc7a5\uc18c",def:"(after in) a place where many people can see you",unit:3,opts:["special", "amazing", "cheer", "public"]},
    {w:"scene",m:"\uc7a5\uba74",def:"a part of a play or movie",unit:3,opts:["secret", "scene", "contest", "express"]},
    {w:"secret",m:"\ube44\ubc00",def:"something that is kept hidden from other people",unit:3,opts:["special", "secret", "public", "set"]},
    {w:"stage",m:"\ubb34\ub300",def:"the part of a theater where people perform",unit:3,opts:["part", "express", "cheer", "stage"]},
    {w:"unique",m:"\ub3c5\ud2b9\ud55c",def:"not like anyone or anything else",unit:3,opts:["amazing", "unique", "special", "public"]},
  ],
  "bew3_4": [
    {w:"electricity",m:"\uc804\uae30",def:"something used to give light and make things work",unit:4,opts:["case", "fold", "electricity", "sock"]},
    {w:"fact",m:"\uc0ac\uc2e4",def:"something that is true",unit:4,opts:["sock", "advice", "fact", "succeed"]},
    {w:"fold",m:"\uc811\ub2e4",def:"to bend one part of something over another part",unit:4,opts:["stupid", "mind", "fold", "sock"]},
    {w:"key",m:"\uc5f4\uc1e0",def:"an object used to lock or unlock a door or to start a car",unit:4,opts:["exam", "case", "key", "lazy"]},
    {w:"mind",m:"\uaebc\ub9ac\ub2e4",def:"to be unhappy about something, usually used with not",unit:4,opts:["terrible", "stupid", "mind", "succeed"]},
    {w:"power",m:"\uc804\uc6d0",def:"something you cannot see that is used to make things work",unit:4,opts:["key", "exam", "case", "power"]},
    {w:"sock",m:"\uc591\ub9d0",def:"a soft piece of clothing that covers the foot",unit:4,opts:["stick", "terrible", "sock", "stupid"]},
    {w:"solve",m:"\ud480\ub2e4",def:"to find the answer",unit:4,opts:["power", "solve", "lazy", "case"]},
    {w:"stick",m:"\ubd99\uc774\ub2e4",def:"to attach to something",unit:4,opts:["case", "stick", "succeed", "fold"]},
    {w:"traffic",m:"\uad50\ud1b5",def:"cars on the road",unit:4,opts:["exam", "upset", "traffic", "message"]},
    {w:"advice",m:"\uc870\uc5b8",def:"an opinion about what someone should or should not do",unit:4,opts:["happen", "advice", "power", "stupid"]},
    {w:"case",m:"\ud1b5",def:"a small box or bag",unit:4,opts:["upset", "case", "stick", "lazy"]},
    {w:"exam",m:"\uc2dc\ud5d8",def:"a test",unit:4,opts:["solve", "message", "terrible", "exam"]},
    {w:"happen",m:"\ubc1c\uc0dd\ud558\ub2e4",def:"to take place",unit:4,opts:["fold", "sock", "exam", "happen"]},
    {w:"lazy",m:"\uac8c\uc73c\ub978",def:"not wanting to work or move",unit:4,opts:["lazy", "terrible", "power", "mind"]},
    {w:"message",m:"\uba54\uc2dc\uc9c0",def:"information that is sent or given to someone",unit:4,opts:["power", "message", "case", "stupid"]},
    {w:"stupid",m:"\uc5b4\ub9ac\uc11d\uc740",def:"dumb; foolish",unit:4,opts:["fact", "traffic", "stupid", "solve"]},
    {w:"succeed",m:"\uc131\uacf5\ud558\ub2e4",def:"to do well; to do what you tried to do",unit:4,opts:["fold", "key", "succeed", "message"]},
    {w:"terrible",m:"\ud615\ud3b8\uc5c6\ub294",def:"very bad",unit:4,opts:["fold", "happen", "case", "terrible"]},
    {w:"upset",m:"\uae30\ubd84\uc774 \uc5b8\uc9e2\uc740",def:"worried; not happy",unit:4,opts:["exam", "upset", "solve", "electricity"]},
  ],
  "bew3_5": [
    {w:"airplane",m:"\ube44\ud589\uae30",def:"a flying machine",unit:5,opts:["experience", "airplane", "sand", "order"]},
    {w:"airport",m:"\uacf5\ud56d",def:"a place where airplanes arrive and leave",unit:5,opts:["spot", "airport", "island", "order"]},
    {w:"culture",m:"\ubb38\ud654",def:"the way of life of a group of people",unit:5,opts:["airplane", "century", "culture", "journey"]},
    {w:"decide",m:"\uacb0\uc815\ud558\ub2e4",def:"to make a choice",unit:5,opts:["modern", "leave", "airport", "decide"]},
    {w:"leave",m:"\ub5a0\ub098\ub2e4",def:"to go away from",unit:5,opts:["leave", "journey", "bill", "modern"]},
    {w:"modern",m:"\ud604\ub300\uc801\uc778",def:"of the latest kind",unit:5,opts:["modern", "bill", "return", "leave"]},
    {w:"order",m:"\uc8fc\ubb38\ud558\ub2e4",def:"to ask for food or drink at a restaurant",unit:5,opts:["order", "leave", "airplane", "culture"]},
    {w:"sand",m:"\ubaa8\ub798",def:"very tiny pieces of rock",unit:5,opts:["spot", "experience", "leave", "sand"]},
    {w:"spot",m:"\uc7a5\uc18c",def:"an area, place, or location",unit:5,opts:["custom", "modern", "spot", "island"]},
    {w:"strange",m:"\uc774\uc0c1\ud55c",def:"different from what is usual",unit:5,opts:["sand", "leave", "airplane", "strange"]},
    {w:"bill",m:"\uc9c0\ud3d0",def:"a piece of paper money",unit:5,opts:["modern", "experience", "bill", "return"]},
    {w:"blow",m:"\ubd88\ub2e4",def:"to move something with air",unit:5,opts:["island", "blow", "journey", "century"]},
    {w:"century",m:"100\ub144",def:"one hundred years",unit:5,opts:["century", "experience", "strange", "sand"]},
    {w:"custom",m:"\uad00\uc2b5",def:"the usual way of doing something in a culture",unit:5,opts:["international", "decide", "airport", "custom"]},
    {w:"experience",m:"\uacbd\ud5d8\ud558\ub2e4",def:"to see, feel, or do something",unit:5,opts:["century", "experience", "airport", "island"]},
    {w:"international",m:"\uad6d\uc81c\uc801\uc778",def:"happening in or between two or more countries",unit:5,opts:["international", "culture", "airplane", "island"]},
    {w:"island",m:"\uc12c",def:"a piece of land in the middle of water",unit:5,opts:["leave", "island", "return", "decide"]},
    {w:"journey",m:"\uc5ec\ud589",def:"a long trip",unit:5,opts:["return", "journey", "leave", "century"]},
    {w:"meal",m:"\uc74c\uc2dd",def:"food that is prepared and eaten",unit:5,opts:["experience", "century", "meal", "sand"]},
    {w:"return",m:"\ub3cc\uc544\uc624\ub2e4",def:"to come back after being away",unit:5,opts:["modern", "bill", "return", "decide"]},
  ],
  "bew3_6": [
    {w:"actually",m:"\uc0ac\uc2e4\uc740",def:"in fact",unit:6,opts:["symbol", "actually", "simple", "member"]},
    {w:"camp",m:"\uc57c\uc601\ud558\ub2e4",def:"to sleep outside in a tent",unit:6,opts:["camp", "actually", "force", "review"]},
    {w:"collect",m:"\ubaa8\uc73c\ub2e4",def:"to bring things together into one group",unit:6,opts:["real", "simple", "reach", "collect"]},
    {w:"form",m:"\ub9cc\ub4e4\ub2e4",def:"to make",unit:6,opts:["reach", "soccer", "form", "simple"]},
    {w:"kick",m:"\ucc28\ub2e4",def:"to hit something with your foot",unit:6,opts:["reach", "simple", "kick", "member"]},
    {w:"reach",m:"\uc190\uc744 \ubed7\ub2e4",def:"to stretch out the arm to touch or get with your hand",unit:6,opts:["reach", "actually", "bat", "step"]},
    {w:"review",m:"\ubcf5\uc2b5\ud558\ub2e4",def:"to look at or study something again",unit:6,opts:["allow", "bat", "step", "review"]},
    {w:"simple",m:"\uac04\ub2e8\ud55c",def:"easy",unit:6,opts:["allow", "leaf", "collect", "simple"]},
    {w:"soccer",m:"\ucd95\uad6c",def:"a sport in which a ball is kicked into a goal to win a point",unit:6,opts:["review", "soccer", "kick", "simple"]},
    {w:"symbol",m:"\uc0c1\uc9d5",def:"a shape with a special meaning",unit:6,opts:["camp", "kick", "symbol", "form"]},
    {w:"allow",m:"\ud5c8\ub77d\ud558\ub2e4",def:"to let someone do something",unit:6,opts:["form", "member", "collect", "allow"]},
    {w:"bat",m:"\ubc15\uc950",def:"a flying animal that hunts at night",unit:6,opts:["sign", "bat", "soccer", "reach"]},
    {w:"exercise",m:"\uc6b4\ub3d9\ud558\ub2e4",def:"to move the body as a way to get healthy",unit:6,opts:["symbol", "simple", "kick", "exercise"]},
    {w:"force",m:"\uac15\uc694\ud558\ub2e4",def:"to make people do things they do not want to do",unit:6,opts:["exercise", "step", "camp", "force"]},
    {w:"leaf",m:"\ub098\ubb47\uc78e",def:"the flat green part of a plant",unit:6,opts:["member", "soccer", "allow", "leaf"]},
    {w:"member",m:"\ud68c\uc6d0",def:"a person in a group or club",unit:6,opts:["soccer", "member", "simple", "reach"]},
    {w:"real",m:"\uc9c4\uc9dc\uc758",def:"actually happening; being what it looks like",unit:6,opts:["exercise", "review", "real", "soccer"]},
    {w:"sign",m:"\ud45c\uc9c0\ud310",def:"a flat board or paper with a message on it",unit:6,opts:["force", "leaf", "real", "sign"]},
    {w:"step",m:"\ubc1f\ub2e4",def:"to move your foot up and put it down in a different spot",unit:6,opts:["soccer", "symbol", "step", "allow"]},
    {w:"treat",m:"\uac04\uc2dd",def:"something nice that you do not eat or do often",unit:6,opts:["member", "step", "camp", "treat"]},
  ],
  "bew3_7": [
    {w:"afraid",m:"\ub450\ub824\uc6cc\ud558\ub294",def:"feeling fear",unit:7,opts:["fair", "sentence", "afraid", "habit"]},
    {w:"fair",m:"\uacf5\ud3c9\ud55c",def:"good for everyone",unit:7,opts:["college", "foreign", "honest", "fair"]},
    {w:"focus",m:"\uc9d1\uc911\ud558\ub2e4",def:"to put all of your thoughts on one thing",unit:7,opts:["fair", "focus", "honest", "level"]},
    {w:"foreign",m:"\uc678\uad6d\uc758",def:"from a different country",unit:7,opts:["comfortable", "stress", "foreign", "habit"]},
    {w:"habit",m:"\uc2b5\uad00",def:"something you do often, usually without thinking about it",unit:7,opts:["audience", "habit", "comfortable", "foreign"]},
    {w:"invent",m:"\ubc1c\uba85\ud558\ub2e4",def:"to make something for the first time",unit:7,opts:["invent", "stress", "language", "comfortable"]},
    {w:"language",m:"\uc5b8\uc5b4",def:"the words and symbols used by people of one country or area",unit:7,opts:["sentence", "honest", "language", "invent"]},
    {w:"nation",m:"\ub098\ub77c",def:"a country",unit:7,opts:["nation", "topic", "still", "habit"]},
    {w:"still",m:"\uac00\ub9cc\ud788 \uc788\ub294",def:"not moving",unit:7,opts:["sentence", "honest", "fair", "still"]},
    {w:"wise",m:"\ud604\uba85\ud55c",def:"knowing the right things to do",unit:7,opts:["topic", "still", "comfortable", "wise"]},
    {w:"audience",m:"\uad00\uc911",def:"a group of people watching an event or show",unit:7,opts:["stress", "habit", "audience", "still"]},
    {w:"college",m:"\ub300\ud559",def:"a school where students study after high school",unit:7,opts:["college", "level", "language", "focus"]},
    {w:"comfortable",m:"\ud3b8\uc548\ud55c",def:"feeling relaxed",unit:7,opts:["audience", "comfortable", "suddenly", "fair"]},
    {w:"honest",m:"\uc815\uc9c1\ud55c",def:"good and saying things that are true",unit:7,opts:["imagine", "college", "focus", "honest"]},
    {w:"imagine",m:"\uc0c1\uc0c1\ud558\ub2e4",def:"to think of things that are not real",unit:7,opts:["suddenly", "sentence", "level", "imagine"]},
    {w:"level",m:"\uc815\ub3c4",def:"an amount of something",unit:7,opts:["level", "foreign", "language", "topic"]},
    {w:"sentence",m:"\ubb38\uc7a5",def:"a set of words that make a statement or question",unit:7,opts:["afraid", "habit", "topic", "sentence"]},
    {w:"stress",m:"\uc2a4\ud2b8\ub808\uc2a4",def:"worry caused by problems in your life",unit:7,opts:["stress", "foreign", "comfortable", "nation"]},
    {w:"suddenly",m:"\uac11\uc790\uae30",def:"very quickly",unit:7,opts:["stress", "suddenly", "still", "honest"]},
    {w:"topic",m:"\uc8fc\uc81c",def:"a subject people talk or write about",unit:7,opts:["college", "focus", "topic", "suddenly"]},
  ],
  "bew3_8": [
    {w:"add",m:"\ucca8\uac00\ud558\ub2e4",def:"to put one thing with another thing or things",unit:8,opts:["blind", "add", "match", "celebrate"]},
    {w:"blind",m:"\ub208\uc774 \uba3c",def:"not able to see",unit:8,opts:["string", "blind", "social", "princess"]},
    {w:"button",m:"\ub2e8\ucd94",def:"a small round thing used to close an opening in clothing",unit:8,opts:["add", "button", "blind", "item"]},
    {w:"create",m:"\ucc3d\uc791\ud558\ub2e4",def:"to make something",unit:8,opts:["string", "button", "create", "tear"]},
    {w:"memory",m:"\uae30\uc5b5",def:"something from the past that is remembered",unit:8,opts:["prince", "memory", "board", "tradition"]},
    {w:"prince",m:"\uc655\uc790",def:"the son of a king or queen",unit:8,opts:["button", "princess", "hole", "prince"]},
    {w:"string",m:"\ub048",def:"a long thread used to keep things together",unit:8,opts:["string", "create", "tradition", "match"]},
    {w:"thick",m:"\ub450\uaebc\uc6b4",def:"having a large distance from top to bottom",unit:8,opts:["princess", "add", "thick", "tight"]},
    {w:"tight",m:"\uaf49 \ub9de\ub294",def:"fitting close to the body",unit:8,opts:["match", "memory", "princess", "tight"]},
    {w:"tradition",m:"\uc804\ud1b5",def:"a custom that has been around for a long time",unit:8,opts:["tradition", "celebrate", "especially", "memory"]},
    {w:"board",m:"\ub110\ube64\uc9c0",def:"a flat, wide piece of wood",unit:8,opts:["tradition", "string", "brain", "board"]},
    {w:"brain",m:"\ub1cc",def:"the part of the body inside your head",unit:8,opts:["board", "brain", "princess", "celebrate"]},
    {w:"celebrate",m:"\ucd95\ud558\ud558\ub2e4",def:"to do something special for an important event",unit:8,opts:["match", "string", "button", "celebrate"]},
    {w:"especially",m:"\ud2b9\ud788",def:"in a way that is greater than usual",unit:8,opts:["especially", "string", "button", "tight"]},
    {w:"hole",m:"\uad6c\uba4d",def:"an opening that something can pass through",unit:8,opts:["hole", "item", "match", "tight"]},
    {w:"item",m:"\ubb3c\ud488",def:"a thing that is usually part of a group",unit:8,opts:["prince", "especially", "thick", "item"]},
    {w:"match",m:"\uc77c\uce58\ud558\ub2e4",def:"to look similar to something",unit:8,opts:["brain", "board", "add", "match"]},
    {w:"princess",m:"\uacf5\uc8fc",def:"the daughter of a king or queen",unit:8,opts:["button", "princess", "memory", "blind"]},
    {w:"social",m:"\uc0ac\uad50\uc801\uc778",def:"having a need to be with others",unit:8,opts:["button", "social", "string", "celebrate"]},
    {w:"tear",m:"\ucc22\ub2e4",def:"to pull something into parts",unit:8,opts:["hole", "tear", "board", "tradition"]},
  ],
  "bew3_9": [
    {w:"cross",m:"\uac74\ub108\ub2e4",def:"to go from one side to the other",unit:9,opts:["cross", "heat", "climb", "perfect"]},
    {w:"finally",m:"\ub9c8\uce68\ub0b4",def:"after a long time",unit:9,opts:["finally", "perfect", "follow", "cross"]},
    {w:"follow",m:"\ub530\ub77c\uac00\ub2e4",def:"to go after; to do what a person or thing says",unit:9,opts:["follow", "heat", "engine", "finally"]},
    {w:"heat",m:"\ub530\ub73b\ud558\uac8c \ud558\ub2e4",def:"to make something hot",unit:9,opts:["cross", "stone", "energy", "heat"]},
    {w:"rainbow",m:"\ubb34\uc9c0\uac1c",def:"a curved line of colors in the sky",unit:9,opts:["follow", "energy", "rainbow", "shape"]},
    {w:"spread",m:"\ud3bc\uce58\ub2e4",def:"to open or place something so that it covers a large area",unit:9,opts:["vote", "perfect", "shape", "spread"]},
    {w:"tired",m:"\ud53c\uace4\ud55c",def:"needing rest or sleep",unit:9,opts:["field", "tower", "cross", "tired"]},
    {w:"tower",m:"\ud0d1",def:"a tall and narrow building",unit:9,opts:["shape", "tower", "tired", "engine"]},
    {w:"unit",m:"\ub2e8\uc6d0",def:"one part of something",unit:9,opts:["shape", "unit", "energy", "follow"]},
    {w:"vote",m:"\ud22c\ud45c\ud558\ub2e4",def:"to make a choice for or against a person or thing",unit:9,opts:["engine", "stone", "vote", "heat"]},
    {w:"climb",m:"\uc624\ub974\ub2e4",def:"to go up or down using your feet and hands",unit:9,opts:["spread", "climb", "vote", "shape"]},
    {w:"describe",m:"\uc124\uba85\ud558\ub2e4",def:"to talk about what something is like",unit:9,opts:["describe", "climb", "tower", "finally"]},
    {w:"energy",m:"\ud65c\uae30, \ud798",def:"power; the ability to be active",unit:9,opts:["describe", "rise", "finally", "energy"]},
    {w:"engine",m:"\uc5d4\uc9c4",def:"the part of a car that makes power for it to move",unit:9,opts:["heat", "tower", "engine", "climb"]},
    {w:"field",m:"\ub4e4\ud310",def:"a grassy area that has no trees or buildings",unit:9,opts:["energy", "unit", "perfect", "field"]},
    {w:"include",m:"\ud3ec\ud568\ud558\ub2e4",def:"to have a person or thing as part of a group",unit:9,opts:["describe", "include", "climb", "stone"]},
    {w:"perfect",m:"\uc644\ubcbd\ud55c",def:"not having anything wrong",unit:9,opts:["perfect", "cross", "vote", "rise"]},
    {w:"rise",m:"\uc62c\ub77c\uac00\ub2e4",def:"to move upward",unit:9,opts:["engine", "climb", "rainbow", "rise"]},
    {w:"shape",m:"\ubaa8\uc591",def:"the outline of something",unit:9,opts:["follow", "shape", "tower", "field"]},
    {w:"stone",m:"\ub3cc",def:"a small rock",unit:9,opts:["stone", "energy", "finally", "tower"]},
  ],
  "bew3_10": [
    {w:"bake",m:"\uad7d\ub2e4",def:"to make something and cook it in an oven",unit:10,opts:["interview", "bake", "deliver", "sport"]},
    {w:"communicate",m:"\uc758\uc0ac\uc18c\ud1b5\ud558\ub2e4",def:"to share thoughts and feelings with another person",unit:10,opts:["festival", "direct", "communicate", "deliver"]},
    {w:"deliver",m:"\ubc30\ub2ec\ud558\ub2e4",def:"to take something to a person or place",unit:10,opts:["uniform", "million", "deliver", "whole"]},
    {w:"direct",m:"\uac10\ub3c5\ud558\ub2e4",def:"to tell an actor or a group of actors what to do",unit:10,opts:["festival", "whole", "goal", "direct"]},
    {w:"goal",m:"\ubaa9\ud45c",def:"something you are trying to do",unit:10,opts:["support", "interview", "million", "goal"]},
    {w:"history",m:"\uc5ed\uc0ac",def:"events in the past",unit:10,opts:["uniform", "history", "direct", "community"]},
    {w:"inform",m:"\uc54c\ub9ac\ub2e4",def:"to let others know about something",unit:10,opts:["march", "inform", "appear", "community"]},
    {w:"mail",m:"\uc6b0\ud3b8\ubb3c",def:"letters or packages sent to others",unit:10,opts:["festival", "mail", "report", "whole"]},
    {w:"march",m:"\ud589\uc9c4\ud558\ub2e4",def:"to walk as a group in step with each other",unit:10,opts:["goal", "march", "newspaper", "inform"]},
    {w:"whole",m:"\uc804\uccb4\uc758",def:"all of something",unit:10,opts:["whole", "bake", "goal", "million"]},
    {w:"appear",m:"\ub098\ud0c0\ub098\ub2e4",def:"to be seen",unit:10,opts:["sport", "appear", "uniform", "direct"]},
    {w:"community",m:"\uacf5\ub3d9\uccb4, \uc9c0\uc5ed \uc0ac\ud68c",def:"a group of people living in the same area",unit:10,opts:["uniform", "newspaper", "community", "report"]},
    {w:"festival",m:"\ucd95\uc81c",def:"a special party with events to celebrate something",unit:10,opts:["bake", "march", "festival", "report"]},
    {w:"interview",m:"\uba74\uc811\uc744 \ubcf4\ub2e4",def:"to ask someone many questions",unit:10,opts:["interview", "festival", "sport", "community"]},
    {w:"million",m:"100\ub9cc\uc758",def:"of the number 1,000,000",unit:10,opts:["direct", "goal", "million", "mail"]},
    {w:"newspaper",m:"\uc2e0\ubb38",def:"a set of large papers with stories about true events",unit:10,opts:["interview", "newspaper", "goal", "history"]},
    {w:"report",m:"\uc804\ud558\ub2e4",def:"to give news on television or in a newspaper",unit:10,opts:["uniform", "appear", "communicate", "report"]},
    {w:"sport",m:"\uc2a4\ud3ec\uce20, \uc6b4\ub3d9",def:"an active game with rules that people play",unit:10,opts:["million", "sport", "history", "direct"]},
    {w:"support",m:"\uc9c0\uc9c0\ud558\ub2e4",def:"to show you like and want to help a person or group",unit:10,opts:["report", "festival", "goal", "support"]},
    {w:"uniform",m:"\uc720\ub2c8\ud3fc",def:"the clothing worn by members of a group",unit:10,opts:["uniform", "bake", "whole", "appear"]},
  ],
  "bew3_11": [
    {w:"brave",m:"\uc6a9\uac10\ud55c",def:"not afraid",unit:11,opts:["product", "brave", "roll", "corn"]},
    {w:"goat",m:"\uc5fc\uc18c",def:"a small animal that lives on a farm or in the mountains",unit:11,opts:["hang", "insect", "sore", "goat"]},
    {w:"hang",m:"\ub9e4\ub2ec\ub2e4",def:"to place something so that it is held at the top",unit:11,opts:["roll", "quite", "hang", "roof"]},
    {w:"ice",m:"\uc5bc\uc74c",def:"frozen water",unit:11,opts:["brave", "village", "ice", "sore"]},
    {w:"insect",m:"\uace4\ucda9",def:"a small animal with six legs",unit:11,opts:["rope", "sore", "quite", "insect"]},
    {w:"raise",m:"\uae30\ub974\ub2e4",def:"to care for an animal or plant as it grows",unit:11,opts:["tent", "medicine", "goat", "raise"]},
    {w:"roll",m:"\uad74\ub9ac\ub2e4",def:"to turn over and over",unit:11,opts:["ice", "sore", "roll", "brave"]},
    {w:"sore",m:"\uc544\ud508",def:"hurting",unit:11,opts:["sore", "accident", "brave", "product"]},
    {w:"tent",m:"\ud150\ud2b8",def:"a covered place to sleep outside",unit:11,opts:["rope", "accident", "roof", "tent"]},
    {w:"village",m:"\ub9c8\uc744",def:"a very small town",unit:11,opts:["roof", "ice", "sore", "village"]},
    {w:"accident",m:"\uc0ac\uace0",def:"a sudden bad event in which someone might be hurt",unit:11,opts:["accident", "roll", "village", "corn"]},
    {w:"adventure",m:"\ubaa8\ud5d8",def:"an exciting experience",unit:11,opts:["ice", "product", "adventure", "corn"]},
    {w:"corn",m:"\uc625\uc218\uc218",def:"a vegetable with many small yellow seeds",unit:11,opts:["village", "develop", "corn", "hang"]},
    {w:"develop",m:"\uac1c\ubc1c\ud558\ub2e4",def:"to create something over time",unit:11,opts:["tent", "product", "develop", "accident"]},
    {w:"medicine",m:"\uc57d",def:"something that helps a sick person or animal",unit:11,opts:["develop", "raise", "medicine", "adventure"]},
    {w:"own",m:"\uc18c\uc720\ud558\ub2e4",def:"to pay for something so it belongs to you",unit:11,opts:["accident", "develop", "own", "medicine"]},
    {w:"product",m:"\uc0c1\ud488",def:"something that is made or grown and sold",unit:11,opts:["product", "accident", "rope", "roof"]},
    {w:"quite",m:"\uaf64",def:"very",unit:11,opts:["quite", "goat", "accident", "rope"]},
    {w:"roof",m:"\uc9c0\ubd95",def:"the top covering on a building",unit:11,opts:["accident", "sore", "roof", "hang"]},
    {w:"rope",m:"\ubc27\uc904",def:"a very thick and strong string",unit:11,opts:["corn", "roof", "raise", "rope"]},
  ],
  "bew3_12": [
    {w:"carrot",m:"\ub2f9\uadfc",def:"an orange vegetable that grows under the ground",unit:12,opts:["mark", "carrot", "ground", "lay"]},
    {w:"cause",m:"\uc57c\uae30\ud558\ub2e4, \uc77c\uc73c\ud0a4\ub2e4",def:"to make something happen",unit:12,opts:["lay", "cause", "possible", "price"]},
    {w:"experiment",m:"\uc2e4\ud5d8\ud558\ub2e4",def:"to try something new",unit:12,opts:["mark", "experiment", "fry", "carrot"]},
    {w:"fry",m:"\uae30\ub984\uc5d0 \ud280\uae30\ub2e4",def:"to cook in oil",unit:12,opts:["proud", "pot", "mix", "fry"]},
    {w:"ground",m:"\ub545",def:"the land under your feet",unit:12,opts:["mark", "experiment", "ground", "fry"]},
    {w:"kill",m:"\uc8fd\uc774\ub2e4",def:"to end a life",unit:12,opts:["kill", "soil", "possible", "fry"]},
    {w:"mix",m:"\uc11e\ub2e4",def:"to put two or more things together",unit:12,opts:["mark", "mix", "kill", "fry"]},
    {w:"possible",m:"\uac00\ub2a5\ud55c",def:"able to be done",unit:12,opts:["cause", "possible", "mark", "taste"]},
    {w:"pot",m:"\ub0c4\ube44",def:"a deep, round container used for cooking",unit:12,opts:["pot", "list", "mix", "taste"]},
    {w:"proud",m:"\uc790\ub791\uc2a4\ub7ec\uc6cc\ud558\ub294",def:"feeling good about something done",unit:12,opts:["share", "main", "proud", "ground"]},
    {w:"lay",m:"\ub193\ub2e4",def:"to put something down carefully",unit:12,opts:["proud", "lay", "mix", "several"]},
    {w:"list",m:"\ubaa9\ub85d",def:"a number of items that are needed",unit:12,opts:["mistake", "fry", "soil", "list"]},
    {w:"main",m:"\uc8fc\uc694\ud55c",def:"most important",unit:12,opts:["main", "mark", "proud", "lay"]},
    {w:"mark",m:"\ud45c\uc2dc",def:"a symbol or shape drawn on something",unit:12,opts:["main", "proud", "mark", "ground"]},
    {w:"mistake",m:"\uc2e4\uc218",def:"something that is not correct",unit:12,opts:["taste", "list", "pot", "mistake"]},
    {w:"price",m:"\uac00\uaca9",def:"the amount that something costs",unit:12,opts:["mistake", "main", "proud", "price"]},
    {w:"several",m:"\uc5ec\ub7ec \uac1c\uc758",def:"more than two but not many",unit:12,opts:["mark", "share", "ground", "several"]},
    {w:"share",m:"\ud568\uaed8 \uc4f0\ub2e4",def:"to allow someone to use or enjoy something of yours",unit:12,opts:["taste", "kill", "fry", "share"]},
    {w:"soil",m:"\ud1a0\uc591",def:"dirt",unit:12,opts:["proud", "soil", "pot", "share"]},
    {w:"taste",m:"\ub9db\ubcf4\ub2e4",def:"to get the flavor of food in the mouth",unit:12,opts:["cause", "share", "proud", "taste"]},
  ],
  "bew4_1": [
    {w:"awful",m:"\uc9c0\ub3c5\ud55c",def:"very bad",unit:1,opts:["awful", "tough", "pour", "chance"]},
    {w:"crazy",m:"\uc815\uc0c1\uc774 \uc544\ub2cc",def:"very strange",unit:1,opts:["search", "mention", "crazy", "score"]},
    {w:"huge",m:"\uac70\ub300\ud55c",def:"very large",unit:1,opts:["regret", "tough", "huge", "thief"]},
    {w:"moment",m:"\uc7a0\uc2dc",def:"a short period of time",unit:1,opts:["hall", "score", "tough", "moment"]},
    {w:"odd",m:"\uc774\uc0c1\ud55c",def:"strange or different",unit:1,opts:["odd", "immediately", "intend", "awful"]},
    {w:"pour",m:"\ubd93\ub2e4",def:"to fill a container with something to drink",unit:1,opts:["regret", "pour", "score", "tough"]},
    {w:"regret",m:"\ud6c4\ud68c\ud558\ub2e4",def:"to feel sorry about something that you did or did not do",unit:1,opts:["regret", "mention", "extra", "score"]},
    {w:"steal",m:"\ud6d4\uce58\ub2e4",def:"to take something without someone saying you can",unit:1,opts:["score", "worse", "steal", "hall"]},
    {w:"thief",m:"\ub3c4\ub451",def:"someone who steals",unit:1,opts:["thief", "tough", "extra", "score"]},
    {w:"tough",m:"\uac15\uc778\ud55c",def:"strong",unit:1,opts:["tough", "search", "intend", "odd"]},
    {w:"chance",m:"\uae30\ud68c",def:"an opportunity to do something",unit:1,opts:["crazy", "mention", "chance", "intend"]},
    {w:"extra",m:"\ucd94\uac00\uc758",def:"more than is usual",unit:1,opts:["intend", "odd", "extra", "regret"]},
    {w:"hall",m:"\uac15\ub2f9",def:"a large open space in a building",unit:1,opts:["steal", "immediately", "hall", "awful"]},
    {w:"immediately",m:"\uc989\uc2dc",def:"right away",unit:1,opts:["immediately", "hall", "mention", "moment"]},
    {w:"intend",m:"\uc791\uc815\ud558\ub2e4",def:"to want or plan to do",unit:1,opts:["intend", "score", "search", "thief"]},
    {w:"mention",m:"\uc5b8\uae09\ud558\ub2e4",def:"to talk or write about something, often quickly",unit:1,opts:["crazy", "mention", "search", "moment"]},
    {w:"reaction",m:"\ubc18\uc751",def:"the way someone acts or feels after something happens",unit:1,opts:["reaction", "hall", "tough", "immediately"]},
    {w:"score",m:"\ub4dd\uc810\uc744 \uae30\ub85d\ud558\ub2e4",def:"to win a point in a game",unit:1,opts:["immediately", "score", "worse", "odd"]},
    {w:"search",m:"\uc218\uc0c9\ud558\ub2e4",def:"to look for",unit:1,opts:["immediately", "awful", "worse", "search"]},
    {w:"worse",m:"\ub354 \uc548 \uc88b\uc740",def:"more terrible than other things",unit:1,opts:["reaction", "worse", "pour", "immediately"]},
  ],
  "bew4_2": [
    {w:"bit",m:"\uc791\uc740 \uc870\uac01",def:"a small piece or amount",unit:2,opts:["physical", "produce", "limit", "bit"]},
    {w:"common",m:"\ud754\ud55c",def:"usual; happening or seen often",unit:2,opts:["amount", "common", "necessary", "bit"]},
    {w:"diet",m:"\uc2dd\uc0ac",def:"the food that someone usually eats",unit:2,opts:["reduce", "produce", "medical", "diet"]},
    {w:"evidence",m:"\uc99d\uac70",def:"something that shows something else is true",unit:2,opts:["sale", "limit", "evidence", "reduce"]},
    {w:"fit",m:"\uac74\uac15\ud55c",def:"strong and healthy",unit:2,opts:["type", "necessary", "sale", "fit"]},
    {w:"limit",m:"\uc81c\ud55c\ud558\ub2e4",def:"to keep at a low level or keep from getting larger",unit:2,opts:["physical", "limit", "cure", "produce"]},
    {w:"physical",m:"\uc2e0\uccb4\uc758",def:"of the body",unit:2,opts:["amount", "sale", "cure", "physical"]},
    {w:"poison",m:"\ub3c5\uc57d",def:"something that can make you sick if eaten or drunk",unit:2,opts:["type", "poison", "supply", "serious"]},
    {w:"sale",m:"\ud310\ub9e4",def:"the act of selling something for money",unit:2,opts:["amount", "source", "sale", "supply"]},
    {w:"type",m:"\uc885\ub958",def:"a kind or variety",unit:2,opts:["produce", "type", "amount", "bit"]},
    {w:"amount",m:"\uc591",def:"how much there is of something",unit:2,opts:["diet", "amount", "disease", "limit"]},
    {w:"cure",m:"\uce58\uc720\ubc95",def:"something that makes sick people better",unit:2,opts:["produce", "reduce", "limit", "cure"]},
    {w:"disease",m:"\uc9c8\ubcd1",def:"a sickness",unit:2,opts:["disease", "medical", "evidence", "limit"]},
    {w:"medical",m:"\uc758\ud559\uc801\uc778",def:"of medicine; treating people who are sick or hurt",unit:2,opts:["common", "disease", "poison", "medical"]},
    {w:"necessary",m:"\ud544\uc218\uc801\uc778",def:"needed",unit:2,opts:["necessary", "limit", "medical", "type"]},
    {w:"produce",m:"\uc0dd\uc0b0\ud558\ub2e4",def:"to make or cause",unit:2,opts:["evidence", "poison", "bit", "produce"]},
    {w:"reduce",m:"\ub0ae\ucd94\ub2e4",def:"to make smaller in size, number, or amount",unit:2,opts:["reduce", "produce", "sale", "cure"]},
    {w:"serious",m:"\uc2ec\uac01\ud55c",def:"having important or dangerous possible results",unit:2,opts:["produce", "serious", "poison", "fit"]},
    {w:"source",m:"\uc6d0\ucc9c",def:"a person or thing that gives what is wanted or needed",unit:2,opts:["necessary", "source", "amount", "bit"]},
    {w:"supply",m:"\uc81c\uacf5\ud558\ub2e4",def:"to give someone something so they can use it",unit:2,opts:["sale", "supply", "necessary", "cure"]},
  ],
  "bew4_3": [
    {w:"castle",m:"\uc131",def:"a large home where a king or queen usually lives",unit:3,opts:["guard", "flight", "castle", "respect"]},
    {w:"decision",m:"\uacb0\uc815",def:"a choice",unit:3,opts:["castle", "decision", "incredible", "wave"]},
    {w:"empire",m:"\uc81c\uad6d",def:"a kingdom",unit:3,opts:["flight", "admire", "serve", "empire"]},
    {w:"explore",m:"\ud0d0\ud5d8\ud558\ub2e4",def:"to look at something in a careful way to learn about it",unit:3,opts:["incredible", "ancient", "southern", "explore"]},
    {w:"flight",m:"\ube44\ud589",def:"a trip on an airplane",unit:3,opts:["skin", "southern", "flight", "wave"]},
    {w:"guard",m:"\uc9c0\ud0a4\ub2e4",def:"to watch in order to protect",unit:3,opts:["incredible", "guard", "prefer", "decision"]},
    {w:"incredible",m:"\ubbff\uc5b4\uc9c0\uc9c0 \uc54a\uc744 \uc815\ub3c4\ub85c \uc88b\uc740",def:"very good",unit:3,opts:["skin", "decision", "pack", "incredible"]},
    {w:"serve",m:"\uc81c\uacf5\ud558\ub2e4",def:"to give someone food in a restaurant or at home",unit:3,opts:["giant", "serve", "decision", "castle"]},
    {w:"skin",m:"\ud53c\ubd80",def:"the outer part that covers humans and animals",unit:3,opts:["skin", "wave", "ancient", "guard"]},
    {w:"southern",m:"\ub0a8\ucabd\uc758",def:"being in or toward the south",unit:3,opts:["castle", "southern", "flight", "pack"]},
    {w:"admire",m:"\uc874\uacbd\ud558\ub2e4",def:"to like and think good things about others",unit:3,opts:["ancient", "skin", "admire", "respect"]},
    {w:"ancient",m:"\uace0\ub300\uc758",def:"very old",unit:3,opts:["wave", "ancient", "view", "rent"]},
    {w:"attractive",m:"\uba4b\uc9c4",def:"looking or sounding nice",unit:3,opts:["flight", "southern", "incredible", "attractive"]},
    {w:"giant",m:"\uac70\ub300\ud55c",def:"very large",unit:3,opts:["explore", "rent", "flight", "giant"]},
    {w:"pack",m:"\uc9d0\uc744 \uc2f8\ub2e4",def:"to put items into a bag or suitcase to take somewhere",unit:3,opts:["pack", "ancient", "rent", "wave"]},
    {w:"prefer",m:"\uc120\ud638\ud558\ub2e4",def:"to like something more than something else",unit:3,opts:["guard", "prefer", "pack", "decision"]},
    {w:"rent",m:"\uc784\ub300\ud558\ub2e4",def:"to pay money to use a thing that belongs to someone else",unit:3,opts:["rent", "flight", "wave", "southern"]},
    {w:"respect",m:"\uc874\uc911\ud558\ub2e4",def:"to think someone is special and important",unit:3,opts:["view", "respect", "attractive", "pack"]},
    {w:"view",m:"\ubcf4\ub2e4",def:"to look at or watch something",unit:3,opts:["skin", "empire", "view", "flight"]},
    {w:"wave",m:"\uc190\uc744 \ud754\ub4e4\ub2e4",def:"to move your hand to say hello or goodbye",unit:3,opts:["wave", "giant", "explore", "prefer"]},
  ],
  "bew4_4": [
    {w:"base",m:"\uae30\ubc18\uc744 \ub450\ub2e4",def:"to use as the starting point for something",unit:4,opts:["regularly", "base", "enemy", "female"]},
    {w:"character",m:"\ub4f1\uc7a5\uc778\ubb3c",def:"a person in a book or movie",unit:4,opts:["enemy", "length", "character", "opinion"]},
    {w:"clever",m:"\uc601\ub9ac\ud55c",def:"very smart",unit:4,opts:["regularly", "length", "clever", "female"]},
    {w:"enemy",m:"\uc801",def:"someone who hates you",unit:4,opts:["enemy", "clever", "desert", "flow"]},
    {w:"length",m:"\uae38\uc774",def:"how long something is from one end to the other",unit:4,opts:["regularly", "length", "flow", "survive"]},
    {w:"promise",m:"\uc57d\uc18d\ud558\ub2e4",def:"to tell someone that you will do something for sure",unit:4,opts:["promise", "title", "adult", "mystery"]},
    {w:"quality",m:"\uc9c8",def:"how good or bad something is",unit:4,opts:["base", "quality", "clever", "length"]},
    {w:"regularly",m:"\uc790\uc8fc",def:"often",unit:4,opts:["length", "enemy", "regularly", "publish"]},
    {w:"survive",m:"\uc0b4\uc544\ub0a8\ub2e4",def:"to stay alive",unit:4,opts:["pleasure", "survive", "flow", "quality"]},
    {w:"title",m:"\uc81c\ubaa9",def:"a name of something like a book or movie",unit:4,opts:["title", "length", "base", "regularly"]},
    {w:"adult",m:"\uc5b4\ub978",def:"someone who is fully grown",unit:4,opts:["female", "character", "adult", "flow"]},
    {w:"classic",m:"\uace0\uc804\uc801\uc778",def:"of good quality and popular for a long time",unit:4,opts:["quality", "adult", "female", "classic"]},
    {w:"desert",m:"\ubc84\ub9ac\ub2e4",def:"to leave a place so it is empty",unit:4,opts:["flow", "desert", "publish", "clever"]},
    {w:"discover",m:"\ubc1c\uacac\ud558\ub2e4",def:"to find",unit:4,opts:["survive", "discover", "enemy", "title"]},
    {w:"female",m:"\uc5ec\uc131\uc758",def:"being a girl or woman",unit:4,opts:["character", "discover", "female", "adult"]},
    {w:"flow",m:"\ud750\ub974\ub2e4",def:"to move like water",unit:4,opts:["length", "flow", "adult", "character"]},
    {w:"mystery",m:"\uc218\uc218\uaed8\ub07c",def:"something strange and not understood",unit:4,opts:["mystery", "regularly", "clever", "length"]},
    {w:"opinion",m:"\uc758\uacac",def:"a belief about something",unit:4,opts:["opinion", "length", "promise", "pleasure"]},
    {w:"pleasure",m:"\uae30\uc068",def:"a feeling of happiness",unit:4,opts:["base", "pleasure", "flow", "publish"]},
    {w:"publish",m:"\ucd9c\ud310\ud558\ub2e4",def:"to make books or magazines for sale",unit:4,opts:["length", "regularly", "publish", "flow"]},
  ],
  "bew4_5": [
    {w:"cough",m:"\uae30\uce68\ud558\ub2e4",def:"to force air out through your throat, often when sick",unit:5,opts:["cough", "smoke", "edge", "machine"]},
    {w:"crowd",m:"\uad70\uc911",def:"a large group of people",unit:5,opts:["crowd", "expect", "guide", "wheel"]},
    {w:"curious",m:"\ud638\uae30\uc2ec\uc774 \ub9ce\uc740",def:"wanting to know about something",unit:5,opts:["western", "expect", "curious", "explain"]},
    {w:"disappear",m:"\uc0ac\ub77c\uc9c0\ub2e4",def:"not to be seen or found",unit:5,opts:["machine", "strength", "disappear", "rub"]},
    {w:"edge",m:"\uac00\uc7a5\uc790\ub9ac",def:"the part of something where it ends or starts",unit:5,opts:["native", "western", "edge", "avenue"]},
    {w:"guide",m:"\uc5ec\ud589 \uc548\ub0b4\uc778",def:"someone who directs others on a trip",unit:5,opts:["guide", "western", "shine", "avenue"]},
    {w:"local",m:"\ud604\uc9c0\uc758",def:"from the place where you live",unit:5,opts:["local", "tour", "strength", "cough"]},
    {w:"machine",m:"\uae30\uacc4",def:"something that does work using moving parts",unit:5,opts:["local", "machine", "strength", "western"]},
    {w:"native",m:"\ud1a0\ubc15\uc774",def:"a person who was born or grew up in a certain place",unit:5,opts:["western", "explain", "curious", "native"]},
    {w:"smoke",m:"\uc5f0\uae30",def:"the cloud of gases that is made by fire",unit:5,opts:["disappear", "avenue", "western", "smoke"]},
    {w:"avenue",m:"\ub300\ub85c",def:"a wide street",unit:5,opts:["expect", "strength", "smoke", "avenue"]},
    {w:"expect",m:"\uc608\uc0c1\ud558\ub2e4",def:"to think something is likely to happen",unit:5,opts:["avenue", "cough", "guide", "expect"]},
    {w:"explain",m:"\uc124\uba85\ud558\ub2e4",def:"to make something easy to understand",unit:5,opts:["edge", "smoke", "explain", "cough"]},
    {w:"rub",m:"\ubb38\uc9c0\ub974\ub2e4",def:"to press with the fingers and move them from side to side",unit:5,opts:["rub", "strength", "native", "cough"]},
    {w:"shine",m:"\ube5b\ub098\ub2e4",def:"to produce bright light",unit:5,opts:["curious", "disappear", "rub", "shine"]},
    {w:"strength",m:"\ud798",def:"great physical power",unit:5,opts:["explain", "expect", "suggest", "strength"]},
    {w:"suggest",m:"\uc81c\uc548\ud558\ub2e4",def:"to say that something is good or a good idea",unit:5,opts:["local", "crowd", "disappear", "suggest"]},
    {w:"tour",m:"\uc5ec\ud589",def:"a journey to see several places",unit:5,opts:["cough", "tour", "guide", "disappear"]},
    {w:"western",m:"\uc11c\ucabd\uc758",def:"of or from the west",unit:5,opts:["strength", "western", "local", "wheel"]},
    {w:"wheel",m:"\ubc14\ud034",def:"something round which moves by turning",unit:5,opts:["native", "crowd", "explain", "wheel"]},
  ],
  "bew4_6": [
    {w:"cloth",m:"\uc637",def:"something used to make clothes",unit:6,opts:["fail", "cloth", "equal", "wrap"]},
    {w:"equal",m:"\uac19\uc740",def:"of the same size or number",unit:6,opts:["pattern", "equal", "penny", "fail"]},
    {w:"fail",m:"\uc2e4\ud328\ud558\ub2e4",def:"not to succeed",unit:6,opts:["pattern", "false", "wrap", "fail"]},
    {w:"false",m:"\uc0ac\uc2e4\uc774 \uc544\ub2cc",def:"not true",unit:6,opts:["increase", "avoid", "false", "wrap"]},
    {w:"goods",m:"\uc0c1\ud488",def:"things which are made and sold",unit:6,opts:["fail", "avoid", "medium", "goods"]},
    {w:"increase",m:"\uc99d\uac00\ud558\ub2e4",def:"to make bigger or more",unit:6,opts:["customer", "destroy", "separate", "increase"]},
    {w:"penny",m:"\ud398\ub2c8",def:"a coin equal to one cent in the US",unit:6,opts:["cloth", "penny", "equal", "trick"]},
    {w:"separate",m:"\ubd84\ub9ac\ud558\ub2e4",def:"not to be joined",unit:6,opts:["separate", "increase", "cloth", "total"]},
    {w:"total",m:"\uc804\uccb4",def:"the number of everything counted",unit:6,opts:["disappointed", "total", "avoid", "pattern"]},
    {w:"wrap",m:"\ud3ec\uc7a5\ud558\ub2e4",def:"to cover with something",unit:6,opts:["trick", "wrap", "penny", "pattern"]},
    {w:"appreciate",m:"\uc778\uc815\ud558\ub2e4",def:"to understand the importance of a person or thing",unit:6,opts:["wrap", "appreciate", "goods", "avoid"]},
    {w:"avoid",m:"\ud53c\ud558\ub2e4",def:"to stay away from",unit:6,opts:["equal", "trick", "fail", "avoid"]},
    {w:"convenient",m:"\ud3b8\ub9ac\ud55c",def:"easy to do and time-saving",unit:6,opts:["separate", "penny", "convenient", "avoid"]},
    {w:"customer",m:"\uace0\uac1d",def:"someone who buys goods or services from a store",unit:6,opts:["destroy", "disappointed", "penny", "customer"]},
    {w:"destroy",m:"\ud30c\uad34\ud558\ub2e4",def:"to cause something to end or not be of use anymore",unit:6,opts:["increase", "customer", "false", "destroy"]},
    {w:"disappointed",m:"\uc2e4\ub9dd\ud55c",def:"unhappy because something is not as you expected",unit:6,opts:["false", "pattern", "disappointed", "goods"]},
    {w:"medium",m:"\uc911\uac04\uc758",def:"of a size between big and small",unit:6,opts:["appreciate", "destroy", "penny", "medium"]},
    {w:"pattern",m:"\ubb34\ub2ac",def:"colors or shapes which are repeated on something",unit:6,opts:["separate", "pattern", "equal", "disappointed"]},
    {w:"trick",m:"\uc18d\uc774\ub2e4",def:"to make someone believe something that is not true",unit:6,opts:["destroy", "equal", "pattern", "trick"]},
    {w:"value",m:"\uac00\uce58",def:"how much something costs",unit:6,opts:["value", "fail", "penny", "false"]},
  ],
  "bew4_7": [
    {w:"beat",m:"\uc774\uae30\ub2e4",def:"to win a game or contest over someone else",unit:7,opts:["conduct", "wing", "confident", "beat"]},
    {w:"conduct",m:"\ud558\ub2e4",def:"to organize and do an event or activity",unit:7,opts:["conduct", "challenge", "beat", "noon"]},
    {w:"confident",m:"\uc790\uc2e0\uac10 \uc788\ub294",def:"believing that you are able to do something well",unit:7,opts:["speed", "noon", "muscle", "confident"]},
    {w:"lead",m:"\uc548\ub0b4\ud558\ub2e4",def:"to show people the way to go",unit:7,opts:["position", "lead", "conduct", "challenge"]},
    {w:"lift",m:"\uc62c\ub9ac\ub2e4",def:"to move to a higher place",unit:7,opts:["speed", "muscle", "skill", "lift"]},
    {w:"male",m:"\ub0a8\uc131\uc758",def:"being a man or boy",unit:7,opts:["speed", "male", "position", "beat"]},
    {w:"muscle",m:"\uadfc\uc721",def:"a body part that works to move arms and legs",unit:7,opts:["trouble", "beat", "record", "muscle"]},
    {w:"speed",m:"\uc18d\ub3c4",def:"how fast something moves",unit:7,opts:["lift", "speed", "skill", "noon"]},
    {w:"stretch",m:"\ub298\ub9ac\ub2e4",def:"to pull or move until tight",unit:7,opts:["lift", "position", "male", "stretch"]},
    {w:"trouble",m:"\ubb38\uc81c",def:"a problem or difficulty",unit:7,opts:["trouble", "wing", "skill", "lift"]},
    {w:"captain",m:"\uc8fc\uc7a5",def:"a person who is the leader of a team",unit:7,opts:["lift", "lead", "captain", "conduct"]},
    {w:"challenge",m:"\ub3c4\uc804",def:"something that is difficult to do",unit:7,opts:["wing", "encourage", "skill", "challenge"]},
    {w:"complete",m:"\uc644\uc131\ud558\ub2e4",def:"to finish something",unit:7,opts:["noon", "complete", "conduct", "challenge"]},
    {w:"encourage",m:"\uaca9\ub824\ud558\ub2e4",def:"to help someone feel confident",unit:7,opts:["race", "encourage", "trouble", "skill"]},
    {w:"noon",m:"\uc815\uc624",def:"12 o\u2019clock in the daytime",unit:7,opts:["noon", "race", "stretch", "record"]},
    {w:"position",m:"\uc704\uce58",def:"the place where a person or thing is",unit:7,opts:["lift", "position", "skill", "trouble"]},
    {w:"race",m:"\uacbd\uc8fc",def:"a contest to decide who is the fastest",unit:7,opts:["race", "encourage", "complete", "challenge"]},
    {w:"record",m:"\uae30\ub85d",def:"the highest or best result ever in an activity",unit:7,opts:["trouble", "captain", "record", "speed"]},
    {w:"skill",m:"\uae30\uc220",def:"the ability to do something well",unit:7,opts:["confident", "challenge", "record", "skill"]},
    {w:"wing",m:"\ub0a0\uac1c",def:"one of the body parts that birds and insects use to fly",unit:7,opts:["record", "lift", "wing", "encourage"]},
  ],
  "bew4_8": [
    {w:"certain",m:"\ud655\uc2e0\ud558\ub294",def:"believing something strongly",unit:8,opts:["section", "major", "certain", "gather"]},
    {w:"discuss",m:"\ud1a0\ub860\ud558\ub2e4",def:"to talk with someone about something",unit:8,opts:["discuss", "career", "certain", "attack"]},
    {w:"edit",m:"\ud3b8\uc9d1\ud558\ub2e4",def:"to look at something carefully and correct any mistakes",unit:8,opts:["handle", "edit", "screen", "material"]},
    {w:"gather",m:"\ubaa8\uc774\ub2e4",def:"to bring things or people together",unit:8,opts:["positive", "attack", "gather", "handle"]},
    {w:"image",m:"\uc774\ubbf8\uc9c0",def:"a picture",unit:8,opts:["major", "image", "career", "connect"]},
    {w:"material",m:"\uc7ac\ub8cc",def:"something needed to do an activity",unit:8,opts:["material", "positive", "career", "provide"]},
    {w:"positive",m:"\uae0d\uc815\uc801\uc778",def:"thinking good things",unit:8,opts:["screen", "handle", "image", "positive"]},
    {w:"role",m:"\uc5ed\ud560",def:"a part or job someone has in an activity or event",unit:8,opts:["screen", "image", "role", "technology"]},
    {w:"screen",m:"\ud654\uba74",def:"the part of a computer that shows images and words",unit:8,opts:["image", "gather", "screen", "discuss"]},
    {w:"technology",m:"\uacfc\ud559 \uae30\uc220",def:"any type of useful machine invented by science",unit:8,opts:["provide", "connect", "career", "technology"]},
    {w:"attack",m:"\uacf5\uaca9\ud558\ub2e4",def:"to try to hurt physically or say hurtful things",unit:8,opts:["dictionary", "positive", "attack", "gather"]},
    {w:"available",m:"\uc774\uc6a9 \uac00\ub2a5\ud55c",def:"able to be used",unit:8,opts:["available", "career", "positive", "technology"]},
    {w:"career",m:"\uc9c1\uc5c5",def:"what a person does for his or her job",unit:8,opts:["career", "role", "technology", "material"]},
    {w:"connect",m:"\uc5f0\uacb0\ud558\ub2e4",def:"to join something with something else",unit:8,opts:["connect", "edit", "site", "material"]},
    {w:"dictionary",m:"\uc0ac\uc804",def:"a book that gives definitions of words",unit:8,opts:["positive", "material", "dictionary", "discuss"]},
    {w:"handle",m:"\ub2e4\ub8e8\ub2e4",def:"to deal with a person or thing",unit:8,opts:["handle", "connect", "site", "provide"]},
    {w:"major",m:"\uc2ec\uac01\ud55c",def:"very important; very serious",unit:8,opts:["career", "discuss", "major", "certain"]},
    {w:"provide",m:"\uc81c\uacf5\ud558\ub2e4",def:"to offer or give",unit:8,opts:["provide", "career", "handle", "screen"]},
    {w:"section",m:"\uad6c\uc5ed",def:"a part of something",unit:8,opts:["image", "gather", "role", "section"]},
    {w:"site",m:"\uc7a5\uc18c, \uc0ac\uc774\ud2b8 (\uc778\ud130\ub137)",def:"a spot or place, usually on the Internet",unit:8,opts:["dictionary", "discuss", "screen", "site"]},
  ],
  "bew4_9": [
    {w:"accept",m:"\ubc1b\ub2e4",def:"to take or receive",unit:9,opts:["root", "society", "host", "accept"]},
    {w:"consider",m:"\uace0\ub824\ud558\ub2e4",def:"to think about carefully",unit:9,opts:["fortune", "guest", "consider", "society"]},
    {w:"exist",m:"\uc874\uc7ac\ud558\ub2e4",def:"to be",unit:9,opts:["original", "trust", "wealthy", "exist"]},
    {w:"familiar",m:"\ub0af\uc775\uc740",def:"commonly known or seen",unit:9,opts:["wealthy", "consider", "familiar", "band"]},
    {w:"joy",m:"\uc990\uac70\uc6c0",def:"great happiness",unit:9,opts:["trust", "joy", "band", "familiar"]},
    {w:"married",m:"\uacb0\ud63c\ud55c",def:"being a husband or wife",unit:9,opts:["society", "poem", "married", "fortune"]},
    {w:"rather",m:"\ucc28\ub77c\ub9ac",def:"used to say what you prefer to do or have",unit:9,opts:["guest", "root", "rather", "original"]},
    {w:"represent",m:"\ub098\ud0c0\ub0b4\ub2e4",def:"to be a symbol for something",unit:9,opts:["rather", "sense", "represent", "society"]},
    {w:"root",m:"\uc6d0\uc778",def:"the cause of something",unit:9,opts:["root", "trust", "society", "wealthy"]},
    {w:"society",m:"\uc0ac\ud68c",def:"a group of people living in a community",unit:9,opts:["trust", "root", "society", "sense"]},
    {w:"band",m:"\uc545\ub2e8",def:"a group that plays music",unit:9,opts:["fortune", "represent", "band", "accept"]},
    {w:"fortune",m:"\uc7ac\uc0b0",def:"a large amount of money",unit:9,opts:["fortune", "rather", "trust", "society"]},
    {w:"guest",m:"\uc190\ub2d8",def:"a person who spends time at another\u2019s home",unit:9,opts:["society", "rather", "trust", "guest"]},
    {w:"host",m:"\uc8fc\uc778",def:"a person who accepts guests into a home or restaurant",unit:9,opts:["peace", "host", "rather", "guest"]},
    {w:"original",m:"\ub3c5\ucc3d\uc801\uc778",def:"made or produced for the first time; new",unit:9,opts:["exist", "familiar", "fortune", "original"]},
    {w:"peace",m:"\ud3c9\ud654",def:"when people live together well and do not cause trouble",unit:9,opts:["familiar", "sense", "host", "peace"]},
    {w:"poem",m:"\uc2dc",def:"a type of writing which often uses rhymes like make and bake",unit:9,opts:["poem", "fortune", "married", "trust"]},
    {w:"sense",m:"\ub290\ub07c\ub2e4",def:"to know something without having evidence that it is true",unit:9,opts:["guest", "wealthy", "sense", "peace"]},
    {w:"trust",m:"\ubbff\ub2e4",def:"to have confidence in a person or thing",unit:9,opts:["exist", "sense", "trust", "married"]},
    {w:"wealthy",m:"\ubd80\uc720\ud55c",def:"having a large amount of money",unit:9,opts:["host", "poem", "wealthy", "rather"]},
  ],
  "bew4_10": [
    {w:"blood",m:"\ud53c",def:"the red liquid in your body",unit:10,opts:["electronic", "warn", "shoot", "blood"]},
    {w:"business",m:"\uc0ac\uc5c5",def:"something that makes money by selling goods or services",unit:10,opts:["achieve", "signal", "teenager", "business"]},
    {w:"electronic",m:"\uc804\uc790\uc758",def:"relating to things that use electricity",unit:10,opts:["influence", "electronic", "master", "similar"]},
    {w:"influence",m:"\uc601\ud5a5",def:"the power to affect a person or thing",unit:10,opts:["business", "electronic", "beg", "influence"]},
    {w:"master",m:"\uc219\ub2ec\ud558\ub2e4",def:"to become very skilled at something",unit:10,opts:["improve", "warn", "war", "master"]},
    {w:"pity",m:"\uc720\uac10",def:"feeling sorry for another person or animal",unit:10,opts:["pity", "debate", "teenager", "control"]},
    {w:"press",m:"\uc5b8\ub860",def:"all the people and groups who provide the news",unit:10,opts:["press", "beg", "shoot", "electronic"]},
    {w:"shoot",m:"\uc3d8\ub2e4",def:"to make one thing come out of another at a fast speed",unit:10,opts:["signal", "business", "electronic", "shoot"]},
    {w:"signal",m:"\uc2e0\ud638\ub97c \ubcf4\ub0b4\ub2e4",def:"to communicate by making a sign or sound",unit:10,opts:["debate", "signal", "control", "press"]},
    {w:"teenager",m:"\uc2ed\ub300",def:"a person between the ages of thirteen and nineteen",unit:10,opts:["pity", "teenager", "soldier", "similar"]},
    {w:"achieve",m:"\ub2ec\uc131\ud558\ub2e4",def:"to get something by working hard",unit:10,opts:["electronic", "achieve", "business", "beg"]},
    {w:"beg",m:"\uc560\uc6d0\ud558\ub2e4",def:"to ask for something again and again",unit:10,opts:["signal", "master", "electronic", "beg"]},
    {w:"control",m:"\uc9c0\ubc30\ud558\ub2e4",def:"to be in charge of a person or thing",unit:10,opts:["control", "teenager", "similar", "debate"]},
    {w:"debate",m:"\ud1a0\ub860\ud558\ub2e4",def:"to exchange opinions about a topic",unit:10,opts:["signal", "debate", "achieve", "similar"]},
    {w:"improve",m:"\ud5a5\uc0c1\uc2dc\ud0a4\ub2e4",def:"to get better at something",unit:10,opts:["warn", "master", "improve", "press"]},
    {w:"similar",m:"\ube44\uc2b7\ud55c",def:"almost the same",unit:10,opts:["control", "shoot", "similar", "soldier"]},
    {w:"soldier",m:"\uad70\uc778",def:"a person who trains to fight for his or her country",unit:10,opts:["soldier", "signal", "achieve", "beg"]},
    {w:"system",m:"\uccb4\uc81c",def:"a group of parts that move or work together",unit:10,opts:["shoot", "influence", "achieve", "system"]},
    {w:"war",m:"\uc804\uc7c1",def:"fighting between two countries or groups",unit:10,opts:["war", "influence", "business", "debate"]},
    {w:"warn",m:"\uacbd\uace0\ud558\ub2e4",def:"to tell someone to be careful",unit:10,opts:["soldier", "electronic", "business", "warn"]},
  ],
  "bew4_11": [
    {w:"announce",m:"\uc54c\ub9ac\ub2e4",def:"to make something known to many people",unit:11,opts:["sheet", "respond", "proper", "announce"]},
    {w:"bottom",m:"\ubc14\ub2e5",def:"the lowest point of something",unit:11,opts:["bottom", "exhibit", "spell", "structure"]},
    {w:"compete",m:"\uacbd\uc7c1\ud558\ub2e4",def:"to try to be better or faster than another",unit:11,opts:["spell", "compete", "announce", "prize"]},
    {w:"copy",m:"\ubcf5\uc0ac\ud558\ub2e4",def:"to make or do the same thing as something else",unit:11,opts:["exhibit", "copy", "project", "state"]},
    {w:"exhibit",m:"\uc804\uc2dc\ud488",def:"something shown in a museum or for an event",unit:11,opts:["compete", "exhibit", "respond", "sheet"]},
    {w:"print",m:"\uc778\uc1c4\ud558\ub2e4",def:"to produce words or images on paper using a machine",unit:11,opts:["bottom", "print", "compete", "select"]},
    {w:"project",m:"\ud504\ub85c\uc81d\ud2b8",def:"a planned piece of work that takes time to finish",unit:11,opts:["project", "spell", "exhibit", "state"]},
    {w:"proper",m:"\uc801\uc808\ud55c",def:"correct or right",unit:11,opts:["structure", "proper", "maximum", "sheet"]},
    {w:"select",m:"\uace0\ub974\ub2e4",def:"to choose",unit:11,opts:["concentrate", "select", "print", "research"]},
    {w:"sheet",m:"\uc885\uc774 \ud55c \uc7a5",def:"a piece of flat material like paper",unit:11,opts:["project", "copy", "compete", "sheet"]},
    {w:"concentrate",m:"\uc9d1\uc911\ud558\ub2e4",def:"to put all your energy on one thing",unit:11,opts:["select", "concentrate", "prize", "bottom"]},
    {w:"maximum",m:"\ucd5c\ub300\uc758",def:"greatest possible",unit:11,opts:["structure", "project", "state", "maximum"]},
    {w:"prize",m:"\uc0c1",def:"something you get for winning",unit:11,opts:["require", "print", "exhibit", "prize"]},
    {w:"require",m:"\ud544\uc694\ub85c \ud558\ub2e4",def:"to have to; to be necessary to do",unit:11,opts:["project", "require", "sheet", "maximum"]},
    {w:"research",m:"\uc5f0\uad6c\ud558\ub2e4",def:"to study something carefully and try to discover new facts",unit:11,opts:["tool", "research", "compete", "prize"]},
    {w:"respond",m:"\ub300\ub2f5\ud558\ub2e4",def:"to answer",unit:11,opts:["respond", "sheet", "concentrate", "copy"]},
    {w:"spell",m:"\ucca0\uc790\ub97c \ub9d0\ud558\ub2e4",def:"to write or say the letters of a word",unit:11,opts:["compete", "require", "spell", "exhibit"]},
    {w:"state",m:"\ub9d0\ud558\ub2e4",def:"to say something",unit:11,opts:["announce", "research", "state", "print"]},
    {w:"structure",m:"\uad6c\uc870\ubb3c",def:"something that is built",unit:11,opts:["prize", "structure", "select", "copy"]},
    {w:"tool",m:"\uc5f0\uc7a5",def:"anything used to do a job",unit:11,opts:["tool", "spell", "prize", "structure"]},
  ],
  "bew4_12": [
    {w:"flood",m:"\ud64d\uc218",def:"a great amount of water over land that is usually dry",unit:12,opts:["waste", "task", "worth", "flood"]},
    {w:"gentle",m:"\uc628\uc21c\ud55c",def:"not mean or unkind",unit:12,opts:["task", "temperature", "gentle", "operate"]},
    {w:"melt",m:"\ub179\ub2e4",def:"to change into liquid",unit:12,opts:["remain", "storm", "task", "melt"]},
    {w:"operate",m:"\uc870\uc791\ud558\ub2e4",def:"to use or make something work",unit:12,opts:["operate", "stream", "temperature", "flood"]},
    {w:"recognize",m:"\uc54c\uc544\ubcf4\ub2e4",def:"to know a person or thing because it is familiar",unit:12,opts:["waste", "gentle", "recognize", "various"]},
    {w:"remain",m:"\ub0a8\uc544 \uc788\ub2e4",def:"to stay in one place",unit:12,opts:["melt", "recently", "remain", "various"]},
    {w:"task",m:"\uc77c",def:"work",unit:12,opts:["responsible", "task", "temperature", "waste"]},
    {w:"various",m:"\ub2e4\uc591\ud55c",def:"of different kinds",unit:12,opts:["factory", "melt", "gentle", "various"]},
    {w:"waste",m:"\ub0ad\ube44\ud558\ub2e4",def:"to use too much of something",unit:12,opts:["task", "waste", "responsible", "operate"]},
    {w:"worth",m:"\uac00\uce58 \uc788\ub294",def:"having a value in money",unit:12,opts:["storm", "worth", "recently", "melt"]},
    {w:"climate",m:"\uae30\ud6c4",def:"the weather of a place",unit:12,opts:["factory", "climate", "freeze", "waste"]},
    {w:"emergency",m:"\ube44\uc0c1\uc0ac\ud0dc",def:"a sudden, serious event when people need help immediately",unit:12,opts:["melt", "emergency", "stream", "freeze"]},
    {w:"factory",m:"\uacf5\uc7a5",def:"a building that produces goods",unit:12,opts:["responsible", "factory", "freeze", "recently"]},
    {w:"freeze",m:"\uc5bc\ub2e4",def:"to turn into ice",unit:12,opts:["storm", "stream", "remain", "freeze"]},
    {w:"population",m:"\uc778\uad6c",def:"the total number of people or animals living in a place",unit:12,opts:["population", "recognize", "worth", "melt"]},
    {w:"recently",m:"\ucd5c\uadfc\uc5d0",def:"not long ago",unit:12,opts:["waste", "recognize", "recently", "task"]},
    {w:"responsible",m:"\ucc45\uc784\uac10 \uc788\ub294",def:"able to act correctly and make good decisions",unit:12,opts:["freeze", "temperature", "responsible", "factory"]},
    {w:"storm",m:"\ud3ed\ud48d\uc6b0",def:"a bad weather event with a lot of rain, wind, or snow",unit:12,opts:["remain", "flood", "recently", "storm"]},
    {w:"stream",m:"\uac1c\uc6b8",def:"a very small river",unit:12,opts:["emergency", "stream", "recently", "climate"]},
    {w:"temperature",m:"\uccb4\uc628",def:"how hot or cold a person or thing is",unit:12,opts:["emergency", "temperature", "operate", "recognize"]},
  ],
};
// ?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺?곣봺??//  2000 Core English Words (1-4) + 4000 Essential English Words (1-6)

