// Wonderful World Basic Lv.5 word bank.
export const WW5_WORDS = [
  {w:"sky",m:"\ud558\ub298",def:"the space over the Earth",unit:1,opts:["sky", "wind", "cloud", "moon"]},
  {w:"wind",m:"\ubc14\ub78c",def:"a natural movement of air outside",unit:1,opts:["sky", "wind", "bright", "watch"]},
  {w:"cloud",m:"\uad6c\ub984",def:"a white or gray mass in the sky made of tiny water drops",unit:1,opts:["moon", "cloud", "wind", "sky"]},
  {w:"moon",m:"\ub2ec",def:"the round object moving around Earth, seen at night",unit:1,opts:["moon", "cloud", "east", "west"]},
  {w:"bright",m:"\ubc1d\uc740",def:"having very light and strong colors",unit:1,opts:["bright", "watch", "east", "west"]},
  {w:"watch",m:"\ubcf4\ub2e4",def:"to look at someone or something for a period of time",unit:1,opts:["sky", "watch", "bright", "wind"]},
  {w:"east",m:"\ub3d9\ucabd",def:"the direction where the sun rises",unit:1,opts:["east", "west", "cloud", "moon"]},
  {w:"west",m:"\uc11c\ucabd",def:"the direction where the sun sets",unit:1,opts:["east", "west", "bright", "sky"]},
  {w:"ride",m:"\ud0c0\ub2e4",def:"to sit on and control the movements of",unit:2,opts:["ride", "school", "vacation", "cold"]},
  {w:"school",m:"\ud559\uad50",def:"a place where children go to learn",unit:2,opts:["school", "vacation", "month", "start"]},
  {w:"vacation",m:"\ubc29\ud559",def:"a time when schools and universities are closed",unit:2,opts:["ride", "vacation", "cold", "January"]},
  {w:"cold",m:"\ucd94\uc6b4",def:"having a very low temperature",unit:2,opts:["cold", "month", "start", "school"]},
  {w:"month",m:"\ub2ec",def:"any one of the 12 parts into which the year is divided",unit:2,opts:["month", "ride", "January", "June"]},
  {w:"start",m:"\uc2dc\uc791\ud558\ub2e4",def:"to begin to happen, to exist, or to be done",unit:2,opts:["start", "cold", "school", "vacation"]},
  {w:"January",m:"1\uc6d4",def:"the first month of the year",unit:2,opts:["January", "June", "month", "start"]},
  {w:"June",m:"6\uc6d4",def:"the sixth month of the year",unit:2,opts:["June", "January", "cold", "ride"]},
  {w:"watch TV",m:"TV\ub97c \uc2dc\uccad\ud558\ub2e4",def:"to look at programs broadcast on television",unit:3,opts:["watch TV", "watch a movie", "study", "think"]},
  {w:"watch a movie",m:"\uc601\ud654\ub97c \ubcf4\ub2e4",def:"to look at a movie on TV or using a computer",unit:3,opts:["watch a movie", "watch TV", "arcade game", "mobile game"]},
  {w:"study",m:"\uacf5\ubd80\ud558\ub2e4",def:"the activity of learning or gaining knowledge",unit:3,opts:["study", "rainy", "think", "watch TV"]},
  {w:"rainy",m:"\ube44\uac00 \uc624\ub294",def:"having a lot of rain",unit:3,opts:["rainy", "study", "think", "arcade game"]},
  {w:"think",m:"\uc0dd\uac01\ud558\ub2e4",def:"to have an opinion about someone or something",unit:3,opts:["think", "rainy", "study", "mobile game"]},
  {w:"arcade game",m:"\uc544\ucf00\uc774\ub4dc \uac8c\uc784",def:"an electronic or coin-operated game",unit:3,opts:["arcade game", "mobile game", "watch TV", "study"]},
  {w:"mobile game",m:"\ubaa8\ubc14\uc77c \uac8c\uc784",def:"a game designed for mobile devices",unit:3,opts:["mobile game", "arcade game", "rainy", "think"]},
  {w:"ski",m:"\uc2a4\ud0a4",def:"a long narrow runner for gliding over snow",unit:4,opts:["ski", "jump", "mountain", "snowboard"]},
  {w:"jump",m:"\ub6f0\ub2e4",def:"to push yourself off the ground into the air",unit:4,opts:["jump", "ski", "snowboard", "helmet"]},
  {w:"mountain",m:"\uc0b0",def:"a large steep hill",unit:4,opts:["mountain", "ski", "snowboard", "stick"]},
  {w:"snowboard",m:"\uc2a4\ub178\ubcf4\ub4dc",def:"a board for gliding on snow",unit:4,opts:["snowboard", "ski", "mountain", "jump"]},
  {w:"play ice hockey",m:"\uc544\uc774\uc2a4 \ud558\ud0a4\ub97c \ud558\ub2e4",def:"to participate in ice hockey",unit:4,opts:["play ice hockey", "ice skate", "jump", "ski"]},
  {w:"ice skate",m:"\uc2a4\ucf00\uc774\ud2b8\ub97c \ud0c0\ub2e4",def:"to skate on ice",unit:4,opts:["ice skate", "play ice hockey", "snowboard", "mountain"]},
  {w:"helmet",m:"\ud5ec\uba67",def:"a strong hard hat that protects the head",unit:4,opts:["helmet", "stick", "jump", "ski"]},
  {w:"stick",m:"\uc2a4\ud2f1",def:"a long thin object used to hit or direct a puck",unit:4,opts:["stick", "helmet", "mountain", "snowboard"]},
  {w:"go camping",m:"\ucea0\ud551 \uac00\ub2e4",def:"to stay in a tent usually for enjoyment",unit:5,opts:["go camping", "tent", "fire", "bring"]},
  {w:"tent",m:"\ud150\ud2b8",def:"a portable shelter used outdoors",unit:5,opts:["tent", "go camping", "sleeping bag", "flashlight"]},
  {w:"fire",m:"\ubd88",def:"the light, heat, and flame produced by burning",unit:5,opts:["fire", "bring", "sea", "forest"]},
  {w:"bring",m:"\uac00\uc838\uc624\ub2e4",def:"to come with something or someone to a place",unit:5,opts:["bring", "fire", "tent", "flashlight"]},
  {w:"flashlight",m:"\uc190\uc804\ub4f1",def:"a small electric light carried in your hand",unit:5,opts:["flashlight", "sleeping bag", "bring", "go camping"]},
  {w:"sleeping bag",m:"\uce68\ub0ad",def:"a warm long bag used for sleeping outdoors",unit:5,opts:["sleeping bag", "flashlight", "tent", "fire"]},
  {w:"sea",m:"\ubc14\ub2e4",def:"the salt water that covers much of the Earth's surface",unit:5,opts:["sea", "forest", "fire", "bring"]},
  {w:"forest",m:"\uc232",def:"a thick growth of trees covering a large area",unit:5,opts:["forest", "sea", "go camping", "tent"]},
  {w:"go hiking",m:"\ud558\uc774\ud0b9\ud558\ub7ec \uac00\ub2e4",def:"to walk a long distance for pleasure",unit:6,opts:["go hiking", "beach", "have a picnic", "ride a bike"]},
  {w:"beach",m:"\ud574\ubcc0",def:"an area of sand next to an ocean",unit:6,opts:["beach", "backyard", "go hiking", "forest"]},
  {w:"have a picnic",m:"\uc18c\ud48d \uac00\ub2e4",def:"to take food and eat it outdoors",unit:6,opts:["have a picnic", "go hiking", "ride a bike", "backyard"]},
  {w:"backyard",m:"\ub4b7\ub9c8\ub2f9",def:"an area in back of a house",unit:6,opts:["backyard", "beach", "inside", "outside"]},
  {w:"ride a bike",m:"\uc790\uc804\uac70\ub97c \ud0c0\ub2e4",def:"to sit on a bike and travel along on it",unit:6,opts:["ride a bike", "go hiking", "have a picnic", "beach"]},
  {w:"inside",m:"\uc548\uc5d0",def:"in or into the inner part of a building",unit:6,opts:["inside", "outside", "backyard", "beach"]},
  {w:"outside",m:"\ubc16\uc5d0",def:"in or near a building, not inside it",unit:6,opts:["outside", "inside", "forest", "beach"]},
  {w:"job",m:"\uc9c1\uc5c5",def:"the work a person does regularly to earn money",unit:7,opts:["job", "photographer", "chef", "doctor"]},
  {w:"photographer",m:"\uc0ac\uc9c4\uc791\uac00",def:"a person who takes photographs as a job",unit:7,opts:["photographer", "chef", "deliveryman", "scientist"]},
  {w:"chef",m:"\uc694\ub9ac\uc0ac",def:"a person who prepares food for people to eat",unit:7,opts:["chef", "doctor", "photographer", "scientist"]},
  {w:"doctor",m:"\uc758\uc0ac",def:"a person skilled in the science of medicine",unit:7,opts:["doctor", "chef", "deliveryman", "job"]},
  {w:"deliveryman",m:"\ubc30\ub2ec\uc6d0",def:"a man who delivers goods to customers",unit:7,opts:["deliveryman", "scientist", "photographer", "chef"]},
  {w:"scientist",m:"\uacfc\ud559\uc790",def:"a person who studies one or more natural sciences",unit:7,opts:["scientist", "doctor", "deliveryman", "photographer"]},
  {w:"take pictures",m:"\uc0ac\uc9c4\uc744 \ucc0d\ub2e4",def:"to create images with a camera",unit:7,opts:["take pictures", "help sick people", "job", "chef"]},
  {w:"help sick people",m:"\uc544\ud508 \uc0ac\ub78c\ub4e4\uc744 \ub3d5\ub2e4",def:"to aid sick people",unit:7,opts:["help sick people", "take pictures", "deliveryman", "scientist"]},
  {w:"unusual",m:"\ud2b9\uc774\ud55c",def:"not normal or usual",unit:8,opts:["unusual", "famous", "robot", "money"]},
  {w:"famous",m:"\uc720\uba85\ud55c",def:"known or recognized by very many people",unit:8,opts:["famous", "unusual", "excited", "love"]},
  {w:"robot",m:"\ub85c\ubd07",def:"a machine that looks like a human, controlled by computer",unit:8,opts:["robot", "money", "river", "ocean"]},
  {w:"money",m:"\ub3c8",def:"something used to pay for goods and services",unit:8,opts:["money", "robot", "unusual", "excited"]},
  {w:"excited",m:"\uc2e0\uc774 \ub09c",def:"very enthusiastic and eager about something",unit:8,opts:["excited", "love", "famous", "unusual"]},
  {w:"love",m:"\uc0ac\ub791\ud558\ub2e4",def:"to feel great affection for someone",unit:8,opts:["love", "excited", "money", "robot"]},
  {w:"river",m:"\uac15",def:"a natural flow of water flowing in a channel to the sea",unit:8,opts:["river", "ocean", "unusual", "famous"]},
  {w:"ocean",m:"\ubc14\ub2e4",def:"the salt water covering much of Earth's surface",unit:8,opts:["ocean", "river", "robot", "money"]},
  {w:"pilot",m:"\uc870\uc885\uc0ac",def:"a person who flies an airplane or helicopter",unit:9,opts:["pilot", "astronaut", "nurse", "vet"]},
  {w:"astronaut",m:"\uc6b0\uc8fc \ube44\ud589\uc0ac",def:"a person who travels in a spacecraft into outer space",unit:9,opts:["astronaut", "pilot", "firefighter", "actor"]},
  {w:"nurse",m:"\uac04\ud638\uc0ac",def:"a person who takes care of sick or injured people",unit:9,opts:["nurse", "vet", "doctor", "pilot"]},
  {w:"vet",m:"\uc218\uc758\uc0ac",def:"an animal doctor",unit:9,opts:["vet", "nurse", "pilot", "astronaut"]},
  {w:"actor",m:"\ubc30\uc6b0",def:"a person who acts in a play or movie",unit:9,opts:["actor", "firefighter", "cool", "awesome"]},
  {w:"firefighter",m:"\uc18c\ubc29\uad00",def:"a member of a group that works to put out fires",unit:9,opts:["firefighter", "actor", "nurse", "vet"]},
  {w:"cool",m:"\uba4b\uc9c4",def:"often used to show approval in a general way",unit:9,opts:["cool", "awesome", "actor", "pilot"]},
  {w:"awesome",m:"\ub300\ub2e8\ud55c",def:"used to show that something is very good or great fun",unit:9,opts:["awesome", "cool", "firefighter", "astronaut"]},
  {w:"laptop",m:"\ub178\ud2b8\ubd81",def:"a small computer designed to be easily carried",unit:10,opts:["laptop", "screen", "keyboard", "email"]},
  {w:"screen",m:"\ud654\uba74",def:"the flat part of a TV showing images or text",unit:10,opts:["screen", "laptop", "smartphone", "tablet"]},
  {w:"keyboard",m:"\ud0a4\ubcf4\ub4dc",def:"the set of keys used for a computer or typewriter",unit:10,opts:["keyboard", "screen", "email", "mobile devices"]},
  {w:"email",m:"\uc774\uba54\uc77c",def:"an electronic mail message",unit:10,opts:["email", "laptop", "keyboard", "screen"]},
  {w:"smartphone",m:"\uc2a4\ub9c8\ud2b8\ud3f0",def:"a mobile phone that works as a computer",unit:10,opts:["smartphone", "tablet", "laptop", "email"]},
  {w:"tablet",m:"\ud0dc\ube14\ub9bf",def:"a portable computer with a large touch screen",unit:10,opts:["tablet", "smartphone", "screen", "keyboard"]},
  {w:"mobile devices",m:"\ubaa8\ubc14\uc77c \uae30\uae30",def:"any types of handheld and portable computers",unit:10,opts:["mobile devices", "laptop", "email", "screen"]},
  {w:"busy",m:"\ubc14\uc05c",def:"full of activity or work",unit:11,opts:["busy", "easy", "app", "math"]},
  {w:"easy",m:"\uc26c\uc6b4",def:"not hard to do",unit:11,opts:["easy", "difficult", "busy", "slow"]},
  {w:"app",m:"\uc571",def:"a computer program that performs a special function",unit:11,opts:["app", "math", "teach", "learn"]},
  {w:"math",m:"\uc218\ud559",def:"mathematics, especially as a subject in school",unit:11,opts:["math", "app", "difficult", "easy"]},
  {w:"difficult",m:"\uc5b4\ub824\uc6b4",def:"not easy",unit:11,opts:["difficult", "easy", "slow", "busy"]},
  {w:"slow",m:"\ub290\ub9b0",def:"not moving quickly",unit:11,opts:["slow", "difficult", "busy", "app"]},
  {w:"teach",m:"\uac00\ub974\uce58\ub2e4",def:"to help a person learn how to do something",unit:11,opts:["teach", "learn", "busy", "app"]},
  {w:"learn",m:"\ubc30\uc6b0\ub2e4",def:"to gain knowledge by studying",unit:11,opts:["learn", "teach", "slow", "difficult"]},
  {w:"touch",m:"\ub9cc\uc9c0\ub2e4",def:"to put your hand or fingers on someone or something",unit:12,opts:["touch", "password", "need", "safe"]},
  {w:"password",m:"\ube44\ubc00\ubc88\ud638",def:"a secret code that allows you to use a computer system",unit:12,opts:["password", "touch", "login", "download"]},
  {w:"need",m:"\ud544\uc694\ud558\ub2e4",def:"to require something",unit:12,opts:["need", "safe", "send", "share"]},
  {w:"safe",m:"\uc548\uc804\ud55c",def:"not in danger",unit:12,opts:["safe", "need", "touch", "password"]},
  {w:"send",m:"\ubcf4\ub0b4\ub2e4",def:"to make something go to a place, especially by email",unit:12,opts:["send", "share", "login", "download"]},
  {w:"share",m:"\uacf5\uc720\ud558\ub2e4",def:"to have or use something with others",unit:12,opts:["share", "send", "need", "safe"]},
  {w:"login",m:"\ub85c\uadf8\uc778",def:"an act of logging in to a computer or online account",unit:12,opts:["login", "download", "password", "touch"]},
  {w:"download",m:"\ub2e4\uc6b4\ub85c\ub4dc\ud558\ub2e4",def:"to get data from another computer via the internet",unit:12,opts:["download", "login", "send", "share"]},
];

// 1000 Basic English Words ??Books 2, 3, 4

